package defpackage;

import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class abdm {
    public static final abbd A;
    public static final abbe B;
    public static final abbd C;
    public static final abbe D;
    public static final abbd E;
    public static final abbe F;
    public static final abbd G;
    public static final abbe H;
    public static final abbd I;
    public static final abbe J;
    public static final abbd K;
    public static final abbe L;
    public static final abbd M;
    public static final abbe N;
    public static final abbd O;
    public static final abbe P;
    public static final abbd Q;
    public static final abbe R;
    public static final abbd S;
    public static final abbe T;
    public static final abbe U;
    public static final abbd a;
    public static final abbe b;
    public static final abbd c;
    public static final abbe d;
    public static final abbd e;
    public static final abbe f;
    public static final abbd g;
    public static final abbe h;
    public static final abbd i;
    public static final abbe j;
    public static final abbd k;
    public static final abbe l;
    public static final abbd m;
    public static final abbe n;
    public static final abbd o;
    public static final abbe p;
    public static final abbd q;
    public static final abbe r;
    public static final abbd s;
    public static final abbd t;
    public static final abbe u;
    public static final abbd v;
    public static final abbd w;
    public static final abbd x;
    public static final abbd y;
    public static final abbe z;

    static {
        abbd abbdVarA = new abcs().a();
        a = abbdVarA;
        b = new abdb(Class.class, abbdVarA);
        abbd abbdVarA2 = new abdc().a();
        c = abbdVarA2;
        d = new abdb(BitSet.class, abbdVarA2);
        abdg abdgVar = new abdg();
        e = abdgVar;
        f = new abdd(Boolean.TYPE, Boolean.class, abdgVar);
        abdh abdhVar = new abdh();
        g = abdhVar;
        h = new abdd(Byte.TYPE, Byte.class, abdhVar);
        abdi abdiVar = new abdi();
        i = abdiVar;
        j = new abdd(Short.TYPE, Short.class, abdiVar);
        abdj abdjVar = new abdj();
        k = abdjVar;
        l = new abdd(Integer.TYPE, Integer.class, abdjVar);
        abbd abbdVarA3 = new abdk().a();
        m = abbdVarA3;
        n = new abdb(AtomicInteger.class, abbdVarA3);
        abbd abbdVarA4 = new abdl().a();
        o = abbdVarA4;
        p = new abdb(AtomicBoolean.class, abbdVarA4);
        abbd abbdVarA5 = new abck().a();
        q = abbdVarA5;
        r = new abdb(AtomicIntegerArray.class, abbdVarA5);
        s = new abcl();
        abcm abcmVar = new abcm();
        t = abcmVar;
        u = new abdd(Character.TYPE, Character.class, abcmVar);
        abcn abcnVar = new abcn();
        v = abcnVar;
        w = new abco();
        x = new abcp();
        y = new abcq();
        z = new abdb(String.class, abcnVar);
        abcr abcrVar = new abcr();
        A = abcrVar;
        B = new abdb(StringBuilder.class, abcrVar);
        abct abctVar = new abct();
        C = abctVar;
        D = new abdb(StringBuffer.class, abctVar);
        abcu abcuVar = new abcu();
        E = abcuVar;
        F = new abdb(URL.class, abcuVar);
        abcv abcvVar = new abcv();
        G = abcvVar;
        H = new abdb(URI.class, abcvVar);
        abcw abcwVar = new abcw();
        I = abcwVar;
        J = new abdf(InetAddress.class, abcwVar);
        abcx abcxVar = new abcx();
        K = abcxVar;
        L = new abdb(UUID.class, abcxVar);
        abbd abbdVarA6 = new abcy().a();
        M = abbdVarA6;
        N = new abdb(Currency.class, abbdVarA6);
        abcz abczVar = new abcz();
        O = abczVar;
        P = new abde(Calendar.class, GregorianCalendar.class, abczVar);
        abda abdaVar = new abda();
        Q = abdaVar;
        R = new abdb(Locale.class, abdaVar);
        abcd abcdVar = abcd.a;
        S = abcdVar;
        T = new abdf(abar.class, abcdVar);
        U = abcb.a;
    }
}
