package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class adlf implements aasp {
    public static final qpi a = new qpi("speech.s3.S3StubbyClientConnectorService.");
    public static final qpi b = new qpi("speech.s3.S3StubbyClientConnectorService/");
    public static final aaso c = new adlc();
    public static final aaso d = new adld();
    public static final aaso e = new adle();
    public static final adlf f = new adlf();
    public static final qpi g = new qpi("ug-assistant-speechs3proto2-pa.sandbox.googleapis.com");
    public final yyk h;
    public final yyr i;

    private adlf() {
        int i = yyk.e;
        yyf yyfVar = new yyf(4);
        yyfVar.g("bh-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("cb-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ce-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("cf-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("dj-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ej-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("el-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("gc-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("je-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("lr-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("lu-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ok-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("oz-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("px-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("rg-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("sf-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("si-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("sl-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("sm-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("tm-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("tp-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ue-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("wd-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("yo-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ug-assistant-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("daily-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("staging-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("super-staging-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("staging-assistant-s3-pa.sandbox.googleapis.com");
        yyfVar.g("phil-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test324-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test478-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test189-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test389-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test393-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test67-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test304-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("khromov-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test136-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test143-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test388-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("parrotron-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("thacht-s3-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test215-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test99-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test203-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test218-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test381-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test10-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test424-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test36-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test80-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test145-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("universal-sd-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("id-smartedit-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ikowalski-pod-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ckcz-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test84-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("mnuhn-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("jiangboy-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test25-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("smart-dictation-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("yf-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("jfmortensen-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("jainmahaveer-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-test81-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("gwstest-s3-able-pri-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("gwstest-s3-baker-pri-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("gwstest-s3-charlie-pri-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("gwstest-s3-dog-pri-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("hanchenj-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("yingyinz-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("seno-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("lukechen-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("translate-fishfood-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("jcol-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("dysarthric-fishfood-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("kannumehta-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("vimitha-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("tttaoyu-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("phil-pod-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("yf-pod-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("autopush-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("autopush-assistant-s3-pa.sandbox.googleapis.com");
        yyfVar.g("assistant-server-dev-pa.sandbox.googleapis.com");
        yyfVar.g("damndaniel-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("pewu-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("thacht-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("zilongh-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("bkutzman-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("alikidwai-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("asfe-shared-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("mkleiner-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("vstashuk-dev-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("bruan-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("eh-asfe-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("saratan-autopush-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("bh-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("cb-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ce-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("cf-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("dj-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ej-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("el-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("gc-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("je-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("lr-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("lu-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ok-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("oz-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("px-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("rg-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("sf-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("si-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("sl-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("sm-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("tm-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("tp-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ue-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("wd-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("yo-speechs3proto2-pa.sandbox.googleapis.com");
        yyfVar.g("ug-assistant-speechs3proto2-pa.sandbox.googleapis.com");
        this.h = yyfVar.f();
        new yzo().f();
        aaso aasoVar = c;
        aaso aasoVar2 = d;
        aaso aasoVar3 = e;
        yzq.r(aasoVar, aasoVar2, aasoVar3);
        yyn yynVar = new yyn(4);
        yynVar.c("RunBlocking", aasoVar);
        yynVar.c("S3Bidi", aasoVar2);
        yynVar.c("RunBidi", aasoVar3);
        this.i = yynVar.a(true);
        new yyn(4).a(true);
    }
}
