package defpackage;

import com.google.android.katniss.R;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class atk {
    public static final int[] a = {R.attr.guidanceBreadcrumbStyle, R.attr.guidanceContainerStyle, R.attr.guidanceDescriptionStyle, R.attr.guidanceEntryAnimation, R.attr.guidanceIconStyle, R.attr.guidanceTitleStyle, R.attr.guidedActionCheckedAnimation, R.attr.guidedActionContentWidth, R.attr.guidedActionContentWidthNoIcon, R.attr.guidedActionContentWidthWeight, R.attr.guidedActionContentWidthWeightTwoPanels, R.attr.guidedActionDescriptionMinLines, R.attr.guidedActionDisabledChevronAlpha, R.attr.guidedActionEnabledChevronAlpha, R.attr.guidedActionItemCheckmarkStyle, R.attr.guidedActionItemChevronStyle, R.attr.guidedActionItemContainerStyle, R.attr.guidedActionItemContentStyle, R.attr.guidedActionItemDescriptionStyle, R.attr.guidedActionItemIconStyle, R.attr.guidedActionItemTitleStyle, R.attr.guidedActionPressedAnimation, R.attr.guidedActionTitleMaxLines, R.attr.guidedActionTitleMinLines, R.attr.guidedActionUncheckedAnimation, R.attr.guidedActionUnpressedAnimation, R.attr.guidedActionVerticalPadding, R.attr.guidedActionsBackground, R.attr.guidedActionsBackgroundDark, R.attr.guidedActionsContainerStyle, R.attr.guidedActionsElevation, R.attr.guidedActionsEntryAnimation, R.attr.guidedActionsListStyle, R.attr.guidedActionsSelectorDrawable, R.attr.guidedActionsSelectorHideAnimation, R.attr.guidedActionsSelectorShowAnimation, R.attr.guidedActionsSelectorStyle, R.attr.guidedActionsShadowWidth, R.attr.guidedButtonActionsListStyle, R.attr.guidedButtonActionsWidthWeight, R.attr.guidedStepBackground, R.attr.guidedStepEntryAnimation, R.attr.guidedStepExitAnimation, R.attr.guidedStepHeightWeight, R.attr.guidedStepImeAppearingAnimation, R.attr.guidedStepImeDisappearingAnimation, R.attr.guidedStepKeyline, R.attr.guidedStepReentryAnimation, R.attr.guidedStepReturnAnimation, R.attr.guidedStepTheme, R.attr.guidedStepThemeFlag, R.attr.guidedSubActionsListStyle};
    public static final int[] b = {R.attr.baseCardViewStyle, R.attr.browsePaddingBottom, R.attr.browsePaddingEnd, R.attr.browsePaddingStart, R.attr.browsePaddingTop, R.attr.browseRowsFadingEdgeLength, R.attr.browseRowsMarginStart, R.attr.browseRowsMarginTop, R.attr.browseTitleIconStyle, R.attr.browseTitleTextStyle, R.attr.browseTitleViewLayout, R.attr.browseTitleViewStyle, R.attr.datePickerStyle, R.attr.defaultBrandColor, R.attr.defaultBrandColorDark, R.attr.defaultSearchBrightColor, R.attr.defaultSearchColor, R.attr.defaultSearchIcon, R.attr.defaultSearchIconColor, R.attr.defaultSectionHeaderColor, R.attr.detailsActionButtonStyle, R.attr.detailsDescriptionBodyStyle, R.attr.detailsDescriptionSubtitleStyle, R.attr.detailsDescriptionTitleStyle, R.attr.errorMessageStyle, R.attr.headerStyle, R.attr.headersVerticalGridStyle, R.attr.imageCardViewBadgeStyle, R.attr.imageCardViewContentStyle, R.attr.imageCardViewImageStyle, R.attr.imageCardViewInfoAreaStyle, R.attr.imageCardViewStyle, R.attr.imageCardViewTitleStyle, R.attr.itemsVerticalGridStyle, R.attr.overlayDimActiveLevel, R.attr.overlayDimDimmedLevel, R.attr.overlayDimMaskColor, R.attr.pickerStyle, R.attr.pinPickerStyle, R.attr.playbackControlButtonLabelStyle, R.attr.playbackControlsActionIcons, R.attr.playbackControlsAutoHideTickleTimeout, R.attr.playbackControlsAutoHideTimeout, R.attr.playbackControlsButtonStyle, R.attr.playbackControlsIconHighlightColor, R.attr.playbackControlsTimeStyle, R.attr.playbackMediaItemDetailsStyle, R.attr.playbackMediaItemDurationStyle, R.attr.playbackMediaItemNameStyle, R.attr.playbackMediaItemNumberStyle, R.attr.playbackMediaItemNumberViewFlipperLayout, R.attr.playbackMediaItemNumberViewFlipperStyle, R.attr.playbackMediaItemPaddingStart, R.attr.playbackMediaItemRowStyle, R.attr.playbackMediaItemSeparatorStyle, R.attr.playbackMediaListHeaderStyle, R.attr.playbackMediaListHeaderTitleStyle, R.attr.playbackPaddingEnd, R.attr.playbackPaddingStart, R.attr.playbackProgressPrimaryColor, R.attr.playbackProgressSecondaryColor, R.attr.rowHeaderDescriptionStyle, R.attr.rowHeaderDockStyle, R.attr.rowHeaderStyle, R.attr.rowHorizontalGridStyle, R.attr.rowHoverCardDescriptionStyle, R.attr.rowHoverCardTitleStyle, R.attr.rowsVerticalGridStyle, R.attr.searchOrbViewStyle, R.attr.sectionHeaderStyle, R.attr.timePickerStyle};
    public static final int[] c = {R.attr.arrowBgColor, R.attr.arrowColor, R.attr.arrowRadius, R.attr.dotBgColor, R.attr.dotToArrowGap, R.attr.dotToDotGap, R.attr.lbDotRadius};
    public static final int[] d = {R.attr.activatedAnimationDuration, R.attr.cardBackground, R.attr.cardForeground, R.attr.cardType, R.attr.extraVisibility, R.attr.infoVisibility, R.attr.selectedAnimationDelay, R.attr.selectedAnimationDuration};
    public static final int[] e = {R.attr.layout_viewType};
    public static final int[] f = {android.R.attr.minDate, android.R.attr.maxDate, R.attr.datePickerFormat, R.attr.pickerItemLayout, R.attr.pickerItemTextViewId};
    public static final int[] g = {R.attr.pickerItemLayout, R.attr.pickerItemTextViewId};
    public static final int[] h = {R.attr.maintainLineSpacing, R.attr.resizeTrigger, R.attr.resizedPaddingAdjustmentBottom, R.attr.resizedPaddingAdjustmentTop, R.attr.resizedTextSize};
    public static final int[] i = {R.attr.searchOrbBrightColor, R.attr.searchOrbColor, R.attr.searchOrbIcon, R.attr.searchOrbIconColor};
    public static final int[] j = {android.R.attr.interpolator, android.R.attr.duration, android.R.attr.startDelay, R.attr.lb_slideEdge};
}
