package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public class c {
    public int b;
    public int c;
    int d;
    public boolean a = false;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;

    public final void a(b bVar) {
        bVar.d = this.h;
        bVar.e = this.i;
        bVar.f = this.j;
        bVar.g = this.k;
        bVar.h = this.l;
        bVar.i = this.m;
        bVar.j = this.n;
        bVar.k = this.o;
        bVar.l = this.p;
        bVar.m = this.q;
        bVar.n = this.r;
        bVar.o = this.s;
        bVar.p = this.t;
        bVar.leftMargin = this.A;
        bVar.rightMargin = this.B;
        bVar.topMargin = this.C;
        bVar.bottomMargin = this.D;
        bVar.u = this.M;
        bVar.v = this.L;
        bVar.w = this.u;
        bVar.x = this.v;
        bVar.y = this.w;
        bVar.K = this.x;
        bVar.L = this.y;
        bVar.B = this.N;
        bVar.A = this.O;
        bVar.D = this.Q;
        bVar.C = this.P;
        bVar.E = this.ad;
        bVar.F = this.ae;
        bVar.I = this.af;
        bVar.J = this.ag;
        bVar.G = this.ah;
        bVar.H = this.ai;
        bVar.M = this.z;
        bVar.c = this.g;
        bVar.a = this.e;
        bVar.b = this.f;
        bVar.width = this.b;
        bVar.height = this.c;
        bVar.setMarginStart(this.F);
        bVar.setMarginEnd(this.E);
        bVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        c cVar = new c();
        cVar.a = this.a;
        cVar.b = this.b;
        cVar.c = this.c;
        cVar.e = this.e;
        cVar.f = this.f;
        cVar.g = this.g;
        cVar.h = this.h;
        cVar.i = this.i;
        cVar.j = this.j;
        cVar.k = this.k;
        cVar.l = this.l;
        cVar.m = this.m;
        cVar.n = this.n;
        cVar.o = this.o;
        cVar.p = this.p;
        cVar.q = this.q;
        cVar.r = this.r;
        cVar.s = this.s;
        cVar.t = this.t;
        cVar.u = this.u;
        cVar.v = this.v;
        cVar.w = this.w;
        cVar.x = this.x;
        cVar.y = this.y;
        cVar.u = this.u;
        cVar.u = this.u;
        cVar.u = this.u;
        cVar.u = this.u;
        cVar.u = this.u;
        cVar.z = this.z;
        cVar.A = this.A;
        cVar.B = this.B;
        cVar.C = this.C;
        cVar.D = this.D;
        cVar.E = this.E;
        cVar.F = this.F;
        cVar.G = this.G;
        cVar.H = this.H;
        cVar.I = this.I;
        cVar.J = this.J;
        cVar.K = this.K;
        cVar.L = this.L;
        cVar.M = this.M;
        cVar.N = this.N;
        cVar.O = this.O;
        cVar.P = this.P;
        cVar.Q = this.Q;
        cVar.R = this.R;
        cVar.S = this.S;
        cVar.T = this.T;
        cVar.U = this.U;
        cVar.V = this.V;
        cVar.W = this.W;
        cVar.X = this.X;
        cVar.Y = this.Y;
        cVar.Z = this.Z;
        cVar.aa = this.aa;
        cVar.ab = this.ab;
        cVar.ac = this.ac;
        cVar.ad = this.ad;
        cVar.ae = this.ae;
        cVar.af = this.af;
        cVar.ag = this.ag;
        cVar.ah = this.ah;
        cVar.ai = this.ai;
        return cVar;
    }
}
