package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public class dyv {
    final int a;
    public final String b;
    public final String c;
    public final int d;

    public dyv(int i, String str, String str2) {
        this.a = i;
        this.b = str;
        this.c = str2;
        this.d = (str.hashCode() * 961) + ((str2 == null ? 0 : str2.hashCode()) * 31) + i;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj != null && getClass() == obj.getClass()) {
            dyv dyvVar = (dyv) obj;
            if (this.a == dyvVar.a) {
                String str = this.b;
                String str2 = dyvVar.b;
                if (str != str2 && !str.equals(str2)) {
                    return false;
                }
                String str3 = this.c;
                String str4 = dyvVar.c;
                if (str3 != str4) {
                    return str3 != null && str3.equals(str4);
                }
                return true;
            }
        }
        return false;
    }

    public final int hashCode() {
        return this.d;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("TransitionId{\"");
        sb.append(this.b);
        sb.append("\", ");
        int i = this.a;
        if (i == 1) {
            sb.append("GLOBAL");
        } else if (i != 2) {
            sb.append("AUTOGENERATED");
        } else {
            sb.append("SCOPED(");
            sb.append(this.c);
            sb.append(")");
        }
        sb.append("}");
        return sb.toString();
    }
}
