package defpackage;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: PG */
/* loaded from: classes.dex */
public final class gmc {
    public static final gmc A;
    public static final gmc B;
    public static final gmc C;
    public static final gmc D;
    public static final gmc E;
    public static final gmc F;
    public static final gmc G;
    public static final gmc H;
    public static final gmc I;
    public static final gmc J;
    public static final gmc K;
    public static final gmc L;
    public static final gmc M;
    public static final gmc N;
    public static final gmc O;
    public static final gmc P;
    public static final gmc Q;
    public static final gmc R;
    public static final gmc S;
    public static final gmc T;
    public static final gmc U;
    public static final gmc V;
    public static final gmc W;
    public static final gmc X;
    public static final gmc Y;
    public static final gmc Z;
    public static final gmc a;
    public static final gmc aA;
    public static final gmc aB;
    public static final gmc aC;
    private static final /* synthetic */ gmc[] aE;
    public static final gmc aa;
    public static final gmc ab;
    public static final gmc ac;
    public static final gmc ad;
    public static final gmc ae;
    public static final gmc af;
    public static final gmc ag;
    public static final gmc ah;
    public static final gmc ai;
    public static final gmc aj;
    public static final gmc ak;
    public static final gmc al;
    public static final gmc am;
    public static final gmc an;
    public static final gmc ao;
    public static final gmc ap;
    public static final gmc aq;
    public static final gmc ar;
    public static final gmc as;
    public static final gmc at;
    public static final gmc au;
    public static final gmc av;
    public static final gmc aw;
    public static final gmc ax;
    public static final gmc ay;
    public static final gmc az;
    public static final gmc b;
    public static final gmc c;
    public static final gmc d;
    public static final gmc e;
    public static final gmc f;
    public static final gmc g;
    public static final gmc h;
    public static final gmc i;
    public static final gmc j;
    public static final gmc k;
    public static final gmc l;
    public static final gmc m;
    public static final gmc n;
    public static final gmc o;
    public static final gmc p;
    public static final gmc q;
    public static final gmc r;
    public static final gmc s;
    public static final gmc t;
    public static final gmc u;
    public static final gmc v;
    public static final gmc w;
    public static final gmc x;
    public static final gmc y;
    public static final gmc z;
    public final qpi aD;

    static {
        gmc gmcVar = new gmc("APP_START_TO_MIC_OPEN", 0, "app_start_to_mic_open");
        a = gmcVar;
        gmc gmcVar2 = new gmc("ASSISTANT_REQUEST_HOTWORD_TO_LISTENING", 1, "assistant_request_hotword_to_listening");
        b = gmcVar2;
        gmc gmcVar3 = new gmc("ASSISTANT_REQUEST_INTENT_TO_LISTENING", 2, "assistant_request_intent_to_listening");
        c = gmcVar3;
        gmc gmcVar4 = new gmc("ASSISTANT_REQUEST_INTENT_TO_LISTENING_FIRST_QUERY", 3, "new_assistant_request_intent_to_listening_first_query");
        d = gmcVar4;
        gmc gmcVar5 = new gmc("QUERY_DURATION", 4, "query_duration");
        e = gmcVar5;
        gmc gmcVar6 = new gmc("QUERY_RECOGNIZED_TO_RESULT", 5, "query_recognized_to_result");
        f = gmcVar6;
        gmc gmcVar7 = new gmc("QUERY_RECOGNIZED_TO_TTS_START", 6, "query_recognized_to_tts_start");
        g = gmcVar7;
        gmc gmcVar8 = new gmc("START_RECORDING_TO_FIRST_RECOGNIZED", 7, "start_recording_to_first_recognized");
        h = gmcVar8;
        gmc gmcVar9 = new gmc("START_RECORDING_TO_FIRST_UI_UPDATE", 8, "start_recording_to_first_ui_update");
        i = gmcVar9;
        gmc gmcVar10 = new gmc("IN_APP_INTERACTION_EXECUTION", 9, "in_app_interaction_execution");
        j = gmcVar10;
        gmc gmcVar11 = new gmc("HOMEGRAPH_SETUP_E2E_LATENCY", 10, "homehraph_setup_e2e_latency");
        k = gmcVar11;
        gmc gmcVar12 = new gmc("SCREEN_LOAD_TIME_EVENT", 11, "screen_load_time_event");
        l = gmcVar12;
        gmc gmcVar13 = new gmc("OPERATOR_API_CONNECTION_ESTABLISHED", 12, "operator_api_connection_established");
        m = gmcVar13;
        gmc gmcVar14 = new gmc("OPERATOR_API_DATA_RETRIEVED", 13, "operator_api_data_retrieved");
        n = gmcVar14;
        gmc gmcVar15 = new gmc("OPERATOR_API_DATA_SENT", 14, "operator_api_data_sent");
        o = gmcVar15;
        gmc gmcVar16 = new gmc("OPERATOR_API_E2E_LATENCY", 15, "operator_api_e2e_latency");
        p = gmcVar16;
        gmc gmcVar17 = new gmc("PERFORMER_DEVICE_LINK_TOKEN", 16, "performer_device_link_token");
        q = gmcVar17;
        gmc gmcVar18 = new gmc("PERFORMER_DEVICE_POWER", 17, "performer_device_power");
        r = gmcVar18;
        gmc gmcVar19 = new gmc("PERFORMER_DEVICE_VOLUME", 18, "performer_device_volume");
        s = gmcVar19;
        gmc gmcVar20 = new gmc("PERFORMER_MEDIA", 19, "performer_media");
        t = gmcVar20;
        gmc gmcVar21 = new gmc("PERFORMER_OPEN", 20, "performer_open");
        u = gmcVar21;
        gmc gmcVar22 = new gmc("PERFORMER_PLAY_MEDIA", 21, "performer_play_media");
        v = gmcVar22;
        gmc gmcVar23 = new gmc("PERFORMER_UPLOAD_CRASH_REPORT", 22, "performer_upload_crash_report");
        w = gmcVar23;
        gmc gmcVar24 = new gmc("RESULT_FULFILLED_MEDIA_CONTROL", 23, "result_fulfilled_media_control");
        x = gmcVar24;
        gmc gmcVar25 = new gmc("RESULT_FULFILLED_PROVIDER_OPEN", 24, "result_fulfilled_provider_open");
        y = gmcVar25;
        gmc gmcVar26 = new gmc("AMATI_ENTITY_PAGE_KATNISS", 25, "amati_entity_page_katniss");
        z = gmcVar26;
        gmc gmcVar27 = new gmc("DRAW_XUIKIT_CARD", 26, "draw_xuikit_card");
        A = gmcVar27;
        gmc gmcVar28 = new gmc("REFINEMENT_CLICKED_LOADING_DURATION", 27, "refinement_clicked_loading_duration");
        B = gmcVar28;
        gmc gmcVar29 = new gmc("RESULT_ACROSS_PROCESS", 28, "result_across_process");
        C = gmcVar29;
        gmc gmcVar30 = new gmc("RESULT_DISPLAYED", 29, "result_displayed");
        D = gmcVar30;
        gmc gmcVar31 = new gmc("RESULT_DISPLAYED_CARD", 30, "result_displayed_card");
        E = gmcVar31;
        gmc gmcVar32 = new gmc("RESULT_DISPLAYED_CARD_XUIKIT", 31, "result_displayed_card_xuikit");
        F = gmcVar32;
        gmc gmcVar33 = new gmc("RESULT_DISPLAYED_SPOCK", 32, "result_displayed_spock");
        G = gmcVar33;
        gmc gmcVar34 = new gmc("RESULT_DISPLAYED_SPOCK_CAROUSEL", 33, "result_displayed_spock_carousel");
        H = gmcVar34;
        gmc gmcVar35 = new gmc("RESULT_DISPLAYED_SPOCK_ENTITY", 34, "result_displayed_spock_entity");
        I = gmcVar35;
        gmc gmcVar36 = new gmc("RESULT_DISPLAYED_TEXT", 35, "result_displayed_text");
        J = gmcVar36;
        gmc gmcVar37 = new gmc("VIEW_ADD_CARD", 36, "view_add_card");
        K = gmcVar37;
        gmc gmcVar38 = new gmc("VIEW_ADD_SPOCK", 37, "view_add_spock");
        L = gmcVar38;
        gmc gmcVar39 = new gmc("VIEW_ADD_SPOCK_CAROUSEL", 38, "view_add_spock_carousel");
        M = gmcVar39;
        gmc gmcVar40 = new gmc("VIEW_ADD_SPOCK_ENTITY", 39, "view_add_spock_entity");
        N = gmcVar40;
        gmc gmcVar41 = new gmc("VIEW_ADD_TEXT", 40, "view_add_text");
        O = gmcVar41;
        gmc gmcVar42 = new gmc("WATSON_ENTITY_PAGE_KATNISS", 41, "watson_entity_page_katniss");
        P = gmcVar42;
        gmc gmcVar43 = new gmc("WEBVIEW_CONTENT_LOADING", 42, "webview_content_loading");
        Q = gmcVar43;
        gmc gmcVar44 = new gmc("SEARCH_TAB_OPEN", 43, "search_tab_open");
        R = gmcVar44;
        gmc gmcVar45 = new gmc("SUGGESTED_QUERIES_DISMISS", 44, "suggested_queries_dismiss");
        S = gmcVar45;
        gmc gmcVar46 = new gmc("SUGGESTED_QUERIES_FETCH_SUGGESTIONS_FROM_SERVER", 45, "suggested_queries_fetch_suggestions_from_server");
        T = gmcVar46;
        gmc gmcVar47 = new gmc("SUGGESTED_QUERIES_LOAD_SUGGESTIONS", 46, "suggested_queries_load_suggestions");
        U = gmcVar47;
        gmc gmcVar48 = new gmc("FETCH_ZEROSTATE_SUGGESTIONS_FROM_SERVER", 47, "fetch_zerostate_suggestions_from_server");
        V = gmcVar48;
        gmc gmcVar49 = new gmc("FETCH_CACHED_OR_DEFAULT_ZEROSTATE_SUGGESTIONS", 48, "fetch_cached_or_default_zerostate_suggestions");
        W = gmcVar49;
        gmc gmcVar50 = new gmc("APP_START_TO_VPA_VISIBLE", 49, "app_start_to_vpa_visible");
        X = gmcVar50;
        gmc gmcVar51 = new gmc("ASSISTANT_REQUEST_HOTWORD_TO_UI", 50, "assistant_request_hotword_to_ui");
        Y = gmcVar51;
        gmc gmcVar52 = new gmc("ASSISTANT_REQUEST_HOTWORD_TO_UI_COLD_SEARCH", 51, "assistant_request_hotword_to_ui_cold_search");
        Z = gmcVar52;
        gmc gmcVar53 = new gmc("ASSISTANT_REQUEST_INTENT_TO_UI", 52, "assistant_request_intent_to_ui");
        aa = gmcVar53;
        gmc gmcVar54 = new gmc("ASSISTANT_REQUEST_INTENT_TO_UI_COLD_SEARCH", 53, "assistant_request_intent_to_ui_cold_search");
        ab = gmcVar54;
        gmc gmcVar55 = new gmc("IMMERSIVE_SEARCH_START", 54, "immersive_search_start");
        ac = gmcVar55;
        gmc gmcVar56 = new gmc("IMMERSIVE_SEARCH_START_INTERNAL", 55, "immersive_search_start_internal");
        ad = gmcVar56;
        gmc gmcVar57 = new gmc("KEYBOARD_SEARCH_SUGGESTIONS", 56, "keyboard_search_suggestions");
        ae = gmcVar57;
        gmc gmcVar58 = new gmc("SEARCHBAR_STATE_IDLE", 57, "searchbar_state_idle");
        af = gmcVar58;
        gmc gmcVar59 = new gmc("SEARCHBAR_STATE_IDLE_WITHOUT_SUGGESTIONS", 58, "searchbar_state_idle_without_suggestions");
        ag = gmcVar59;
        gmc gmcVar60 = new gmc("SEARCHBAR_STATE_INTRODUCTION", 59, "searchbar_state_introduction");
        ah = gmcVar60;
        gmc gmcVar61 = new gmc("SEARCHBAR_STATE_KEYBOARD", 60, "searchbar_state_keyboard");
        ai = gmcVar61;
        gmc gmcVar62 = new gmc("SEARCHBAR_STATE_LISTENING", 61, "searchbar_state_listening");
        aj = gmcVar62;
        gmc gmcVar63 = new gmc("SEARCHBAR_STATE_LISTENING_FALLBACK", 62, "searchbar_state_listening_fallback");
        ak = gmcVar63;
        gmc gmcVar64 = new gmc("SEARCHBAR_STATE_LOADING", 63, "searchbar_state_loading");
        al = gmcVar64;
        gmc gmcVar65 = new gmc("SEARCHBAR_STATE_PRE_START", 64, "searchbar_state_pre_start");
        am = gmcVar65;
        gmc gmcVar66 = new gmc("SEARCHBAR_STATE_RESPONSE", 65, "searchbar_state_response");
        an = gmcVar66;
        gmc gmcVar67 = new gmc("SEARCHBAR_STATE_SPEAKING", 66, "searchbar_state_speaking");
        ao = gmcVar67;
        gmc gmcVar68 = new gmc("SEARCHBAR_STATE_SPEAKING_FALLBACK", 67, "searchbar_state_speaking_fallback");
        ap = gmcVar68;
        gmc gmcVar69 = new gmc("SEARCHBAR_STATE_TALKING", 68, "searchbar_state_talking");
        aq = gmcVar69;
        gmc gmcVar70 = new gmc("SEARCHBAR_STATE_TALKING_IDLE", 69, "searchbar_state_talking_idle");
        ar = gmcVar70;
        gmc gmcVar71 = new gmc("SEARCHBAR_STATE_TALKING_RESPONSE", 70, "searchbar_state_talking_response");
        as = gmcVar71;
        gmc gmcVar72 = new gmc("SEARCHBAR_STATE_TRANSCRIBING", 71, "searchbar_state_transcribing");
        at = gmcVar72;
        gmc gmcVar73 = new gmc("SEARCHBAR_STATE_UPDATE", 72, "searchbar_state_update");
        au = gmcVar73;
        gmc gmcVar74 = new gmc("START_QUERY_HOTWORD_UI", 73, "start_query_hotword_ui");
        av = gmcVar74;
        gmc gmcVar75 = new gmc("START_QUERY_INTENT_UI", 74, "start_query_intent_ui");
        aw = gmcVar75;
        gmc gmcVar76 = new gmc("VOICE_PLATE_ENTRANCE_ANIMATION", 75, "voice_plate_entrance_animation");
        ax = gmcVar76;
        gmc gmcVar77 = new gmc("TEST_EVENT", 76, "test_event");
        ay = gmcVar77;
        gmc gmcVar78 = new gmc("ASSISTANT_REQUEST_INTENT_TO_LISTENING_GIA_CHAT", 77, "assistant_request_intent_to_listening_gia_chat");
        az = gmcVar78;
        gmc gmcVar79 = new gmc("ASSISTANT_REQUEST_HOTWORD_TO_UI_GIA_CHAT", 78, "assistant_request_hotword_to_ui_gia_chat");
        aA = gmcVar79;
        gmc gmcVar80 = new gmc("ASSISTANT_REQUEST_INTENT_TO_UI_GIA_CHAT", 79, "assistant_request_intent_to_ui_gia_chat");
        aB = gmcVar80;
        gmc gmcVar81 = new gmc("VOICE_PLATE_ENTRANCE_ANIMATION_GIA_CHAT", 80, "voice_plate_entrance_animation_gia_chat");
        aC = gmcVar81;
        gmc[] gmcVarArr = {gmcVar, gmcVar2, gmcVar3, gmcVar4, gmcVar5, gmcVar6, gmcVar7, gmcVar8, gmcVar9, gmcVar10, gmcVar11, gmcVar12, gmcVar13, gmcVar14, gmcVar15, gmcVar16, gmcVar17, gmcVar18, gmcVar19, gmcVar20, gmcVar21, gmcVar22, gmcVar23, gmcVar24, gmcVar25, gmcVar26, gmcVar27, gmcVar28, gmcVar29, gmcVar30, gmcVar31, gmcVar32, gmcVar33, gmcVar34, gmcVar35, gmcVar36, gmcVar37, gmcVar38, gmcVar39, gmcVar40, gmcVar41, gmcVar42, gmcVar43, gmcVar44, gmcVar45, gmcVar46, gmcVar47, gmcVar48, gmcVar49, gmcVar50, gmcVar51, gmcVar52, gmcVar53, gmcVar54, gmcVar55, gmcVar56, gmcVar57, gmcVar58, gmcVar59, gmcVar60, gmcVar61, gmcVar62, gmcVar63, gmcVar64, gmcVar65, gmcVar66, gmcVar67, gmcVar68, gmcVar69, gmcVar70, gmcVar71, gmcVar72, gmcVar73, gmcVar74, gmcVar75, gmcVar76, gmcVar77, gmcVar78, gmcVar79, gmcVar80, gmcVar81};
        aE = gmcVarArr;
        agtw.a(gmcVarArr);
    }

    private gmc(String str, int i2, String str2) {
        this.aD = new qpi(str2);
    }

    public static gmc a(String str) {
        return (gmc) Enum.valueOf(gmc.class, str);
    }

    public static gmc[] values() {
        return (gmc[]) aE.clone();
    }
}
