package defpackage;

import java.util.LinkedHashMap;
import java.util.Map;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: PG */
/* loaded from: classes.dex */
public final class ouq {
    public static final ouq A;
    public static final ouq B;
    public static final ouq C;
    public static final ouq D;
    public static final ouq E;
    public static final ouq F;
    public static final ouq G;
    public static final ouq H;
    public static final ouq I;
    public static final ouq J;
    public static final ouq K;
    public static final ouq L;
    public static final ouq M;
    public static final ouq N;
    public static final ouq O;
    public static final ouq P;
    public static final ouq Q;
    public static final ouq R;
    public static final ouq S;
    public static final ouq T;
    public static final ouq U;
    public static final ouq V;
    public static final ouq W;
    public static final ouq X;
    public static final ouq Y;
    public static final ouq Z;
    public static final Map a;
    public static final ouq aA;
    public static final ouq aB;
    public static final ouq aC;
    public static final ouq aD;
    public static final ouq aE;
    public static final ouq aF;
    public static final ouq aG;
    public static final ouq aH;
    public static final ouq aI;
    public static final ouq aJ;
    public static final ouq aK;
    public static final ouq aL;
    public static final ouq aM;
    public static final ouq aN;
    public static final ouq aO;
    public static final ouq aP;
    public static final ouq aQ;
    public static final ouq aR;
    public static final ouq aS;
    public static final ouq aT;
    public static final ouq aU;
    public static final ouq aV;
    public static final ouq aW;
    public static final ouq aX;
    public static final ouq aY;
    public static final ouq aZ;
    public static final ouq aa;
    public static final ouq ab;
    public static final ouq ac;
    public static final ouq ad;
    public static final ouq ae;
    public static final ouq af;
    public static final ouq ag;
    public static final ouq ah;
    public static final ouq ai;
    public static final ouq aj;
    public static final ouq ak;
    public static final ouq al;
    public static final ouq am;
    public static final ouq an;
    public static final ouq ao;
    public static final ouq ap;
    public static final ouq aq;
    public static final ouq ar;
    public static final ouq as;
    public static final ouq at;
    public static final ouq au;
    public static final ouq av;
    public static final ouq aw;
    public static final ouq ax;
    public static final ouq ay;
    public static final ouq az;
    public static final ouq b;
    public static final ouq bA;
    public static final ouq bB;
    public static final ouq bC;
    public static final ouq bD;
    public static final ouq bE;
    private static final /* synthetic */ ouq[] bF;
    private static final /* synthetic */ agtv bG;
    public static final ouq ba;
    public static final ouq bb;
    public static final ouq bc;
    public static final ouq bd;
    public static final ouq be;
    public static final ouq bf;
    public static final ouq bg;
    public static final ouq bh;
    public static final ouq bi;
    public static final ouq bj;
    public static final ouq bk;
    public static final ouq bl;
    public static final ouq bm;
    public static final ouq bn;
    public static final ouq bo;
    public static final ouq bp;
    public static final ouq bq;
    public static final ouq br;
    public static final ouq bs;
    public static final ouq bt;
    public static final ouq bu;
    public static final ouq bv;
    public static final ouq bw;
    public static final ouq bx;
    public static final ouq by;
    public static final ouq bz;
    public static final ouq c;
    public static final ouq d;
    public static final ouq e;
    public static final ouq f;
    public static final ouq g;
    public static final ouq h;
    public static final ouq i;
    public static final ouq j;
    public static final ouq k;
    public static final ouq l;
    public static final ouq m;
    public static final ouq n;
    public static final ouq o;
    public static final ouq p;
    public static final ouq q;
    public static final ouq r;
    public static final ouq s;
    public static final ouq t;
    public static final ouq u;
    public static final ouq v;
    public static final ouq w;
    public static final ouq x;
    public static final ouq y;
    public static final ouq z;
    private final String bH;

    /* JADX WARN: Multi-variable type inference failed */
    static {
        ouq ouqVar = new ouq("UNKNOWN", 0, "");
        b = ouqVar;
        ouq ouqVar2 = new ouq("AC_HEATING", 1, "action.devices.types.AC_HEATING");
        c = ouqVar2;
        ouq ouqVar3 = new ouq("AC_UNIT", 2, "action.devices.types.AC_UNIT");
        d = ouqVar3;
        ouq ouqVar4 = new ouq("AVR", 3, "action.devices.types.AUDIO_VIDEO_RECEIVER");
        e = ouqVar4;
        ouq ouqVar5 = new ouq("BORDER_ROUTER", 4, "action.devices.types.BORDER_ROUTER");
        f = ouqVar5;
        ouq ouqVar6 = new ouq("CAMERA", 5, "action.devices.types.CAMERA");
        g = ouqVar6;
        ouq ouqVar7 = new ouq("DEVICE_GROUP", 6, "action.devices.types.DEVICE_GROUP");
        h = ouqVar7;
        ouq ouqVar8 = new ouq("DISHWASHER", 7, "action.devices.types.DISHWASHER");
        i = ouqVar8;
        ouq ouqVar9 = new ouq("DISPLAY", 8, "action.devices.types.DISPLAY");
        j = ouqVar9;
        ouq ouqVar10 = new ouq("DOORBELL", 9, "action.devices.types.DOORBELL");
        k = ouqVar10;
        ouq ouqVar11 = new ouq("DRYER", 10, "action.devices.types.DRYER");
        l = ouqVar11;
        ouq ouqVar12 = new ouq("GAME_CONSOLE", 11, "action.devices.types.GAME_CONSOLE");
        m = ouqVar12;
        ouq ouqVar13 = new ouq("GOOGLE_HOME", 12, "action.devices.types.GOOGLE_HOME");
        n = ouqVar13;
        ouq ouqVar14 = new ouq("LIGHT", 13, "action.devices.types.LIGHT");
        o = ouqVar14;
        ouq ouqVar15 = new ouq("LOCK", 14, "action.devices.types.LOCK");
        p = ouqVar15;
        ouq ouqVar16 = new ouq("NETWORK", 15, "action.devices.types.NETWORK");
        q = ouqVar16;
        ouq ouqVar17 = new ouq("OUTLET", 16, "action.devices.types.OUTLET");
        r = ouqVar17;
        ouq ouqVar18 = new ouq("REMOTE_CONTROL", 17, "action.devices.types.REMOTECONTROL");
        s = ouqVar18;
        ouq ouqVar19 = new ouq("SCENE", 18, "action.devices.types.SCENE");
        t = ouqVar19;
        ouq ouqVar20 = new ouq("SCREEN", 19, "action.devices.types.SCREEN");
        u = ouqVar20;
        ouq ouqVar21 = new ouq("SENSOR", 20, "action.devices.types.SENSOR");
        v = ouqVar21;
        ouq ouqVar22 = new ouq("SET_TOP", 21, "action.devices.types.SETTOP");
        w = ouqVar22;
        ouq ouqVar23 = new ouq("SPEAKER", 22, "action.devices.types.SPEAKER");
        x = ouqVar23;
        ouq ouqVar24 = new ouq("SPEAKER_GROUP", 23, "action.devices.types.SPEAKER_GROUP");
        y = ouqVar24;
        ouq ouqVar25 = new ouq("SPEAKER_PAIR", 24, "action.devices.types.SPEAKER_PAIR");
        z = ouqVar25;
        ouq ouqVar26 = new ouq("SWITCH", 25, "action.devices.types.SWITCH");
        A = ouqVar26;
        ouq ouqVar27 = new ouq("SYNCBOX", 26, "action.devices.types.SYNCBOX");
        B = ouqVar27;
        ouq ouqVar28 = new ouq("THERMOSTAT", 27, "action.devices.types.THERMOSTAT");
        C = ouqVar28;
        ouq ouqVar29 = new ouq("TV", 28, "action.devices.types.TV");
        D = ouqVar29;
        ouq ouqVar30 = new ouq("VACUUM", 29, "action.devices.types.VACUUM");
        E = ouqVar30;
        ouq ouqVar31 = new ouq("WASHER", 30, "action.devices.types.WASHER");
        F = ouqVar31;
        ouq ouqVar32 = new ouq("AIRCOOLER", 31, "action.devices.types.AIRCOOLER");
        G = ouqVar32;
        ouq ouqVar33 = new ouq("AIR_FRESHENER", 32, "action.devices.types.AIRFRESHENER");
        H = ouqVar33;
        ouq ouqVar34 = new ouq("AIR_PURIFIER", 33, "action.devices.types.AIRPURIFIER");
        I = ouqVar34;
        ouq ouqVar35 = new ouq("ALARM", 34, "action.devices.types.ALARM");
        J = ouqVar35;
        ouq ouqVar36 = new ouq("AUTO", 35, "action.devices.types.AUTO");
        K = ouqVar36;
        ouq ouqVar37 = new ouq("AWNING", 36, "action.devices.types.AWNING");
        L = ouqVar37;
        ouq ouqVar38 = new ouq("BAG", 37, "action.devices.types.BAG");
        M = ouqVar38;
        ouq ouqVar39 = new ouq("BATHTUB", 38, "action.devices.types.BATHTUB");
        N = ouqVar39;
        ouq ouqVar40 = new ouq("BATTERY", 39, "action.devices.types.BATTERY");
        O = ouqVar40;
        ouq ouqVar41 = new ouq("BED", 40, "action.devices.types.BED");
        P = ouqVar41;
        ouq ouqVar42 = new ouq("BIKE", 41, "action.devices.types.BIKE");
        Q = ouqVar42;
        ouq ouqVar43 = new ouq("BLANKET", 42, "action.devices.types.BLANKET");
        R = ouqVar43;
        ouq ouqVar44 = new ouq("BLENDER", 43, "action.devices.types.BLENDER");
        S = ouqVar44;
        ouq ouqVar45 = new ouq("BLINDS", 44, "action.devices.types.BLINDS");
        T = ouqVar45;
        ouq ouqVar46 = new ouq("BOILER", 45, "action.devices.types.BOILER");
        U = ouqVar46;
        ouq ouqVar47 = new ouq("CARBON_MONOXIDE_DETECTOR", 46, "action.devices.types.CARBON_MONOXIDE_DETECTOR");
        V = ouqVar47;
        ouq ouqVar48 = new ouq("CAT", 47, "action.devices.types.CAT");
        W = ouqVar48;
        ouq ouqVar49 = new ouq("CHARGER", 48, "action.devices.types.CHARGER");
        X = ouqVar49;
        ouq ouqVar50 = new ouq("CLOCK", 49, "action.devices.types.CLOCK");
        Y = ouqVar50;
        ouq ouqVar51 = new ouq("CLOCKRADIO", 50, "action.devices.types.CLOCKRADIO");
        Z = ouqVar51;
        ouq ouqVar52 = new ouq("CLOSET", 51, "action.devices.types.CLOSET");
        aa = ouqVar52;
        ouq ouqVar53 = new ouq("CLOTHING", 52, "action.devices.types.CLOTHING");
        ab = ouqVar53;
        ouq ouqVar54 = new ouq("COFFEE_MAKER", 53, "action.devices.types.COFFEE_MAKER");
        ac = ouqVar54;
        ouq ouqVar55 = new ouq("COMPUTER", 54, "action.devices.types.COMPUTER");
        ad = ouqVar55;
        ouq ouqVar56 = new ouq("COOKTOP", 55, "action.devices.types.COOKTOP");
        ae = ouqVar56;
        ouq ouqVar57 = new ouq("CURTAIN", 56, "action.devices.types.CURTAIN");
        af = ouqVar57;
        ouq ouqVar58 = new ouq("DEHUMIDIFIER", 57, "action.devices.types.DEHUMIDIFIER");
        ag = ouqVar58;
        ouq ouqVar59 = new ouq("DEHYDRATOR", 58, "action.devices.types.DEHYDRATOR");
        ah = ouqVar59;
        ouq ouqVar60 = new ouq("DOCK", 59, "action.devices.types.DOCK");
        ai = ouqVar60;
        ouq ouqVar61 = new ouq("DOG", 60, "action.devices.types.DOG");
        aj = ouqVar61;
        ouq ouqVar62 = new ouq("DOOR", 61, "action.devices.types.DOOR");
        ak = ouqVar62;
        ouq ouqVar63 = new ouq("DRAWER", 62, "action.devices.types.DRAWER");
        al = ouqVar63;
        ouq ouqVar64 = new ouq("ELEVATOR", 63, "action.devices.types.ELEVATOR");
        am = ouqVar64;
        ouq ouqVar65 = new ouq("FAN", 64, "action.devices.types.FAN");
        an = ouqVar65;
        ouq ouqVar66 = new ouq("FAUCET", 65, "action.devices.types.FAUCET");
        ao = ouqVar66;
        ouq ouqVar67 = new ouq("FILTER", 66, "action.devices.types.FILTER");
        ap = ouqVar67;
        ouq ouqVar68 = new ouq("FIREPLACE", 67, "action.devices.types.FIREPLACE");
        aq = ouqVar68;
        ouq ouqVar69 = new ouq("FREEZER", 68, "action.devices.types.FREEZER");
        ar = ouqVar69;
        ouq ouqVar70 = new ouq("FRYER", 69, "action.devices.types.FRYER");
        as = ouqVar70;
        ouq ouqVar71 = new ouq("GARAGE", 70, "action.devices.types.GARAGE");
        at = ouqVar71;
        ouq ouqVar72 = new ouq("GARDEN", 71, "action.devices.types.GARDEN");
        au = ouqVar72;
        ouq ouqVar73 = new ouq("GATE", 72, "action.devices.types.GATE");
        av = ouqVar73;
        ouq ouqVar74 = new ouq("GRILL", 73, "action.devices.types.GRILL");
        aw = ouqVar74;
        ouq ouqVar75 = new ouq("HEADPHONES", 74, "action.devices.types.HEADPHONES");
        ax = ouqVar75;
        ouq ouqVar76 = new ouq("HEATER", 75, "action.devices.types.HEATER");
        ay = ouqVar76;
        ouq ouqVar77 = new ouq("HOOD", 76, "action.devices.types.HOOD");
        az = ouqVar77;
        ouq ouqVar78 = new ouq("HUMIDIFIER", 77, "action.devices.types.HUMIDIFIER");
        aA = ouqVar78;
        ouq ouqVar79 = new ouq("IDBADGE", 78, "action.devices.types.IDBADGE");
        aB = ouqVar79;
        ouq ouqVar80 = new ouq("INTERCOM", 79, "action.devices.types.INTERCOM");
        aC = ouqVar80;
        ouq ouqVar81 = new ouq("KETTLE", 80, "action.devices.types.KETTLE");
        aD = ouqVar81;
        ouq ouqVar82 = new ouq("KEYS", 81, "action.devices.types.KEYS");
        aE = ouqVar82;
        ouq ouqVar83 = new ouq("LAPTOP", 82, "action.devices.types.LAPTOP");
        aF = ouqVar83;
        ouq ouqVar84 = new ouq("LOCATORTAG", 83, "action.devices.types.LOCATORTAG");
        aG = ouqVar84;
        ouq ouqVar85 = new ouq("MAILBOX", 84, "action.devices.types.MAILBOX");
        aH = ouqVar85;
        ouq ouqVar86 = new ouq("MATTRESS", 85, "action.devices.types.MATTRESS");
        aI = ouqVar86;
        ouq ouqVar87 = new ouq("MICROPHONE", 86, "action.devices.types.MICROPHONE");
        aJ = ouqVar87;
        ouq ouqVar88 = new ouq("MICROWAVE", 87, "action.devices.types.MICROWAVE");
        aK = ouqVar88;
        ouq ouqVar89 = new ouq("MIXER", 88, "action.devices.types.MIXER");
        aL = ouqVar89;
        ouq ouqVar90 = new ouq("MOP", 89, "action.devices.types.MOP");
        aM = ouqVar90;
        ouq ouqVar91 = new ouq("MOWER", 90, "action.devices.types.MOWER");
        aN = ouqVar91;
        ouq ouqVar92 = new ouq("MULTICOOKER", 91, "action.devices.types.MULTICOOKER");
        aO = ouqVar92;
        ouq ouqVar93 = new ouq("NOTEBOOK", 92, "action.devices.types.NOTEBOOK");
        aP = ouqVar93;
        ouq ouqVar94 = new ouq("OVEN", 93, "action.devices.types.OVEN");
        aQ = ouqVar94;
        ouq ouqVar95 = new ouq("PASSPORT", 94, "action.devices.types.PASSPORT");
        aR = ouqVar95;
        ouq ouqVar96 = new ouq("PERGOLA", 95, "action.devices.types.PERGOLA");
        aS = ouqVar96;
        ouq ouqVar97 = new ouq("PETFEEDER", 96, "action.devices.types.PETFEEDER");
        aT = ouqVar97;
        ouq ouqVar98 = new ouq("PHONE", 97, "action.devices.types.PHONE");
        aU = ouqVar98;
        ouq ouqVar99 = new ouq("PICTURE", 98, "action.devices.types.PICTURE");
        aV = ouqVar99;
        ouq ouqVar100 = new ouq("PRESSURECOOKER", 99, "action.devices.types.PRESSURECOOKER");
        aW = ouqVar100;
        ouq ouqVar101 = new ouq("PUMP", 100, "action.devices.types.PUMP");
        aX = ouqVar101;
        ouq ouqVar102 = new ouq("RADIATOR", 101, "action.devices.types.RADIATOR");
        aY = ouqVar102;
        ouq ouqVar103 = new ouq("REFRIGERATOR", 102, "action.devices.types.REFRIGERATOR");
        aZ = ouqVar103;
        ouq ouqVar104 = new ouq("ROBOT", 103, "action.devices.types.ROBOT");
        ba = ouqVar104;
        ouq ouqVar105 = new ouq("ROOF", 104, "action.devices.types.ROOF");
        bb = ouqVar105;
        ouq ouqVar106 = new ouq("ROUTER", 105, "action.devices.types.ROUTER");
        bc = ouqVar106;
        ouq ouqVar107 = new ouq("ROUTINE", 106, "action.devices.types.ROUTINE");
        bd = ouqVar107;
        ouq ouqVar108 = new ouq("SECURITY_SYSTEM", 107, "action.devices.types.SECURITYSYSTEM");
        be = ouqVar108;
        ouq ouqVar109 = new ouq("SHOWER", 108, "action.devices.types.SHOWER");
        bf = ouqVar109;
        ouq ouqVar110 = new ouq("SHUTTER", 109, "action.devices.types.SHUTTER");
        bg = ouqVar110;
        ouq ouqVar111 = new ouq("SMOKE_DETECTOR", 110, "action.devices.types.SMOKE_DETECTOR");
        bh = ouqVar111;
        ouq ouqVar112 = new ouq("SOUNDBAR", 111, "action.devices.types.SOUNDBAR");
        bi = ouqVar112;
        ouq ouqVar113 = new ouq("SOUSVIDE", 112, "action.devices.types.SOUSVIDE");
        bj = ouqVar113;
        ouq ouqVar114 = new ouq("SPRINKLER", 113, "action.devices.types.SPRINKLER");
        bk = ouqVar114;
        ouq ouqVar115 = new ouq("STANDMIXER", 114, "action.devices.types.STANDMIXER");
        bl = ouqVar115;
        ouq ouqVar116 = new ouq("STREAMING_BOX", 115, "action.devices.types.STREAMING_BOX");
        bm = ouqVar116;
        ouq ouqVar117 = new ouq("STREAMING_SOUNDBAR", 116, "action.devices.types.STREAMING_SOUNDBAR");
        bn = ouqVar117;
        ouq ouqVar118 = new ouq("STREAMING_STICK", 117, "action.devices.types.STREAMING_STICK");
        bo = ouqVar118;
        ouq ouqVar119 = new ouq("STYLER", 118, "action.devices.types.STYLER");
        bp = ouqVar119;
        ouq ouqVar120 = new ouq("TABLET", 119, "action.devices.types.TABLET");
        bq = ouqVar120;
        ouq ouqVar121 = new ouq("TOILET", 120, "action.devices.types.TOILET");
        br = ouqVar121;
        ouq ouqVar122 = new ouq("TOY", 121, "action.devices.types.TOY");
        bs = ouqVar122;
        ouq ouqVar123 = new ouq("UMBRELLA", 122, "action.devices.types.UMBRELLA");
        bt = ouqVar123;
        ouq ouqVar124 = new ouq("VALVE", 123, "action.devices.types.VALVE");
        bu = ouqVar124;
        ouq ouqVar125 = new ouq("VENTILATOR", 124, "action.devices.types.VENTILATOR");
        bv = ouqVar125;
        ouq ouqVar126 = new ouq("WALLET", 125, "action.devices.types.WALLET");
        bw = ouqVar126;
        ouq ouqVar127 = new ouq("WATCH", 126, "action.devices.types.WATCH");
        bx = ouqVar127;
        ouq ouqVar128 = new ouq("WATERHEATER", 127, "action.devices.types.WATERHEATER");
        by = ouqVar128;
        ouq ouqVar129 = new ouq("WATERPURIFIER", 128, "action.devices.types.WATERPURIFIER");
        bz = ouqVar129;
        ouq ouqVar130 = new ouq("WATERSOFTENER", 129, "action.devices.types.WATERSOFTENER");
        bA = ouqVar130;
        ouq ouqVar131 = new ouq("WEATHERSTATION", 130, "action.devices.types.WEATHERSTATION");
        bB = ouqVar131;
        ouq ouqVar132 = new ouq("WINDOW", 131, "action.devices.types.WINDOW");
        bC = ouqVar132;
        ouq ouqVar133 = new ouq("WINECELLER", 132, "action.devices.types.WINECELLER");
        bD = ouqVar133;
        ouq ouqVar134 = new ouq("YOGURTMAKER", 133, "action.devices.types.YOGURTMAKER");
        bE = ouqVar134;
        ouq[] ouqVarArr = {ouqVar, ouqVar2, ouqVar3, ouqVar4, ouqVar5, ouqVar6, ouqVar7, ouqVar8, ouqVar9, ouqVar10, ouqVar11, ouqVar12, ouqVar13, ouqVar14, ouqVar15, ouqVar16, ouqVar17, ouqVar18, ouqVar19, ouqVar20, ouqVar21, ouqVar22, ouqVar23, ouqVar24, ouqVar25, ouqVar26, ouqVar27, ouqVar28, ouqVar29, ouqVar30, ouqVar31, ouqVar32, ouqVar33, ouqVar34, ouqVar35, ouqVar36, ouqVar37, ouqVar38, ouqVar39, ouqVar40, ouqVar41, ouqVar42, ouqVar43, ouqVar44, ouqVar45, ouqVar46, ouqVar47, ouqVar48, ouqVar49, ouqVar50, ouqVar51, ouqVar52, ouqVar53, ouqVar54, ouqVar55, ouqVar56, ouqVar57, ouqVar58, ouqVar59, ouqVar60, ouqVar61, ouqVar62, ouqVar63, ouqVar64, ouqVar65, ouqVar66, ouqVar67, ouqVar68, ouqVar69, ouqVar70, ouqVar71, ouqVar72, ouqVar73, ouqVar74, ouqVar75, ouqVar76, ouqVar77, ouqVar78, ouqVar79, ouqVar80, ouqVar81, ouqVar82, ouqVar83, ouqVar84, ouqVar85, ouqVar86, ouqVar87, ouqVar88, ouqVar89, ouqVar90, ouqVar91, ouqVar92, ouqVar93, ouqVar94, ouqVar95, ouqVar96, ouqVar97, ouqVar98, ouqVar99, ouqVar100, ouqVar101, ouqVar102, ouqVar103, ouqVar104, ouqVar105, ouqVar106, ouqVar107, ouqVar108, ouqVar109, ouqVar110, ouqVar111, ouqVar112, ouqVar113, ouqVar114, ouqVar115, ouqVar116, ouqVar117, ouqVar118, ouqVar119, ouqVar120, ouqVar121, ouqVar122, ouqVar123, ouqVar124, ouqVar125, ouqVar126, ouqVar127, ouqVar128, ouqVar129, ouqVar130, ouqVar131, ouqVar132, ouqVar133, ouqVar134};
        bF = ouqVarArr;
        agtv agtvVarA = agtw.a(ouqVarArr);
        bG = agtvVarA;
        int iB = agrj.b(agqq.i(agtvVarA, 10));
        LinkedHashMap linkedHashMap = new LinkedHashMap(iB < 16 ? 16 : iB);
        agqa agqaVar = new agqa((agqd) agtvVarA);
        while (agqaVar.hasNext()) {
            Object next = agqaVar.next();
            linkedHashMap.put(((ouq) next).bH, next);
        }
        a = linkedHashMap;
    }

    private ouq(String str, int i2, String str2) {
        this.bH = str2;
    }

    public static ouq[] values() {
        return (ouq[]) bF.clone();
    }
}
