package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public enum rpy implements rqp {
    FLOW_TYPE_UNKNOWN(0),
    NONE(1),
    TRANSCRIPTION_INTENT_API(101),
    TRANSCRIPTION_RECOGNITION_SERVICE(102),
    TRANSCRIPTION_VOICE_IME(103),
    BACKGROUND_SYNC(104),
    INTENT_DOWNLOAD_LANGUAGE(105),
    INTENT_GET_LANGUAGE_DETAILS(106),
    SETTINGS_DOWNLOAD_CONDITION(107),
    SETTINGS_LOAD_AVAILABLE_PACK_LIST(108),
    SETTINGS_LOAD_DOWNLOADED_PACK_LIST(109),
    SETTINGS_PACK_DIALOG(110),
    DICTATION_QUALITY_METRICS(111),
    MODEL_MANAGER_CHECK_RECOGNITION_SUPPORT(112),
    MODEL_MANAGER_TRIGGER_MODEL_DOWNLOAD(113),
    TRANSCRIPTION_RECOGNITION_GRPC_SERVICE(114),
    TRANSCRIPTION_INTENT_API_COUNT(115),
    TRANSCRIPTION_RECOGNITION_GRPC_SERVICE_QUERY_SESSION(116),
    TRANSLATION_SESSION(117),
    TRANSLATION_MODEL_QUERY_AVAILABILITY_SESSION(118),
    TRANSLATION_MODEL_DOWNLOAD_SESSION(119);

    private final int w;

    rpy(int i) {
        this.w = i;
    }

    @Override // defpackage.rqp
    public final int a() {
        return this.w;
    }
}
