package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public enum tga {
    CONTEXT_API(tfu.ASSISTANT),
    TTS_API(tfu.ASSISTANT),
    DATADOWNLOAD_API(tfu.ASSISTANT),
    AUDIO_LIBRARY_AAE(tfu.ASSISTANT_AUTO_EMBEDDED),
    AUDIO_LIBRARY_AAP(tfu.ASSISTANT_AUTO_PROJECTED),
    AUDIO_LIBRARY_ASSISTANT(tfu.ASSISTANT),
    AUDIO_LIBRARY_ASSISTANT_TITAN(tfu.ASSISTANT_TITAN_TNG),
    AUDIO_LIBRARY_BISTO(tfu.BISTO),
    AUDIO_LIBRARY_GOOGLE(tfu.GOOGLE_APP),
    AUDIO_LIBRARY_OMNIENT(tfu.OMNI),
    AUDIO_LIBRARY_LENS_LIVE(tfu.LENS),
    AUDIO_LIBRARY_PRONTO(tfu.PRONUNCIATION_LEARNING),
    AUDIO_LIBRARY_QUICK_PHRASES(tfu.QUICK_PHRASES),
    AUDIO_LIBRARY_ROBIN(tfu.ROBIN_ANDROID),
    AUDIO_LIBRARY_SODA(tfu.SODA_ANDROID),
    AUDIO_LIBRARY_SOUND_SEARCH(tfu.SOUND_SEARCH),
    AUDIO_LIBRARY_TRANSCRIPTION(tfu.TRANSCRIPTION),
    ROBIN_PODCASTS(tfu.ROBIN_ANDROID),
    TEST_LOGGER(tfu.GOOGLE_APP);

    public final tfu t;

    tga(tfu tfuVar) {
        this.t = tfuVar;
    }
}
