package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public interface thg {
    static {
        agqj.p(new zpf[]{zpf.USER_EVENT_CUSTOM_TABS_COPY_LINK_CLICKED, zpf.USER_EVENT_CUSTOM_TABS_NAVIGATION_ENDED, zpf.USER_EVENT_CUSTOM_TABS_OPEN, zpf.USER_EVENT_CUSTOM_TABS_OPEN_IN_BROWSER_CLICKED, zpf.USER_EVENT_CUSTOM_TABS_TAB_HIDDEN});
        agqj.p(new zpf[]{zpf.USER_EVENT_CLICK_ON_DEVICE_RESULT, zpf.USER_EVENT_CLICK_ON_WEB, zpf.USER_EVENT_QUERY_ABANDONED});
        agqj.p(new zpf[]{zpf.GEARHEAD_ASSISTANT_TOOLTIP_FOR_FIRST_RUN, zpf.GEARHEAD_ASSISTANT_TOOLTIP_FOR_MEDIA_OPEN, zpf.GEARHEAD_ASSISTANT_TOOLTIP_FOR_LAUNCHER_OPEN, zpf.GEARHEAD_ASSISTANT_TOOLTIP_FOR_LONG_DRIVE_START, zpf.GEARHEAD_ASSISTANT_MEDIA_REC_TOOLTIP_FOR_DRIVE_START, zpf.GEARHEAD_ASSISTANT_MEDIA_REC_TOOLTIP_FOR_MEDIA_IDLE, zpf.GEARHEAD_CUJ_SHORTCUTS_MEDIA_IMMERSIVE_CLICKED, zpf.GEARHEAD_CUJ_SHORTCUTS_MEDIA_CLICKED, zpf.GEARHEAD_CUJ_SHORTCUTS_CALL_CLICKED, zpf.GEARHEAD_CUJ_SHORTCUTS_MESSAGING_CLICKED, zpf.GEARHEAD_LONG_DRIVE_START, zpf.OPA_AUTO_ON_GEARHEAD_ASSISTANT_CONNECTION_STARTED, zpf.OPA_AUTO_ON_GEARHEAD_ASSISTANT_CONNECTION_STOPPED, zpf.OPA_AUTO_ON_GEARHEAD_ASSISTANT_SESSION_STARTED});
        agqj.p(new zpf[]{zpf.SMARTSPACE_WIDGET_ADDED, zpf.SMARTSPACE_WIDGET_DELETED, zpf.SMARTSPACE_WIDGET_UPDATED});
    }

    zyd a(rru rruVar, yyk yykVar);
}
