package defpackage;

import java.util.Collections;
import java.util.EnumMap;
import java.util.Iterator;
import java.util.Map;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class tiz {
    public static final yyr a;

    static {
        yyr yyrVarK;
        yyn yynVar = new yyn(4);
        yynVar.c(tix.TAG_GOOGLE_APP_TEST, "google_app.test");
        yynVar.c(tix.TAG_CLASSIC_TEST_AREA_TEST, "test_area.test");
        yynVar.c(tix.TAG_CLASSIC_TEST_AREA, "test_area");
        yynVar.c(tix.TAG_GOOGLE_APP_SEARCH, "google_app.search");
        yynVar.c(tix.TAG_GOOGLE_APP_SEARCH_LISTENER, "google_app.search_listener");
        yynVar.c(tix.TAG_GOOGLE_APP_BROWSER, "google_app.browser");
        yynVar.c(tix.TAG_GOOGLE_APP_BROWSER_SILENT, "google_app.browser_silent");
        yynVar.c(tix.TAG_ASSISTANT_ACCL, "assistant.accl");
        yynVar.c(tix.TAG_ASSISTANT_PCP, "assistant.pcp");
        yynVar.c(tix.TAG_ASSISTANT_WEATHER_AT_FLIGHT_LANDING_LO, "assistant.weather_at_flight_landing_lo");
        yynVar.c(tix.TAG_ASSISTANT_PLATFORM, "assistant.platform");
        yynVar.c(tix.TAG_ASSISTANT_DICTATION, "assistant.dictation");
        yynVar.c(tix.TAG_ASSISTANT_TRANSLATE, "assistant.translate");
        yynVar.c(tix.TAG_ASSISTANT_WIDGET, "assistant.widget");
        yynVar.c(tix.TAG_ASSISTANT_STASH, "assistant.stash");
        yynVar.c(tix.TAG_ASSISTANT_AMBIENT, "assistant.ambient");
        yynVar.c(tix.TAG_ASSISTANT_RECOMMEND, "assistant.recommend");
        yynVar.c(tix.TAG_ASSISTANT_ROUTINES, "assistant.routines");
        yynVar.c(tix.TAG_ASSISTANT_VOICE, "assistant.voice");
        yynVar.c(tix.TAG_ASSISTANT_MOBILE_ASSISTANT, "assistant.mobile_assistant");
        yynVar.c(tix.TAG_ASSISTANT_MOBILE_ASSISTANT_LS, "assistant.mobile_assistant_ls");
        yynVar.c(tix.TAG_NIU_SEARCH, "hindi.search");
        yynVar.c(tix.TAG_NIU_BROWSER, "hindi.browser");
        yynVar.c(tix.TAG_UNKNOWN_SILK, "unknown.silk");
        yynVar.c(tix.TAG_TRANSCRIPTION_VOICE_RECOGNITION, "transcription.voice_recognition");
        yynVar.c(tix.TAG_TRANSCRIPTION_VOICE_IME, "transcription.voice_ime");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_VOICE_MATCH, "assistant.voice_match");
        yynVar.c(tix.TAG_CLASSIC_ACCESSIBILITY_VOICE_ACCESS, "accessibility.voice_access");
        yynVar.c(tix.TAG_GOOGLE_APP_MINUS_ONE, "google_app.minus_one");
        yynVar.c(tix.TAG_WEATHER_IMMERSIVE, "weather.immersive");
        yynVar.c(tix.TAG_WEATHER_WIDGET, "weather.widget");
        yynVar.c(tix.TAG_NETWORK_MONITORING_LIBRARY_SEARCH_ANDROID_QUALITY, "network_monitoring_library_search_android.quality");
        yynVar.c(tix.TAG_SOUND_SEARCH_NOW_PLAYING, "sound_search.now_playing");
        yynVar.c(tix.TAG_SOUND_SEARCH_MUSIC_RECOGNITION, "sound_search.music_recognition");
        yynVar.c(tix.TAG_GOOGLE_APP_HOMESCREEN, "google_app.homescreen");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT, "assistant");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_DEVICE_REGISTRATION, "assistant.device_registration");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_AMBIENT_CLASSIC, "assistant.ambient_classic");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_AMBIENT_BUG_REPORT, "assistant.ambient_bug_report");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_AUTO, "assistant.auto");
        yynVar.c(tix.TAG_ASSISTANT_AUTO_TNG_COMMS, "assistant_auto_tng.comms");
        yynVar.c(tix.TAG_ASSISTANT_AUTO_TNG_MIC, "assistant_auto_tng.mic");
        yynVar.c(tix.TAG_ASSISTANT_AUTO_TNG_SUGGESTIONS, "assistant_auto_tng.suggestions");
        yynVar.c(tix.TAG_ASSISTANT_AUTO_TNG_MORRIS, "assistant_auto_tng.morris");
        yynVar.c(tix.TAG_ASSISTANT_AUTO_TNG_POP, "assistant_auto_tng.pop");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_BISTO, "assistant.bisto");
        yynVar.c(tix.TAG_ASSISTANT_TNG_BISTO, "assistant.tng_bisto");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_FACEMATCH, "assistant.facematch");
        yynVar.c(tix.TAG_CLASSIC_LENS, "lens");
        yynVar.c(tix.TAG_LENS_BROWSER, "lens.browser");
        yynVar.c(tix.TAG_LENS_LVF, "lens.lvf");
        yynVar.c(tix.TAG_LENS_NETWORK_METADATA, "lens.network_metadata");
        yynVar.c(tix.TAG_LENS_SILK_GEOLOCATION_REAL_TIME, "lens.silk_geolocation_real_time");
        yynVar.c(tix.TAG_LENS_LIVE, "lens.live");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_LEGACY, "assistant.legacy");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_NGA, "assistant.nga");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_TAPAS, "assistant.tapas");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_SETTINGS, "assistant.settings");
        yynVar.c(tix.TAG_ASSISTANT_TNG_SETTINGS, "assistant.tng_settings");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_SNAPSHOT, "assistant.snapshot");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_VOICEACTIONS, "assistant.voiceactions");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_PCP_CLASSIC, "assistant.pcp_classic");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_PROACTIVEAPI, "assistant.proactiveapi");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_NOTIFICATIONS, "assistant.notifications");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_CAR_LO, "assistant.car_lo");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_CLIENTSYNC_LO, "assistant.clientsync_lo");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_MORRIS_LO, "assistant.morris_lo");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_SMARTSPACE_WEATHER_LO, "assistant.smartspace_weather_lo");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_QUARTZ_LO, "assistant.quartz_lo");
        yynVar.c(tix.TAG_LENS_LO, "lens.lo");
        yynVar.c(tix.TAG_LENS_SEMANTIC_LO, "lens.semantic_lo");
        yynVar.c(tix.TAG_CLASSIC_SEARCH_EMBEDDED_LO, "search.embedded_lo");
        yynVar.c(tix.TAG_CLASSIC_SEARCH_LO, "search.lo");
        yynVar.c(tix.TAG_CLASSIC_SEARCH_PROACTIVE, "search.proactive");
        yynVar.c(tix.TAG_CLASSIC_SEARCH_PROACTIVE_LO, "search.proactive_lo");
        yynVar.c(tix.TAG_CLASSIC_SEARCH_SIDEKICK_LO, "search.sidekick_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES, "services");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_ACCL, "services.accl");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_ACCL_LO, "services.accl_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_CAST, "services.cast");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_CHIME_LO, "services.chime_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_CLOCKWORK_LO, "services.clockwork_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_CLOCKWORK_MIC, "services.clockwork_mic");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_CONTACTAFFINITY, "services.contactaffinity");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_CONTEXTUALCARDS_LO, "services.contextualcards_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_LO, "services.lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_MDD_LO, "services.mdd_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_MDI_LIB, "services.mdi_lib");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_SILK_LO, "services.silk_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_S3_LO, "services.s3_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_TELEPHONY, "services.telephony");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_TV_LO, "services.tv_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_WEATHER_LO, "services.weather_lo");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_WIFI, "services.wifi");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_CO, "services.co");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_CLOCKWORK_CO, "services.clockwork_co");
        yynVar.c(tix.TAG_CREATOR_STUDIO_RECORD, "creator_studio.record");
        yynVar.c(tix.TAG_ASSISTANT_TNG_CAR_LO, "assistant.tng_car_lo");
        yynVar.c(tix.TAG_CLASSIC_SEARCH_URI_LO, "search.uri_lo");
        yynVar.c(tix.TAG_CLASSIC_VOICE_SEARCH_LO, "voice_search.lo");
        yynVar.c(tix.TAG_CLASSIC_VOICE_SEARCH_MIC, "voice_search.mic");
        yynVar.c(tix.TAG_ASSISTANT_CALENDAR, "assistant.calendar");
        yynVar.c(tix.TAG_ASSISTANT_HUBUI, "assistant.hubui");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_URI_VIS, "assistant.uri_vis");
        yynVar.c(tix.TAG_SCENEVIEWER_CAPTURE, "sceneviewer.capture");
        yynVar.c(tix.TAG_ASSISTANT_TORUS, "assistant.torus");
        yynVar.c(tix.TAG_WEB_X_WEBLAYER, "web_x.weblayer");
        yynVar.c(tix.TAG_CLASSIC_ASSISTANT_TEXT_SEARCH, "assistant.text_search");
        yynVar.c(tix.TAG_GOOGLE_APP_SILK_GEOLOCATION_REAL_TIME, "google_app.silk_geolocation_real_time");
        yynVar.c(tix.TAG_ASSISTANT_SILK_GEOLOCATION_REAL_TIME, "assistant.silk_geolocation_real_time");
        yynVar.c(tix.TAG_CLASSIC_SERVICES_SILK_REAL_TIME_LO, "services.silk_real_time_lo");
        yynVar.c(tix.TAG_GOOGLE_APP_TOAST, "google_app.toast");
        yynVar.c(tix.TAG_GOOGLE_APP_NOTIFICATIONS, "google_app.notifications");
        yynVar.c(tix.TAG_ASSISTANT_CONNECTIVITY_USONIA, "assistant.connectivity_usonia");
        yynVar.c(tix.TAG_ASSISTANT_TITAN_TNG_HUBMODE, "assistant_titan_tng.hubmode");
        yynVar.c(tix.TAG_ASSISTANT_UNATTRIBUTED_ANDROID_TRUSTED_HOTWORD, "assistant.unattributed_android_trusted_hotword");
        yynVar.c(tix.TAG_XBLEND_ANDROID_GEOLOCATION, "xblend_android.geolocation");
        yynVar.c(tix.TAG_WEATHER_IMMERSIVE_REAL_TIME, "weather.immersive_real_time");
        yynVar.c(tix.TAG_ROBIN_ANDROID_LOCATION, "robin_android.location");
        yynVar.c(tix.TAG_ROBIN_ANDROID_AUDIO, "robin_android.audio");
        yynVar.c(tix.TAG_OMNI_BROWSER, "omni.browser");
        yynVar.c(tix.TAG_OMNI_SILK_GEOLOCATION_REAL_TIME, "omni.silk_geolocation_real_time");
        yynVar.c(tix.TAG_OMNI_MUSIC_SEARCH, "omni.music_search");
        yynVar.c(tix.TAG_GOOGLE_APP_PAGE_INSIGHTS_HUB, "google_app.page_insights_hub");
        yynVar.c(tix.TAG_GOOGLE_APP_PIH_SILK_GEOLOCATION_REAL_TIME, "google_app.pih_silk_geolocation_real_time");
        yynVar.c(tix.TAG_ASSISTANT_REMOTE_SURFACE_PROXY, "assistant.remote_surface_proxy");
        yynVar.c(tix.TAG_GOOGLE_APP_VOICE_SEARCH_M2, "google_app.voice_search_m2");
        Iterator it = yynVar.a(false).entrySet().iterator();
        if (it.hasNext()) {
            Map.Entry entry = (Map.Entry) it.next();
            Enum r2 = (Enum) entry.getKey();
            Object value = entry.getValue();
            ywl.a(r2, value);
            EnumMap enumMap = new EnumMap(Collections.singletonMap(r2, value));
            while (it.hasNext()) {
                Map.Entry entry2 = (Map.Entry) it.next();
                Enum r22 = (Enum) entry2.getKey();
                Object value2 = entry2.getValue();
                ywl.a(r22, value2);
                enumMap.put((EnumMap) r22, (Enum) value2);
            }
            int size = enumMap.size();
            if (size == 0) {
                yyrVarK = zcl.a;
            } else if (size != 1) {
                yyrVarK = new yyb(enumMap);
            } else {
                Map.Entry entry3 = (Map.Entry) zag.f(enumMap.entrySet());
                yyrVarK = yyr.k((Enum) entry3.getKey(), entry3.getValue());
            }
        } else {
            yyrVarK = zcl.a;
        }
        a = yyrVarK;
        yyn yynVar2 = new yyn(4);
        yynVar2.c("google_app.test", tix.TAG_GOOGLE_APP_TEST);
        yynVar2.c("test_area.test", tix.TAG_CLASSIC_TEST_AREA_TEST);
        yynVar2.c("test_area", tix.TAG_CLASSIC_TEST_AREA);
        yynVar2.c("google_app.search", tix.TAG_GOOGLE_APP_SEARCH);
        yynVar2.c("google_app.search_listener", tix.TAG_GOOGLE_APP_SEARCH_LISTENER);
        yynVar2.c("google_app.browser", tix.TAG_GOOGLE_APP_BROWSER);
        yynVar2.c("google_app.browser_silent", tix.TAG_GOOGLE_APP_BROWSER_SILENT);
        yynVar2.c("assistant.accl", tix.TAG_ASSISTANT_ACCL);
        yynVar2.c("assistant.pcp", tix.TAG_ASSISTANT_PCP);
        yynVar2.c("assistant.weather_at_flight_landing_lo", tix.TAG_ASSISTANT_WEATHER_AT_FLIGHT_LANDING_LO);
        yynVar2.c("assistant.platform", tix.TAG_ASSISTANT_PLATFORM);
        yynVar2.c("assistant.dictation", tix.TAG_ASSISTANT_DICTATION);
        yynVar2.c("assistant.translate", tix.TAG_ASSISTANT_TRANSLATE);
        yynVar2.c("assistant.widget", tix.TAG_ASSISTANT_WIDGET);
        yynVar2.c("assistant.stash", tix.TAG_ASSISTANT_STASH);
        yynVar2.c("assistant.ambient", tix.TAG_ASSISTANT_AMBIENT);
        yynVar2.c("assistant.recommend", tix.TAG_ASSISTANT_RECOMMEND);
        yynVar2.c("assistant.routines", tix.TAG_ASSISTANT_ROUTINES);
        yynVar2.c("assistant.voice", tix.TAG_ASSISTANT_VOICE);
        yynVar2.c("assistant.mobile_assistant", tix.TAG_ASSISTANT_MOBILE_ASSISTANT);
        yynVar2.c("assistant.mobile_assistant_ls", tix.TAG_ASSISTANT_MOBILE_ASSISTANT_LS);
        yynVar2.c("hindi.search", tix.TAG_NIU_SEARCH);
        yynVar2.c("hindi.browser", tix.TAG_NIU_BROWSER);
        yynVar2.c("unknown.silk", tix.TAG_UNKNOWN_SILK);
        yynVar2.c("transcription.voice_recognition", tix.TAG_TRANSCRIPTION_VOICE_RECOGNITION);
        yynVar2.c("transcription.voice_ime", tix.TAG_TRANSCRIPTION_VOICE_IME);
        yynVar2.c("assistant.voice_match", tix.TAG_CLASSIC_ASSISTANT_VOICE_MATCH);
        yynVar2.c("accessibility.voice_access", tix.TAG_CLASSIC_ACCESSIBILITY_VOICE_ACCESS);
        yynVar2.c("google_app.minus_one", tix.TAG_GOOGLE_APP_MINUS_ONE);
        yynVar2.c("weather.immersive", tix.TAG_WEATHER_IMMERSIVE);
        yynVar2.c("weather.widget", tix.TAG_WEATHER_WIDGET);
        yynVar2.c("network_monitoring_library_search_android.quality", tix.TAG_NETWORK_MONITORING_LIBRARY_SEARCH_ANDROID_QUALITY);
        yynVar2.c("sound_search.now_playing", tix.TAG_SOUND_SEARCH_NOW_PLAYING);
        yynVar2.c("sound_search.music_recognition", tix.TAG_SOUND_SEARCH_MUSIC_RECOGNITION);
        yynVar2.c("google_app.homescreen", tix.TAG_GOOGLE_APP_HOMESCREEN);
        yynVar2.c("assistant", tix.TAG_CLASSIC_ASSISTANT);
        yynVar2.c("assistant.device_registration", tix.TAG_CLASSIC_ASSISTANT_DEVICE_REGISTRATION);
        yynVar2.c("assistant.ambient_classic", tix.TAG_CLASSIC_ASSISTANT_AMBIENT_CLASSIC);
        yynVar2.c("assistant.ambient_bug_report", tix.TAG_CLASSIC_ASSISTANT_AMBIENT_BUG_REPORT);
        yynVar2.c("assistant.auto", tix.TAG_CLASSIC_ASSISTANT_AUTO);
        yynVar2.c("assistant_auto_tng.comms", tix.TAG_ASSISTANT_AUTO_TNG_COMMS);
        yynVar2.c("assistant_auto_tng.mic", tix.TAG_ASSISTANT_AUTO_TNG_MIC);
        yynVar2.c("assistant_auto_tng.suggestions", tix.TAG_ASSISTANT_AUTO_TNG_SUGGESTIONS);
        yynVar2.c("assistant_auto_tng.morris", tix.TAG_ASSISTANT_AUTO_TNG_MORRIS);
        yynVar2.c("assistant_auto_tng.pop", tix.TAG_ASSISTANT_AUTO_TNG_POP);
        yynVar2.c("assistant.bisto", tix.TAG_CLASSIC_ASSISTANT_BISTO);
        yynVar2.c("assistant.tng_bisto", tix.TAG_ASSISTANT_TNG_BISTO);
        yynVar2.c("assistant.facematch", tix.TAG_CLASSIC_ASSISTANT_FACEMATCH);
        yynVar2.c("lens", tix.TAG_CLASSIC_LENS);
        yynVar2.c("lens.browser", tix.TAG_LENS_BROWSER);
        yynVar2.c("lens.lvf", tix.TAG_LENS_LVF);
        yynVar2.c("lens.network_metadata", tix.TAG_LENS_NETWORK_METADATA);
        yynVar2.c("lens.silk_geolocation_real_time", tix.TAG_LENS_SILK_GEOLOCATION_REAL_TIME);
        yynVar2.c("lens.live", tix.TAG_LENS_LIVE);
        yynVar2.c("assistant.legacy", tix.TAG_CLASSIC_ASSISTANT_LEGACY);
        yynVar2.c("assistant.nga", tix.TAG_CLASSIC_ASSISTANT_NGA);
        yynVar2.c("assistant.tapas", tix.TAG_CLASSIC_ASSISTANT_TAPAS);
        yynVar2.c("assistant.settings", tix.TAG_CLASSIC_ASSISTANT_SETTINGS);
        yynVar2.c("assistant.tng_settings", tix.TAG_ASSISTANT_TNG_SETTINGS);
        yynVar2.c("assistant.snapshot", tix.TAG_CLASSIC_ASSISTANT_SNAPSHOT);
        yynVar2.c("assistant.voiceactions", tix.TAG_CLASSIC_ASSISTANT_VOICEACTIONS);
        yynVar2.c("assistant.pcp_classic", tix.TAG_CLASSIC_ASSISTANT_PCP_CLASSIC);
        yynVar2.c("assistant.proactiveapi", tix.TAG_CLASSIC_ASSISTANT_PROACTIVEAPI);
        yynVar2.c("assistant.notifications", tix.TAG_CLASSIC_ASSISTANT_NOTIFICATIONS);
        yynVar2.c("assistant.car_lo", tix.TAG_CLASSIC_ASSISTANT_CAR_LO);
        yynVar2.c("assistant.clientsync_lo", tix.TAG_CLASSIC_ASSISTANT_CLIENTSYNC_LO);
        yynVar2.c("assistant.morris_lo", tix.TAG_CLASSIC_ASSISTANT_MORRIS_LO);
        yynVar2.c("assistant.smartspace_weather_lo", tix.TAG_CLASSIC_ASSISTANT_SMARTSPACE_WEATHER_LO);
        yynVar2.c("assistant.quartz_lo", tix.TAG_CLASSIC_ASSISTANT_QUARTZ_LO);
        yynVar2.c("lens.lo", tix.TAG_LENS_LO);
        yynVar2.c("lens.semantic_lo", tix.TAG_LENS_SEMANTIC_LO);
        yynVar2.c("search.embedded_lo", tix.TAG_CLASSIC_SEARCH_EMBEDDED_LO);
        yynVar2.c("search.lo", tix.TAG_CLASSIC_SEARCH_LO);
        yynVar2.c("search.proactive", tix.TAG_CLASSIC_SEARCH_PROACTIVE);
        yynVar2.c("search.proactive_lo", tix.TAG_CLASSIC_SEARCH_PROACTIVE_LO);
        yynVar2.c("search.sidekick_lo", tix.TAG_CLASSIC_SEARCH_SIDEKICK_LO);
        yynVar2.c("services", tix.TAG_CLASSIC_SERVICES);
        yynVar2.c("services.accl", tix.TAG_CLASSIC_SERVICES_ACCL);
        yynVar2.c("services.accl_lo", tix.TAG_CLASSIC_SERVICES_ACCL_LO);
        yynVar2.c("services.cast", tix.TAG_CLASSIC_SERVICES_CAST);
        yynVar2.c("services.chime_lo", tix.TAG_CLASSIC_SERVICES_CHIME_LO);
        yynVar2.c("services.clockwork_lo", tix.TAG_CLASSIC_SERVICES_CLOCKWORK_LO);
        yynVar2.c("services.clockwork_mic", tix.TAG_CLASSIC_SERVICES_CLOCKWORK_MIC);
        yynVar2.c("services.contactaffinity", tix.TAG_CLASSIC_SERVICES_CONTACTAFFINITY);
        yynVar2.c("services.contextualcards_lo", tix.TAG_CLASSIC_SERVICES_CONTEXTUALCARDS_LO);
        yynVar2.c("services.lo", tix.TAG_CLASSIC_SERVICES_LO);
        yynVar2.c("services.mdd_lo", tix.TAG_CLASSIC_SERVICES_MDD_LO);
        yynVar2.c("services.mdi_lib", tix.TAG_CLASSIC_SERVICES_MDI_LIB);
        yynVar2.c("services.silk_lo", tix.TAG_CLASSIC_SERVICES_SILK_LO);
        yynVar2.c("services.s3_lo", tix.TAG_CLASSIC_SERVICES_S3_LO);
        yynVar2.c("services.telephony", tix.TAG_CLASSIC_SERVICES_TELEPHONY);
        yynVar2.c("services.tv_lo", tix.TAG_CLASSIC_SERVICES_TV_LO);
        yynVar2.c("services.weather_lo", tix.TAG_CLASSIC_SERVICES_WEATHER_LO);
        yynVar2.c("services.wifi", tix.TAG_CLASSIC_SERVICES_WIFI);
        yynVar2.c("services.co", tix.TAG_CLASSIC_SERVICES_CO);
        yynVar2.c("services.clockwork_co", tix.TAG_CLASSIC_SERVICES_CLOCKWORK_CO);
        yynVar2.c("creator_studio.record", tix.TAG_CREATOR_STUDIO_RECORD);
        yynVar2.c("assistant.tng_car_lo", tix.TAG_ASSISTANT_TNG_CAR_LO);
        yynVar2.c("search.uri_lo", tix.TAG_CLASSIC_SEARCH_URI_LO);
        yynVar2.c("voice_search.lo", tix.TAG_CLASSIC_VOICE_SEARCH_LO);
        yynVar2.c("voice_search.mic", tix.TAG_CLASSIC_VOICE_SEARCH_MIC);
        yynVar2.c("assistant.calendar", tix.TAG_ASSISTANT_CALENDAR);
        yynVar2.c("assistant.hubui", tix.TAG_ASSISTANT_HUBUI);
        yynVar2.c("assistant.uri_vis", tix.TAG_CLASSIC_ASSISTANT_URI_VIS);
        yynVar2.c("sceneviewer.capture", tix.TAG_SCENEVIEWER_CAPTURE);
        yynVar2.c("assistant.torus", tix.TAG_ASSISTANT_TORUS);
        yynVar2.c("web_x.weblayer", tix.TAG_WEB_X_WEBLAYER);
        yynVar2.c("assistant.text_search", tix.TAG_CLASSIC_ASSISTANT_TEXT_SEARCH);
        yynVar2.c("google_app.silk_geolocation_real_time", tix.TAG_GOOGLE_APP_SILK_GEOLOCATION_REAL_TIME);
        yynVar2.c("assistant.silk_geolocation_real_time", tix.TAG_ASSISTANT_SILK_GEOLOCATION_REAL_TIME);
        yynVar2.c("services.silk_real_time_lo", tix.TAG_CLASSIC_SERVICES_SILK_REAL_TIME_LO);
        yynVar2.c("google_app.toast", tix.TAG_GOOGLE_APP_TOAST);
        yynVar2.c("google_app.notifications", tix.TAG_GOOGLE_APP_NOTIFICATIONS);
        yynVar2.c("assistant.connectivity_usonia", tix.TAG_ASSISTANT_CONNECTIVITY_USONIA);
        yynVar2.c("assistant_titan_tng.hubmode", tix.TAG_ASSISTANT_TITAN_TNG_HUBMODE);
        yynVar2.c("assistant.unattributed_android_trusted_hotword", tix.TAG_ASSISTANT_UNATTRIBUTED_ANDROID_TRUSTED_HOTWORD);
        yynVar2.c("xblend_android.geolocation", tix.TAG_XBLEND_ANDROID_GEOLOCATION);
        yynVar2.c("weather.immersive_real_time", tix.TAG_WEATHER_IMMERSIVE_REAL_TIME);
        yynVar2.c("robin_android.location", tix.TAG_ROBIN_ANDROID_LOCATION);
        yynVar2.c("robin_android.audio", tix.TAG_ROBIN_ANDROID_AUDIO);
        yynVar2.c("omni.browser", tix.TAG_OMNI_BROWSER);
        yynVar2.c("omni.silk_geolocation_real_time", tix.TAG_OMNI_SILK_GEOLOCATION_REAL_TIME);
        yynVar2.c("omni.music_search", tix.TAG_OMNI_MUSIC_SEARCH);
        yynVar2.c("google_app.page_insights_hub", tix.TAG_GOOGLE_APP_PAGE_INSIGHTS_HUB);
        yynVar2.c("google_app.pih_silk_geolocation_real_time", tix.TAG_GOOGLE_APP_PIH_SILK_GEOLOCATION_REAL_TIME);
        yynVar2.c("assistant.remote_surface_proxy", tix.TAG_ASSISTANT_REMOTE_SURFACE_PROXY);
        yynVar2.c("google_app.voice_search_m2", tix.TAG_GOOGLE_APP_VOICE_SEARCH_M2);
        yynVar2.a(false);
    }
}
