package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* compiled from: PG */
/* loaded from: classes.dex */
public class zx {
    int a;
    public final aaa b = new aaa();
    public final zz c = new zz();
    public final zy d = new zy();
    public final aab e = new aab();
    public HashMap f = new HashMap();
    zw g;

    public final void a(zr zrVar) {
        zy zyVar = this.d;
        zrVar.e = zyVar.j;
        zrVar.f = zyVar.k;
        zrVar.g = zyVar.l;
        zrVar.h = zyVar.m;
        zrVar.i = zyVar.n;
        zrVar.j = zyVar.o;
        zrVar.k = zyVar.p;
        zrVar.l = zyVar.q;
        zrVar.m = zyVar.r;
        zrVar.n = zyVar.s;
        zrVar.o = zyVar.t;
        zrVar.s = zyVar.u;
        zrVar.t = zyVar.v;
        zrVar.u = zyVar.w;
        zrVar.v = zyVar.x;
        zrVar.leftMargin = zyVar.H;
        zrVar.rightMargin = zyVar.I;
        zrVar.topMargin = zyVar.J;
        zrVar.bottomMargin = zyVar.K;
        zrVar.A = zyVar.T;
        zrVar.B = zyVar.S;
        zrVar.x = zyVar.P;
        zrVar.z = zyVar.R;
        zrVar.G = zyVar.y;
        zrVar.H = zyVar.z;
        zrVar.p = zyVar.B;
        zrVar.q = zyVar.C;
        zrVar.r = zyVar.D;
        zrVar.I = zyVar.A;
        zrVar.X = zyVar.E;
        zrVar.Y = zyVar.F;
        zrVar.M = zyVar.V;
        zrVar.L = zyVar.W;
        zrVar.O = zyVar.Y;
        zrVar.N = zyVar.X;
        zrVar.aa = zyVar.an;
        zrVar.ab = zyVar.ao;
        zrVar.P = zyVar.Z;
        zrVar.Q = zyVar.aa;
        zrVar.T = zyVar.ab;
        zrVar.U = zyVar.ac;
        zrVar.R = zyVar.ad;
        zrVar.S = zyVar.ae;
        zrVar.V = zyVar.af;
        zrVar.W = zyVar.ag;
        zrVar.Z = zyVar.G;
        zrVar.c = zyVar.h;
        zrVar.a = zyVar.f;
        zrVar.b = zyVar.g;
        zrVar.width = zyVar.d;
        zrVar.height = zyVar.e;
        String str = zyVar.am;
        if (str != null) {
            zrVar.ac = str;
        }
        zrVar.ad = zyVar.aq;
        zrVar.setMarginStart(zyVar.M);
        zrVar.setMarginEnd(zyVar.L);
        zrVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        zx zxVar = new zx();
        zy zyVar = zxVar.d;
        zy zyVar2 = this.d;
        zyVar.b = zyVar2.b;
        zyVar.d = zyVar2.d;
        zyVar.c = zyVar2.c;
        zyVar.e = zyVar2.e;
        zyVar.f = zyVar2.f;
        zyVar.g = zyVar2.g;
        zyVar.h = zyVar2.h;
        zyVar.i = zyVar2.i;
        zyVar.j = zyVar2.j;
        zyVar.k = zyVar2.k;
        zyVar.l = zyVar2.l;
        zyVar.m = zyVar2.m;
        zyVar.n = zyVar2.n;
        zyVar.o = zyVar2.o;
        zyVar.p = zyVar2.p;
        zyVar.q = zyVar2.q;
        zyVar.r = zyVar2.r;
        zyVar.s = zyVar2.s;
        zyVar.t = zyVar2.t;
        zyVar.u = zyVar2.u;
        zyVar.v = zyVar2.v;
        zyVar.w = zyVar2.w;
        zyVar.x = zyVar2.x;
        zyVar.y = zyVar2.y;
        zyVar.z = zyVar2.z;
        zyVar.A = zyVar2.A;
        zyVar.B = zyVar2.B;
        zyVar.C = zyVar2.C;
        zyVar.D = zyVar2.D;
        zyVar.E = zyVar2.E;
        zyVar.F = zyVar2.F;
        zyVar.G = zyVar2.G;
        zyVar.H = zyVar2.H;
        zyVar.I = zyVar2.I;
        zyVar.J = zyVar2.J;
        zyVar.K = zyVar2.K;
        zyVar.L = zyVar2.L;
        zyVar.M = zyVar2.M;
        zyVar.N = zyVar2.N;
        zyVar.O = zyVar2.O;
        zyVar.P = zyVar2.P;
        zyVar.Q = zyVar2.Q;
        zyVar.R = zyVar2.R;
        zyVar.S = zyVar2.S;
        zyVar.T = zyVar2.T;
        zyVar.U = zyVar2.U;
        zyVar.V = zyVar2.V;
        zyVar.W = zyVar2.W;
        zyVar.X = zyVar2.X;
        zyVar.Y = zyVar2.Y;
        zyVar.Z = zyVar2.Z;
        zyVar.aa = zyVar2.aa;
        zyVar.ab = zyVar2.ab;
        zyVar.ac = zyVar2.ac;
        zyVar.ad = zyVar2.ad;
        zyVar.ae = zyVar2.ae;
        zyVar.af = zyVar2.af;
        zyVar.ag = zyVar2.ag;
        zyVar.ah = zyVar2.ah;
        zyVar.ai = zyVar2.ai;
        zyVar.aj = zyVar2.aj;
        zyVar.am = zyVar2.am;
        int[] iArr = zyVar2.ak;
        if (iArr == null || zyVar2.al != null) {
            zyVar.ak = null;
        } else {
            zyVar.ak = Arrays.copyOf(iArr, iArr.length);
        }
        zyVar.al = zyVar2.al;
        zyVar.an = zyVar2.an;
        zyVar.ao = zyVar2.ao;
        zyVar.ap = zyVar2.ap;
        zyVar.aq = zyVar2.aq;
        zz zzVar = zxVar.c;
        zz zzVar2 = this.c;
        zzVar.b = zzVar2.b;
        zzVar.c = zzVar2.c;
        zzVar.e = zzVar2.e;
        zzVar.f = zzVar2.f;
        zzVar.g = zzVar2.g;
        zzVar.j = zzVar2.j;
        zzVar.h = zzVar2.h;
        zzVar.i = zzVar2.i;
        aaa aaaVar = zxVar.b;
        aaa aaaVar2 = this.b;
        aaaVar.a = aaaVar2.a;
        aaaVar.b = aaaVar2.b;
        aaaVar.d = aaaVar2.d;
        aaaVar.e = aaaVar2.e;
        aaaVar.c = aaaVar2.c;
        aab aabVar = zxVar.e;
        aab aabVar2 = this.e;
        aabVar.b = aabVar2.b;
        aabVar.c = aabVar2.c;
        aabVar.d = aabVar2.d;
        aabVar.e = aabVar2.e;
        aabVar.f = aabVar2.f;
        aabVar.g = aabVar2.g;
        aabVar.h = aabVar2.h;
        aabVar.i = aabVar2.i;
        aabVar.j = aabVar2.j;
        aabVar.k = aabVar2.k;
        aabVar.l = aabVar2.l;
        aabVar.m = aabVar2.m;
        aabVar.n = aabVar2.n;
        aabVar.o = aabVar2.o;
        zxVar.a = this.a;
        zxVar.g = this.g;
        return zxVar;
    }
}
