package defpackage;

import android.content.Context;
import com.google.android.tv.remote.service.AtvRemoteServiceApplication;
import java.util.LinkedHashMap;
import java.util.List;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class bnh implements cox {
    final cpm A;
    final cpm B;
    final cpm C;
    final cpm D;
    final cpm E;
    final cpm F;
    final cpm G;
    final cpm H;
    final cpm I;
    final cpm J;
    final cpm K;
    final cpm L;
    final cpm M;
    final cpm N;
    final cpm O;
    final cpm P;
    final cpm Q;
    final cpm R;
    final cpm S;
    final cpm T;
    final cpm U;
    final cpm V;
    final cpm W;
    final cpm X;
    final cpm Y;
    final cpm Z;
    public final Context a;
    final cpm aA;
    final cpm aB;
    final cpm aC;
    final cpm aD;
    final cpm aE;
    final cpm aF;
    final cpm aG;
    final cpm aH;
    final cpm aI;
    final cpm aJ;
    final cpm aK;
    final cpm aL;
    final cpm aM;
    final cpm aN;
    final cpm aO;
    final cpm aP;
    final cpm aQ;
    final cpm aR;
    final cpm aS;
    final cpm aT;
    final cpm aU;
    final cpm aV;
    final cpm aW;
    final cpm aX;
    final cpm aY;
    final cpm aZ;
    final cpm aa;
    final cpm ab;
    final cpm ac;
    final cpm ad;
    final cpm ae;
    final cpm af;
    final cpm ag;
    final cpm ah;
    final cpm ai;
    final cpm aj;
    final cpm ak;
    final cpm al;
    final cpm am;
    final cpm an;
    final cpm ao;
    final cpm ap;
    final cpm aq;
    final cpm ar;
    final cpm as;
    final cpm at;
    final cpm au;
    final cpm av;
    final cpm aw;
    final cpm ax;
    final cpm ay;
    final cpm az;
    final cpm bA;
    final cpm bB;
    final cpm bC;
    final cpm bD;
    final cpm bE;
    final cpm bF;
    final cpm bG;
    final cpm bH;
    final cpm bI;
    final cpm bJ;
    final cpm bK;
    final cpm bL;
    final cpm bM;
    final cpm bN;
    final cpm bO;
    final cpm bP;
    cpm bQ;
    cpm bR;
    cpm bS;
    cpm bT;
    cpm bU;
    cpm bV;
    cpm bW;
    cpm bX;
    cpm bY;
    cpm bZ;
    final cpm ba;
    final cpm bb;
    final cpm bc;
    final cpm bd;
    final cpm be;
    final cpm bf;
    final cpm bg;
    final cpm bh;
    final cpm bi;
    final cpm bj;
    final cpm bk;
    final cpm bl;
    final cpm bm;
    final cpm bn;
    final cpm bo;
    final cpm bp;
    final cpm bq;
    final cpm br;
    final cpm bs;
    final cpm bt;
    final cpm bu;
    final cpm bv;
    final cpm bw;
    final cpm bx;
    final cpm by;
    final cpm bz;
    cpm cA;
    cpm cB;
    cpm cC;
    cpm cD;
    cpm cE;
    cpm cF;
    cpm cG;
    cpm cH;
    cpm cI;
    cpm cJ;
    cpm cK;
    cpm cL;
    cpm cM;
    cpm cN;
    cpm cO;
    cpm cP;
    cpm cQ;
    cpm cR;
    cpm cS;
    cpm cT;
    cpm cU;
    cpm cV;
    cpm cW;
    cpm cX;
    cpm cY;
    cpm cZ;
    cpm ca;
    cpm cb;
    cpm cc;
    cpm cd;
    cpm ce;
    cpm cf;
    cpm cg;
    cpm ch;
    cpm ci;
    cpm cj;
    cpm ck;
    cpm cl;
    cpm cm;
    cpm cn;
    cpm co;
    cpm cp;
    cpm cq;
    cpm cr;
    cpm cs;
    cpm ct;
    cpm cu;
    cpm cv;
    cpm cw;
    cpm cx;
    cpm cy;
    cpm cz;
    cpm dA;
    cpm dB;
    cpm dC;
    cpm dD;
    cpm dE;
    cpm dF;
    cpm dG;
    cpm dH;
    cpm dI;
    cpm dJ;
    cpm dK;
    cpm dL;
    cpm dM;
    cpm dN;
    cpm dO;
    cpm da;
    cpm db;
    cpm dc;
    cpm dd;
    cpm de;
    cpm df;
    cpm dg;
    cpm dh;
    cpm di;
    cpm dj;
    cpm dk;
    cpm dl;
    cpm dm;
    cpm dn;

    /* renamed from: do, reason: not valid java name */
    cpm f0do;
    cpm dp;
    cpm dq;
    cpm dr;
    cpm ds;
    cpm dt;
    cpm du;
    cpm dv;
    cpm dw;
    cpm dx;
    cpm dy;
    cpm dz;
    final cpm g;
    final cpm h;
    final cpm i;
    final cpm j;
    final cpm k;
    final cpm l;
    final cpm m;
    final cpm n;
    final cpm o;
    final cpm p;
    final cpm q;
    final cpm r;
    final cpm s;
    final cpm t;
    final cpm u;
    final cpm v;
    final cpm w;
    final cpm x;
    final cpm y;
    final cpm z;
    public final bnh b = this;
    final cpm c = new bng(this, 1);
    final cpm d = new bng(this, 0);
    final cpm e = new bng(this, 2);
    final cpm f = new bng(this, 3);

    public bnh(Context context) {
        this.a = context;
        cpm cpmVar = bnn.a;
        this.g = cpmVar;
        cpi cpiVarB = cpj.b(context);
        this.h = cpiVarB;
        cpm cpmVar2 = cpk.b;
        bds bdsVar = new bds(cpiVarB, cpmVar2);
        this.i = bdsVar;
        this.j = cpmVar;
        this.k = cpmVar;
        cpi cpiVar = cpo.a;
        axh axhVar = new axh((cpm) cpiVarB, (cpm) cpiVar, (cpm) cpiVar, cpmVar, (cpm) bdsVar, cpmVar, 4, (int[]) null);
        this.l = axhVar;
        bnl bnlVar = new bnl(azu.a, 1, null);
        this.m = bnlVar;
        this.n = cpmVar;
        this.o = cpmVar;
        this.p = cpmVar;
        this.q = cpmVar;
        this.r = cpmVar;
        azy azyVar = new azy(cpiVarB, cpmVar, cpmVar, cpmVar, cpmVar, cpmVar);
        this.s = azyVar;
        cpm cpmVarC = cph.c(new aum(cpiVarB, bnlVar, azyVar, 4, (int[]) null));
        this.t = cpmVarC;
        List listBl = dnx.bl(1);
        List listBl2 = dnx.bl(0);
        dnx.bi(cpmVarC, listBl);
        cpo cpoVar = new cpo(listBl, listBl2);
        this.u = cpoVar;
        cpm cpmVarB = cpp.b(new ari(cpoVar, 7));
        this.v = cpmVarB;
        this.w = cpmVar;
        cpm cpmVarC2 = cph.c(new apy(cpmVar, 4));
        this.x = cpmVarC2;
        cpm cpmVarC3 = cph.c(new ari(cpiVarB, 9));
        this.y = cpmVarC3;
        aul aulVar = new aul(cpmVarC3);
        this.z = aulVar;
        cpm cpmVarB2 = cpp.b(new aqt(cpiVarB, 15));
        this.A = cpmVarB2;
        aty atyVar = new aty(cpiVarB);
        this.B = atyVar;
        cpm cpmVarB3 = cpp.b(new aqs(cpiVarB, 0));
        this.C = cpmVarB3;
        cpm cpmVarB4 = cpp.b(new aqs(cpiVarB, 1));
        this.D = cpmVarB4;
        cpm cpmVarB5 = cpp.b(new apy(cpiVarB, 20));
        this.E = cpmVarB5;
        atx atxVar = new atx(atyVar, cpmVarB3, cpmVarB4, cpmVarB5);
        this.F = atxVar;
        cpm cpmVarC4 = cph.c(asc.a);
        this.G = cpmVarC4;
        bnl bnlVar2 = new bnl(cpmVarC4, 1, null);
        this.H = bnlVar2;
        this.I = cpmVar;
        this.J = cpmVar;
        cpm cpmVarB6 = cpp.b(new ari(cpiVarB, 1));
        this.K = cpmVarB6;
        cpm cpmVarC5 = cph.c(new axw(cpiVarB, cpmVarC2, aulVar, cpmVarB2, atxVar, bnlVar2, cpmVar, cpmVar, cpmVarB6, 1, null));
        this.L = cpmVarC5;
        cpm cpmVarC6 = cph.c(aqq.a);
        this.M = cpmVarC6;
        this.N = cpmVar;
        cpm cpmVarC7 = cph.c(new apy(cpmVar, 7));
        this.O = cpmVarC7;
        this.P = cpmVar;
        aow aowVar = new aow(cpmVar);
        this.Q = aowVar;
        cpm cpmVarC8 = cph.c(new aqd(cpmVarC7, aowVar, 2));
        this.R = cpmVarC8;
        cpm cpmVarB7 = cpp.b(new apy(cpiVarB, 11));
        this.S = cpmVarB7;
        cpm cpmVarC9 = cph.c(new ari(cpmVarB7, 4));
        this.T = cpmVarC9;
        cpm cpmVarC10 = cph.c(new ari(cpmVarC9, 5));
        this.U = cpmVarC10;
        cpm cpmVarC11 = cph.c(new aqd(cpiVarB, cpmVarC10, 5, null));
        this.V = cpmVarC11;
        this.W = cpmVar;
        cpm cpmVarC12 = cph.c(new aum(cpmVarC8, cpmVarC11, cpmVar, 1, (byte[]) null));
        this.X = cpmVarC12;
        this.Y = cpmVar;
        cpm cpmVarC13 = cph.c(new asr(cpmVarC12, cpmVarC8, cpmVarC7, cpmVar, 1, (byte[]) null));
        this.Z = cpmVarC13;
        this.aa = cpmVar;
        cpm cpmVarB8 = cpp.b(aou.a);
        this.ab = cpmVarB8;
        bnl bnlVar3 = new bnl(cpmVarB8, 1, null);
        this.ac = bnlVar3;
        cpm cpmVarB9 = cpp.b(new apy(bnlVar3, 14));
        this.ad = cpmVarB9;
        cpm cpmVarB10 = cpp.b(new apy(cpmVarB9, 12));
        this.ae = cpmVarB10;
        this.af = cpmVar;
        cpm cpmVarC14 = cph.c(new aqd(cpmVar, cpmVarB10, 15));
        this.ag = cpmVarC14;
        cpm cpmVarC15 = cph.c(new ari(cpmVarB9, 15));
        this.ah = cpmVarC15;
        cpm cpmVarC16 = cph.c(new asr(cpmVar, cpmVarB10, cpmVarC14, cpmVarC15, 3, (short[]) null));
        this.ai = cpmVarC16;
        this.aj = cpmVar;
        azc azcVar = new azc(cpmVarB9, cpmVar);
        this.ak = azcVar;
        axh axhVar2 = new axh((cpm) cpiVarB, cpmVarC13, cpmVarC16, (cpm) ayz.a, cpmVar, (cpm) azcVar, 3, (short[]) null);
        this.al = axhVar2;
        aug augVar = new aug(cpmVarB, cpmVarC5, cpmVarC6, axhVar2, cpmVarC2);
        this.am = augVar;
        cpm cpmVarB11 = cpp.b(new aqs(cpiVarB, 13));
        this.an = cpmVarB11;
        ara araVar = new ara(cpiVarB, cpmVarB11);
        this.ao = araVar;
        auk aukVar = new auk(cpmVarC3);
        this.ap = aukVar;
        cpm cpmVarC17 = cph.c(new ari(cpiVarB, 8));
        this.aq = cpmVarC17;
        cpm cpmVarB12 = cpp.b(new aqs(cpiVarB, 10));
        this.ar = cpmVarB12;
        cpm cpmVarB13 = cpp.b(new aqs(cpiVarB, 9));
        this.as = cpmVarB13;
        cpm cpmVarB14 = cpp.b(new aqt(cpiVarB, 4));
        this.at = cpmVarB14;
        cpm cpmVarB15 = cpp.b(new aqt(cpiVarB, 3));
        this.au = cpmVarB15;
        cpm cpmVarB16 = cpp.b(new aqs(cpiVarB, 12));
        this.av = cpmVarB16;
        cpm cpmVarB17 = cpp.b(new aqs(cpiVarB, 11));
        this.aw = cpmVarB17;
        cpm cpmVarB18 = cpp.b(new aqt(cpiVarB, 0));
        this.ax = cpmVarB18;
        cpm cpmVarB19 = cpp.b(new aqt(cpiVarB, 2));
        this.ay = cpmVarB19;
        cpm cpmVarB20 = cpp.b(new aqt(cpiVarB, 8));
        this.az = cpmVarB20;
        cpm cpmVarB21 = cpp.b(new aqt(cpiVarB, 6));
        this.aA = cpmVarB21;
        avr avrVar = new avr(cpiVarB, araVar, aulVar, aukVar, cpmVarC17, cpmVarB12, cpmVarB13, cpmVarB14, cpmVarB15, cpmVarB16, cpmVarB17, cpmVarB18, cpmVarB19, cpmVarB20, cpmVarB21);
        this.aB = avrVar;
        btk btkVar = new btk(cpiVarB, 2);
        this.aC = btkVar;
        bnl bnlVar4 = new bnl(btkVar, 1, null);
        this.aD = bnlVar4;
        ays aysVar = new ays(bnlVar4);
        this.aE = aysVar;
        cpm cpmVarC18 = cph.c(new aqd(cpiVarB, aysVar, 1, null));
        this.aF = cpmVarC18;
        this.aG = cpmVar;
        apy apyVar = new apy(cpmVar, 1);
        this.aH = apyVar;
        cpm cpmVarB22 = cpp.b(new aqt(cpiVarB, 17));
        this.aI = cpmVarB22;
        aqd aqdVar = new aqd(cpmVarB9, cpmVarB22, 3, null);
        this.aJ = aqdVar;
        ari ariVar = new ari(apyVar, 0);
        this.aK = ariVar;
        cpm cpmVarB23 = cpp.b(new aqs(cpiVarB, 17));
        this.aL = cpmVarB23;
        arm armVar = new arm(cpiVarB, aulVar, aukVar, cpmVarC17, cpmVarB23, 0);
        this.aM = armVar;
        List listBl3 = dnx.bl(3);
        List listBl4 = dnx.bl(0);
        dnx.bi(aqdVar, listBl3);
        dnx.bi(ariVar, listBl3);
        dnx.bi(armVar, listBl3);
        cpo cpoVar2 = new cpo(listBl3, listBl4);
        this.aN = cpoVar2;
        arb arbVar = new arb(cpiVarB);
        this.aO = arbVar;
        cpm cpmVarC19 = cph.c(new arm(cpmVarC13, (cpm) cpoVar2, (cpm) arbVar, cpmVarB9, cpmVarB22, 1, (byte[]) null));
        this.aP = cpmVarC19;
        cpm cpmVarB24 = cpp.b(new aqs(cpiVarB, 16));
        this.aQ = cpmVarB24;
        cpm cpmVarB25 = cpp.b(new aqt(cpiVarB, 7));
        this.aR = cpmVarB25;
        cpm cpmVarB26 = cpp.b(new aqt(cpiVarB, 5));
        this.aS = cpmVarB26;
        cpm cpmVarB27 = cpp.b(new aqs(cpiVarB, 3));
        this.aT = cpmVarB27;
        cpm cpmVarB28 = cpp.b(new aus(cpmVarC19, cpmVar, cpmVarB9, cpmVarB24, cpmVarB25, cpmVarB26, cpmVarB27, 1, (byte[]) null));
        this.aU = cpmVarB28;
        cpm cpmVarB29 = cpp.b(new aqs(cpiVarB, 15));
        this.aV = cpmVarB29;
        cpm cpmVarB30 = cpp.b(new aqt(cpiVarB, 12));
        this.aW = cpmVarB30;
        cpm cpmVarB31 = cpp.b(new aqt(cpiVarB, 13));
        this.aX = cpmVarB31;
        cpm cpmVarB32 = cpp.b(new axh(cpmVarB28, cpmVarC8, cpmVarB10, cpmVarB29, cpmVarB30, cpmVarB31, 1, (byte[]) null));
        this.aY = cpmVarB32;
        cpm cpmVarB33 = cpp.b(new apy(cpiVarB, 17));
        this.aZ = cpmVarB33;
        cpm cpmVarB34 = cpp.b(new apy(cpiVarB, 18));
        this.ba = cpmVarB34;
        cpm cpmVarB35 = cpp.b(new aqs(cpiVarB, 14));
        this.bb = cpmVarB35;
        cpm cpmVarC20 = cph.c(new axn(augVar, cpiVarB, cpmVarC13, avrVar, cpmVarC18, apyVar, cpmVarC19, cpmVarB32, cpmVarB33, cpmVarB34, cpmVarB35, 1, null));
        this.bc = cpmVarC20;
        ari ariVar2 = new ari(cpmVarC20, 11);
        this.bd = ariVar2;
        this.be = cpmVar;
        cpm cpmVarC21 = cph.c(new ari(cpiVarB, 6));
        this.bf = cpmVarC21;
        this.bg = cpmVar;
        asl aslVar = new asl(cpmVar);
        this.bh = aslVar;
        this.bi = cpmVar;
        ari ariVar3 = new ari(cpmVar, 3);
        this.bj = ariVar3;
        cpm cpmVarC22 = cph.c(new asr(cpmVarC11, cpmVarC21, aslVar, ariVar3, 0));
        this.bk = cpmVarC22;
        apx apxVar = new apx(cpmVar);
        this.bl = apxVar;
        ayt aytVar = new ayt(cpiVarB, cpmVarC18);
        this.bm = aytVar;
        atu atuVar = new atu(aytVar);
        this.bn = atuVar;
        atv atvVar = new atv(cpiVarB);
        this.bo = atvVar;
        cpm cpmVarC23 = cph.c(new arm((cpm) aulVar, (cpm) atvVar, cpmVarB9, (cpm) apxVar, (cpm) cpiVarB, 2, (char[]) null));
        this.bp = cpmVarC23;
        cpm cpmVarB36 = cpp.b(new aqs(cpiVarB, 2));
        this.bq = cpmVarB36;
        cpm cpmVarC24 = cph.c(new atj(augVar, cpiVarB, cpmVarC11, cpmVarC22, cpmVarC8, apxVar, atuVar, cpmVarC23, cpmVarB36, cpmVarC13));
        this.br = cpmVarC24;
        aqd aqdVar2 = new aqd(cpmVar, cpmVarC24, 7);
        this.bs = aqdVar2;
        this.bt = cpmVar;
        apy apyVar2 = new apy(cpmVar, 3);
        this.bu = apyVar2;
        this.bv = cpmVar;
        cpm cpmVarC25 = cph.c(new asr(augVar, apyVar2, cpmVar, cpmVarC13, 2, (char[]) null));
        this.bw = cpmVarC25;
        aqd aqdVar3 = new aqd(cpmVar, cpmVarC25, 10);
        this.bx = aqdVar3;
        this.by = cpmVar;
        apy apyVar3 = new apy(cpmVar, 5);
        this.bz = apyVar3;
        cpg cpgVar = new cpg();
        this.bA = cpgVar;
        this.bB = cpmVar;
        cpm cpmVarC26 = cph.c(new aum((cpm) cpgVar, cpmVar, cpmVarC13, 2, (byte[]) null));
        this.bC = cpmVarC26;
        awk awkVar = new awk(cpmVarB9);
        this.bD = awkVar;
        cpm cpmVarB37 = cpp.b(new aqs(cpiVarB, 20));
        this.bE = cpmVarB37;
        this.bF = cpmVar;
        cpm cpmVarC27 = cph.c(new ari(cpmVar, 12));
        this.bG = cpmVarC27;
        awz awzVar = new awz(cpmVarC27, cpmVarC8);
        this.bH = awzVar;
        cpm cpmVarB38 = cpp.b(new aqs(cpiVarB, 4));
        this.bI = cpmVarB38;
        awp awpVar = new awp(cpgVar, cpmVarC27);
        this.bJ = awpVar;
        cpm cpmVarB39 = cpp.b(new aqs(cpiVarB, 19));
        this.bK = cpmVarB39;
        cpm cpmVarB40 = cpp.b(new apy(cpmVarB9, 15));
        this.bL = cpmVarB40;
        cpm cpmVarC28 = cph.c(new ari(cpmVarB40, 10));
        this.bM = cpmVarC28;
        awr awrVar = new awr(cpiVarB, cpmVarB39, cpmVarC28, apyVar3);
        this.bN = awrVar;
        this.bO = cpmVar;
        cpm cpmVarB41 = cpp.b(new aqs(cpiVarB, 18));
        this.bP = cpmVarB41;
        cpm cpmVarC29 = cph.c(new awi(augVar, cpiVarB, cpmVarC11, apyVar3, cpmVarC26, awkVar, cpmVarB37, cpmVarC13, awzVar, cpmVarB38, awpVar, awrVar, cpmVar, cpmVarB41));
        if (cpgVar.a != null) {
            throw new IllegalStateException();
        }
        cpgVar.a = cpmVarC29;
        this.bQ = new aqd(cpmVar, cpgVar, 11);
        bto btoVar = new bto(cpiVarB);
        this.bR = btoVar;
        buj bujVar = new buj(cpiVarB, btoVar);
        this.bS = bujVar;
        btk btkVar2 = new btk(bujVar, 5);
        this.bT = btkVar2;
        bnl bnlVar5 = new bnl(btkVar2, 0);
        this.bU = bnlVar5;
        this.bV = new apy(bnlVar5, 2);
        this.bW = cpmVar;
        this.bX = new ayy(cpmVarB10);
        this.bY = cpp.b(new aqt(cpiVarB, 16));
        this.bZ = cpp.b(new aqs(cpiVarB, 7));
        this.ca = cpp.b(new aqs(cpiVarB, 6));
        this.cb = new auz(cpiVarB);
        auy auyVar = new auy(cpiVarB);
        this.cc = auyVar;
        cpm cpmVar3 = this.cb;
        cpm cpmVar4 = this.ca;
        avl avlVar = new avl(cpmVar3, auyVar, cpmVar4);
        this.cd = avlVar;
        cpm cpmVar5 = this.bV;
        this.ce = new ava(avlVar, cpmVar3, auyVar, cpmVarC13, cpmVar5, augVar, cpmVar4);
        asn asnVar = new asn(cpiVarB, cpmVarC22, aslVar);
        this.cf = asnVar;
        cpm cpmVarB42 = cpp.b(new aqd(asnVar, cpiVarB, 6));
        this.cg = cpmVarB42;
        this.ch = new avc(cpmVarB42, cpiVar);
        this.ci = cpp.b(new aqs(cpiVarB, 8));
        this.cj = cpp.b(new aqt(cpiVarB, 1));
        cpm cpmVarB43 = cpp.b(new apy(cpiVarB, 19));
        this.ck = cpmVarB43;
        avv avvVar = new avv(cpmVarB43);
        this.cl = avvVar;
        cpm cpmVarC30 = cph.c(new avh(augVar, cpmVarC13, cpmVar5, this.bW, cpmVarC11, cpmVarC22, this.bX, this.bY, this.bZ, cpmVar4, this.ce, this.ch, bnlVar2, this.ci, this.cj, avvVar));
        this.cm = cpmVarC30;
        this.cn = new aqd(bnlVar5, cpmVarC30, 9);
        this.co = cpmVar;
        apz apzVar = new apz(cpmVar);
        this.cp = apzVar;
        this.cq = new ari(apzVar, 13);
        cpm cpmVarB44 = cpp.b(new aqt(cpiVarB, 11));
        this.cr = cpmVarB44;
        cpm cpmVarC31 = cph.c(new axw(augVar, cpiVarB, cpmVarC22, cpmVarC8, apzVar, this.cq, cpmVarB44, cpmVarC13, cpmVarB42, 0));
        this.cs = cpmVarC31;
        this.ct = new aqd(cpmVar, cpmVarC31, 12);
        this.cu = cpmVar;
        this.cv = new apy(cpmVar, 0);
        this.cw = cpp.b(new aqs(cpiVarB, 5));
        cpm cpmVar6 = this.cv;
        aur aurVar = new aur(cpmVarB9, cpmVar6, cpiVarB);
        this.cx = aurVar;
        cpm cpmVarC32 = cph.c(new aus(augVar, cpiVarB, cpmVarC8, cpmVar6, this.cw, cpmVarB9, aurVar, 0));
        this.cy = cpmVarC32;
        this.cz = new aqd(cpmVar, cpmVarC32, 8);
        btk btkVar3 = new btk(this.bS, 6);
        this.cA = btkVar3;
        bnl bnlVar6 = new bnl(btkVar3, 0);
        this.cB = bnlVar6;
        this.cC = new apy(bnlVar6, 6);
        this.cD = new ayw(cpiVarB, cpmVarB9, cpmVarC18);
        cpm cpmVarB45 = cpp.b(new aqt(cpiVarB, 18));
        this.cE = cpmVarB45;
        cpm cpmVarC33 = cph.c(new aus(augVar, cpiVarB, cpmVarC22, cpmVarC13, this.cC, this.cD, cpmVarB45, 2, (char[]) null));
        this.cF = cpmVarC33;
        this.cG = new ari(cpmVarC33, 14);
        btk btkVar4 = new btk(this.bS, 7);
        this.cH = btkVar4;
        this.cI = new bnl(btkVar4, 0);
        this.cJ = cpmVar;
        this.cK = cpmVar;
        this.cL = new apy(cpmVar, 8);
        cpm cpmVar7 = this.cJ;
        this.cM = new apy(cpmVar7, 10);
        cpm cpmVarB46 = cpp.b(new aqt(cpiVarB, 20));
        this.cN = cpmVarB46;
        cpm cpmVar8 = this.cL;
        cpm cpmVar9 = this.cM;
        cpm cpmVar10 = this.bX;
        cpm cpmVarC34 = cph.c(new aus(augVar, cpmVarC8, cpmVar8, cpmVar9, cpmVarB46, cpmVar10, azcVar, 3, (short[]) null));
        this.cO = cpmVarC34;
        this.cP = new aym(cpmVar7, cpmVar, cpmVarC34);
        cpm cpmVar11 = this.cI;
        this.cQ = new apy(cpmVar11, 9);
        cpm cpmVarB47 = cpp.b(new aqt(cpiVarB, 19));
        this.cR = cpmVarB47;
        cpm cpmVarC35 = cph.c(new axh((cpm) augVar, cpmVarC13, this.cQ, cpmVarC2, cpmVarB47, cpmVar10, 2, (char[]) null));
        this.cS = cpmVarC35;
        cpm cpmVar12 = this.cP;
        cpm cpmVarC36 = cph.c(new aqd(cpmVarC35, cpmVar12, 14, null));
        this.cT = cpmVarC36;
        this.cU = new arm(cpmVar11, cpmVar7, cpmVar12, cpmVarC35, cpmVarC36, 4, (int[]) null);
        this.cV = new aum(cpmVar7, cpmVar, cpmVarC34, 3);
        btk btkVar5 = new btk(this.bS, 4);
        this.cW = btkVar5;
        bnl bnlVar7 = new bnl(btkVar5, 0);
        this.cX = bnlVar7;
        this.cY = new apy(bnlVar7, 16);
        cpm cpmVarB48 = cpp.b(new aqt(cpiVarB, 14));
        this.cZ = cpmVarB48;
        cpm cpmVar13 = this.cY;
        this.da = cph.c(new axh(cpmVarC22, cpmVarC8, cpmVarC13, cpmVar13, cpmVarB48, cpmVarB10, 0));
        cpm cpmVarB49 = cpp.b(new aqt(cpiVarB, 9));
        this.db = cpmVarB49;
        this.dc = cph.c(new arm(cpmVar13, (cpm) cpiVarB, cpmVarB2, cpmVarB49, this.cg, 3, (short[]) null));
        cpm cpmVarB50 = cpp.b(new aqt(cpiVarB, 10));
        this.dd = cpmVarB50;
        this.de = cpmVar;
        this.df = cph.c(new axn(augVar, cpmVarB9, cpiVarB, this.da, cpmVarC8, cpmVar13, this.dc, cpmVarC6, cpmVarB50, cpmVarC13, cpmVar, 0));
        this.dg = new aqd(cpmVarC22, cpmVarC2, 13, null);
        List listBl5 = dnx.bl(2);
        List listBl6 = dnx.bl(10);
        dnx.bh(ariVar2, listBl6);
        dnx.bh(aqdVar2, listBl6);
        dnx.bh(aqdVar3, listBl6);
        dnx.bh(this.bQ, listBl6);
        dnx.bh(this.cn, listBl6);
        dnx.bh(this.ct, listBl6);
        dnx.bh(this.cz, listBl6);
        dnx.bh(this.cG, listBl6);
        dnx.bh(this.cU, listBl6);
        dnx.bh(this.cV, listBl6);
        dnx.bi(this.df, listBl5);
        dnx.bi(this.dg, listBl5);
        this.dh = new cpo(listBl5, listBl6);
        this.di = new bnl(this.cm, 0);
        this.dj = cpmVar;
        bnl bnlVar8 = new bnl(this.df, 0);
        this.dk = bnlVar8;
        ast astVar = new ast(this.di, this.dj, bnlVar8);
        this.dl = astVar;
        this.dm = new aum(this.dh, astVar, this.de, 0);
        LinkedHashMap linkedHashMapBk = dnx.bk(2);
        dnx.bm("ActivityLifecycleCallbacks", axhVar, linkedHashMapBk);
        dnx.bm("PrimesMetricServices", this.dm, linkedHashMapBk);
        cpl cplVar = new cpl(linkedHashMapBk);
        this.dn = cplVar;
        this.f0do = new aum(bdsVar, cpmVar2, cplVar, 5, (int[]) null);
        this.dp = cpmVar;
        cpm cpmVarC37 = cph.c(new aqd(cpmVarC4, cpmVar, 4));
        this.dq = cpmVarC37;
        this.dr = cph.c(new ari(cpmVarC37, 2));
        List listBl7 = dnx.bl(2);
        List listBl8 = dnx.bl(0);
        dnx.bi(btu.a, listBl7);
        dnx.bi(this.dr, listBl7);
        cpo cpoVar3 = new cpo(listBl7, listBl8);
        this.ds = cpoVar3;
        cjy cjyVar = new cjy(cpoVar3);
        this.dt = cjyVar;
        this.du = cpmVar;
        this.dv = new bsj(cjyVar, cpmVar, 9);
        this.dw = new aqd(cpiVar, cpmVarB8, 17);
        LinkedHashMap linkedHashMapBk2 = dnx.bk(3);
        dnx.bm(bdt.STARTUP_LISTENERS, this.f0do, linkedHashMapBk2);
        dnx.bm(bdt.LOGGING, this.dv, linkedHashMapBk2);
        dnx.bm(bdt.UNCAUGHT_EXCEPTION_HANDLER, this.dw, linkedHashMapBk2);
        cpk cpkVar = new cpk(linkedHashMapBk2);
        this.dx = cpkVar;
        this.dy = cph.c(new aqd(cpmVar, cpkVar, 16, null));
        aqj aqjVar = new aqj(cpmVarC6, this.dh, this.df, this.de, this.dl);
        this.dz = aqjVar;
        cpm cpmVarC38 = cph.c(new aqd(aqjVar, cpmVarB7, 0));
        this.dA = cpmVarC38;
        cpm cpmVarC39 = cph.c(new apy(cpmVarC38, 13));
        this.dB = cpmVarC39;
        this.dC = cph.c(new btk(cpmVarC39, 3));
        cpm cpmVarC40 = cph.c(bmo.a);
        this.dD = cpmVarC40;
        this.dE = cph.c(new bsj(cpiVarB, cpmVarC40, 0));
        this.dF = cph.c(bmp.a);
        cpm cpmVar14 = this.bS;
        this.dG = cph.c(new btk(cpmVar14, 8));
        this.dH = cph.c(bsu.a);
        this.dI = cph.c(new ari(cpiVarB, 20));
        this.dJ = cph.c(new bsj(cpiVarB, cpmVar14, 6));
        cpm cpmVarC41 = cph.c(new bsj(cpiVarB, cpmVar14, 7));
        this.dK = cpmVarC41;
        this.dL = cph.c(new bsj(cpmVar14, cpmVarC41, 8, null));
        this.dM = cph.c(new bsj(cpiVarB, cpmVar14, 3));
        this.dN = cph.c(new bsj(cpiVarB, cpmVar14, 5));
        this.dO = cph.c(new bsj(cpiVarB, cpmVar14, 4));
    }

    final cpc a() {
        cpm cpmVar = this.c;
        bzw bzwVar = cbc.a;
        bit.g("com.google.android.tv.remote.service.AtvRemoteProviderService", cpmVar);
        cpm cpmVar2 = this.d;
        bit.g("com.google.android.tv.remote.service.DiscoveryService", cpmVar2);
        cpm cpmVar3 = this.e;
        bit.g("com.google.android.tv.remote.service.RemoteService", cpmVar3);
        cpm cpmVar4 = this.f;
        bit.g("com.google.android.tv.remote.service.pairing.PairingCodeActivity", cpmVar4);
        return new cpc(bzwVar, cbc.g(4, new Object[]{"com.google.android.tv.remote.service.AtvRemoteProviderService", cpmVar, "com.google.android.tv.remote.service.DiscoveryService", cpmVar2, "com.google.android.tv.remote.service.RemoteService", cpmVar3, "com.google.android.tv.remote.service.pairing.PairingCodeActivity", cpmVar4}));
    }

    @Override // defpackage.cox
    public final /* synthetic */ void b(Object obj) {
        AtvRemoteServiceApplication atvRemoteServiceApplication = (AtvRemoteServiceApplication) obj;
        atvRemoteServiceApplication.d = a();
        atvRemoteServiceApplication.a = this.dy;
        atvRemoteServiceApplication.b = this.dC;
        atvRemoteServiceApplication.c = this.dE;
    }
}
