package defpackage;

import android.os.HandlerThread;
import com.google.android.tv.remote.service.RemoteService;
import j$.util.Optional;
import java.util.List;

/* compiled from: PG */
/* loaded from: classes.dex */
final class bnm implements cox {
    final cpm A;
    final cpm B;
    final cpm C;
    final cpm D;
    final bzt E;
    final bzt F;
    final bzt G;
    final bzt H;
    private final bnh I;
    final cpm a;
    final cpm b;
    final cpm c;
    final cpm d;
    final cpm e;
    final cpm f;
    final cpm g;
    final cpm h;
    final cpm i;
    final cpm j;
    final cpm k;
    final cpm l;
    final cpm m;
    final cpm n;
    final cpm o;
    final cpm p;
    final cpm q;
    final cpm r;
    final cpm s;
    final cpm t;
    final cpm u;
    final cpm v;
    final cpm w;
    final cpm x;
    final cpm y;
    final cpm z;

    public bnm(bnh bnhVar, RemoteService remoteService) {
        this.I = bnhVar;
        cpm cpmVarC = cph.c(bpj.a);
        this.a = cpmVarC;
        cpi cpiVarB = cpj.b(remoteService);
        this.b = cpiVarB;
        cpm cpmVar = bnhVar.bS;
        cpm cpmVar2 = bnhVar.dE;
        this.c = cph.c(new aum((cpm) cpiVarB, cpmVar, cpmVar2, 6, (byte[]) null));
        cpm cpmVarC2 = cph.c(new aqr(8));
        this.d = cpmVarC2;
        bqt bqtVar = new bqt(cpiVarB, cpmVar2);
        this.e = bqtVar;
        brc brcVar = new brc(cpiVarB);
        this.f = brcVar;
        cpm cpmVarC3 = cph.c(new aum(cpiVarB, bqtVar, brcVar, 7, (byte[][]) null));
        this.g = cpmVarC3;
        this.h = cph.c(new arm(bnhVar.dH, (cpm) cpiVarB, cpmVar2, cpmVarC2, cpmVarC3, 5, (byte[]) null));
        cpm cpmVarC4 = cph.c(new btk(cpiVarB, 0));
        this.i = cpmVarC4;
        cpm cpmVar3 = bnhVar.dI;
        cpm cpmVarC5 = cph.c(new axh(cpiVarB, cpmVar2, cpmVarC3, cpmVarC4, cpmVar3, bnhVar.dJ, 6, (float[]) null));
        this.j = cpmVarC5;
        cpm cpmVarC6 = cph.c(new btk(cpiVarB, 1));
        this.k = cpmVarC6;
        brq brqVar = new brq(cpiVarB, cpmVarC2, cpmVar2, cpmVarC5, cpmVarC4, cpmVarC6, cpmVar3, bnhVar.dK, bnhVar.dL);
        this.l = brqVar;
        bsj bsjVar = new bsj(cpiVarB, brqVar, 1, null);
        this.m = bsjVar;
        this.n = cph.c(bsjVar);
        bzt bztVar = new bzt(bnhVar.h, (cpm) cpiVarB, cpmVar2);
        this.F = bztVar;
        this.o = cpj.b(new adx(bztVar, (byte[]) null));
        bzt bztVar2 = new bzt(bnhVar.h, (cpm) cpiVarB, bnhVar.dE);
        this.E = bztVar2;
        this.p = cpj.b(new adx(bztVar2, (byte[]) null));
        bzt bztVar3 = new bzt((Object) cpiVarB, (Object) bnhVar.dM, (Object) bnhVar.dN);
        this.G = bztVar3;
        this.q = cpj.b(new att(bztVar3));
        bzt bztVar4 = new bzt((Object) cpiVarB, (Object) bnhVar.dN, (Object) bnhVar.dF);
        this.H = bztVar4;
        this.r = cpj.b(new att(bztVar4));
        bpk bpkVar = new bpk(cpmVarC);
        this.s = bpkVar;
        cpm cpmVar4 = bnhVar.dE;
        aqd aqdVar = new aqd(cpmVar4, bpkVar, 19);
        this.t = aqdVar;
        bpi bpiVar = new bpi(bpkVar);
        this.u = bpiVar;
        aqd aqdVar2 = new aqd(cpiVarB, bpiVar, 18);
        this.v = aqdVar2;
        axh axhVar = new axh(cpiVarB, cpmVar4, cpmVarC2, bnhVar.dI, cpmVarC5, bnhVar.dL, 5, (boolean[]) null);
        this.w = axhVar;
        cpm cpmVarC7 = cph.c(new ari(cpiVarB, 18));
        this.x = cpmVarC7;
        aqd aqdVar3 = new aqd(cpiVarB, bpiVar, 20, null);
        this.y = aqdVar3;
        ari ariVar = new ari(cpiVarB, 19);
        this.z = ariVar;
        ari ariVar2 = new ari(cpiVarB, 16);
        this.A = ariVar2;
        ari ariVar3 = new ari(cpiVarB, 17);
        this.B = ariVar3;
        cpi cpiVar = cpo.a;
        List listBl = dnx.bl(8);
        List listBl2 = dnx.bl(0);
        dnx.bi(aqdVar, listBl);
        dnx.bi(aqdVar2, listBl);
        dnx.bi(axhVar, listBl);
        dnx.bi(cpmVarC7, listBl);
        dnx.bi(aqdVar3, listBl);
        dnx.bi(ariVar, listBl);
        dnx.bi(ariVar2, listBl);
        dnx.bi(ariVar3, listBl);
        cpo cpoVar = new cpo(listBl, listBl2);
        this.C = cpoVar;
        this.D = cph.c(new bsj(bnhVar.dE, cpoVar, 2));
    }

    @Override // defpackage.cox
    public final /* synthetic */ void b(Object obj) {
        RemoteService remoteService = (RemoteService) obj;
        remoteService.e = bpk.c((HandlerThread) this.a.a());
        bnh bnhVar = this.I;
        remoteService.f = ((Boolean) bnhVar.dD.a()).booleanValue();
        remoteService.g = this.c;
        remoteService.u = (bsi) bnhVar.dE.a();
        remoteService.h = (bqo) this.d.a();
        remoteService.i = (bqw) this.h.a();
        remoteService.j = new cbf((brj) this.n.a());
        remoteService.y = (adx) ((cpj) this.o).a;
        remoteService.x = (adx) ((cpj) this.p).a;
        remoteService.v = (att) ((cpj) this.q).a;
        remoteService.w = (att) ((cpj) this.r).a;
        remoteService.k = Optional.empty();
        remoteService.l = (bsz) this.D.a();
        remoteService.m = (bny) this.x.a();
        remoteService.n = this.j;
        remoteService.o = this.i;
        remoteService.p = this.k;
        remoteService.q = bnhVar.dI;
        remoteService.r = ((Boolean) bnhVar.dO.a()).booleanValue();
        remoteService.s = ((Boolean) bnhVar.dG.a()).booleanValue();
    }
}
