package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public interface dcg {
    public static final czv a;
    public static final czv b;
    public static final czv c;
    public static final czv d;
    public static final czv e;
    public static final czv f;
    public static final czv g;
    public static final czv h;
    public static final czv i;
    public static final czv j;
    public static final czv k;
    public static final czv l;
    public static final czv m;
    public static final czv n;
    public static final czv o;
    public static final czv p;
    public static final czv q;
    public static final czv r;
    public static final czv s;
    public static final czv t;
    public static final czv u;

    static {
        czv czvVar = new czv("2.16.840.1.101.3.4");
        a = czvVar;
        czv czvVarF = czvVar.f("2");
        b = czvVarF;
        c = czvVarF.f("1");
        d = czvVarF.f("2");
        e = czvVarF.f("3");
        f = czvVarF.f("4");
        g = czvVarF.f("5");
        h = czvVarF.f("6");
        i = czvVarF.f("7");
        j = czvVarF.f("8");
        k = czvVarF.f("9");
        l = czvVarF.f("10");
        m = czvVarF.f("11");
        n = czvVarF.f("12");
        czvVarF.f("13");
        czvVarF.f("14");
        czvVarF.f("15");
        czvVarF.f("16");
        czvVarF.f("17");
        o = czvVarF.f("18");
        czvVarF.f("19");
        czvVarF.f("20");
        czv czvVarF2 = czvVar.f("1");
        p = czvVarF2;
        czvVarF2.f("1");
        czvVarF2.f("2");
        czvVarF2.f("3");
        czvVarF2.f("4");
        czvVarF2.f("5");
        czvVarF2.f("6");
        czvVarF2.f("7");
        czvVarF2.f("8");
        czvVarF2.f("9");
        czvVarF2.f("21");
        czvVarF2.f("22");
        czvVarF2.f("23");
        czvVarF2.f("24");
        czvVarF2.f("25");
        czvVarF2.f("26");
        czvVarF2.f("27");
        czvVarF2.f("28");
        czvVarF2.f("29");
        czvVarF2.f("41");
        czvVarF2.f("42");
        czvVarF2.f("43");
        czvVarF2.f("44");
        czvVarF2.f("45");
        czvVarF2.f("46");
        czvVarF2.f("47");
        czvVarF2.f("48");
        czvVarF2.f("49");
        czv czvVarF3 = czvVar.f("3");
        q = czvVarF3;
        r = czvVarF3.f("1");
        s = czvVarF3.f("2");
        t = czvVarF3.f("3");
        u = czvVarF3.f("4");
        czvVarF3.f("5");
        czvVarF3.f("6");
        czvVarF3.f("7");
        czvVarF3.f("8");
        czvVarF3.f("9");
        czvVarF3.f("10");
        czvVarF3.f("11");
        czvVarF3.f("12");
        czvVarF3.f("13");
        czvVarF3.f("14");
        czvVarF3.f("15");
        czvVarF3.f("16");
    }
}
