package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public interface deb {
    public static final czv a;
    public static final czv b;
    public static final czv c;
    public static final czv d;
    public static final czv e;
    public static final czv f;
    public static final czv g;
    public static final czv h;
    public static final czv i;
    public static final czv j;
    public static final czv k;
    public static final czv l;
    public static final czv m;
    public static final czv n;
    public static final czv o;
    public static final czv p;
    public static final czv q;
    public static final czv r;
    public static final czv s;
    public static final czv t;

    static {
        czv czvVar = new czv("1.2.840.10045");
        a = czvVar;
        czv czvVarF = czvVar.f("1");
        b = czvVarF;
        czvVarF.f("1");
        czv czvVarF2 = czvVarF.f("2");
        c = czvVarF2;
        czvVarF2.f("3.1");
        czvVarF2.f("3.2");
        czvVarF2.f("3.3");
        czv czvVarF3 = czvVar.f("4");
        d = czvVarF3;
        e = czvVarF3.f("1");
        czv czvVarF4 = czvVar.f("2");
        f = czvVarF4;
        czvVarF4.f("1");
        czv czvVarF5 = czvVarF3.f("3");
        g = czvVarF5;
        h = czvVarF5.f("1");
        i = czvVarF5.f("2");
        j = czvVarF5.f("3");
        k = czvVarF5.f("4");
        czv czvVarF6 = czvVar.f("3");
        l = czvVarF6;
        czv czvVarF7 = czvVarF6.f("0");
        m = czvVarF7;
        czvVarF7.f("1");
        czvVarF7.f("2");
        czvVarF7.f("3");
        czvVarF7.f("4");
        czvVarF7.f("5");
        czvVarF7.f("6");
        czvVarF7.f("7");
        czvVarF7.f("8");
        czvVarF7.f("9");
        czvVarF7.f("10");
        czvVarF7.f("11");
        czvVarF7.f("12");
        czvVarF7.f("13");
        czvVarF7.f("14");
        czvVarF7.f("15");
        czvVarF7.f("16");
        czvVarF7.f("17");
        czvVarF7.f("18");
        czvVarF7.f("19");
        czvVarF7.f("20");
        czv czvVarF8 = czvVarF6.f("1");
        n = czvVarF8;
        czvVarF8.f("1");
        czvVarF8.f("2");
        czvVarF8.f("3");
        czvVarF8.f("4");
        czvVarF8.f("5");
        czvVarF8.f("6");
        czvVarF8.f("7");
        new czv("1.2.840.10040.4.1");
        o = new czv("1.2.840.10040.4.3");
        czv czvVar2 = new czv("1.3.133.16.840.63.0");
        p = czvVar2;
        czvVar2.f("2");
        czvVar2.f("3");
        czvVar2.f("16");
        czv czvVar3 = new czv("1.2.840.10046");
        q = czvVar3;
        czvVar3.f("2.1");
        czv czvVarF9 = czvVar3.f("3");
        r = czvVarF9;
        czvVarF9.f("1");
        czvVarF9.f("2");
        czvVarF9.f("3");
        czvVarF9.f("4");
        czvVarF9.f("5");
        czvVarF9.f("6");
        czvVarF9.f("7");
        czvVarF9.f("8");
        czv czvVar4 = new czv("1.3.133.16.840.9.44");
        s = czvVar4;
        czv czvVarF10 = czvVar4.f("1");
        t = czvVarF10;
        czvVarF10.f("1");
        czvVarF10.f("2");
    }
}
