package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class ad {
    public int b;
    public int c;
    int d;
    public boolean a = false;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    public int ad = -1;
    public int ae = -1;
    public int af = -1;
    public int ag = -1;
    public int ah = -1;
    public int ai = -1;

    public final void a(ac acVar) {
        acVar.d = this.h;
        acVar.e = this.i;
        acVar.f = this.j;
        acVar.g = this.k;
        acVar.h = this.l;
        acVar.i = this.m;
        acVar.j = this.n;
        acVar.k = this.o;
        acVar.l = this.p;
        acVar.m = this.q;
        acVar.n = this.r;
        acVar.o = this.s;
        acVar.p = this.t;
        acVar.leftMargin = this.A;
        acVar.rightMargin = this.B;
        acVar.topMargin = this.C;
        acVar.bottomMargin = this.D;
        acVar.u = this.M;
        acVar.v = this.L;
        acVar.w = this.u;
        acVar.x = this.v;
        acVar.y = this.w;
        acVar.K = this.x;
        acVar.L = this.y;
        acVar.B = this.N;
        acVar.A = this.O;
        acVar.D = this.Q;
        acVar.C = this.P;
        acVar.E = this.ad;
        acVar.F = this.ae;
        acVar.I = this.af;
        acVar.J = this.ag;
        acVar.G = this.ah;
        acVar.H = this.ai;
        acVar.M = this.z;
        acVar.c = this.g;
        acVar.a = this.e;
        acVar.b = this.f;
        acVar.width = this.b;
        acVar.height = this.c;
        acVar.setMarginStart(this.F);
        acVar.setMarginEnd(this.E);
        acVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        ad adVar = new ad();
        adVar.a = this.a;
        adVar.b = this.b;
        adVar.c = this.c;
        adVar.e = this.e;
        adVar.f = this.f;
        adVar.g = this.g;
        adVar.h = this.h;
        adVar.i = this.i;
        adVar.j = this.j;
        adVar.k = this.k;
        adVar.l = this.l;
        adVar.m = this.m;
        adVar.n = this.n;
        adVar.o = this.o;
        adVar.p = this.p;
        adVar.q = this.q;
        adVar.r = this.r;
        adVar.s = this.s;
        adVar.t = this.t;
        adVar.u = this.u;
        adVar.v = this.v;
        adVar.w = this.w;
        adVar.x = this.x;
        adVar.y = this.y;
        adVar.u = this.u;
        adVar.u = this.u;
        adVar.u = this.u;
        adVar.u = this.u;
        adVar.u = this.u;
        adVar.z = this.z;
        adVar.A = this.A;
        adVar.B = this.B;
        adVar.C = this.C;
        adVar.D = this.D;
        adVar.E = this.E;
        adVar.F = this.F;
        adVar.G = this.G;
        adVar.H = this.H;
        adVar.I = this.I;
        adVar.J = this.J;
        adVar.K = this.K;
        adVar.L = this.L;
        adVar.M = this.M;
        adVar.N = this.N;
        adVar.O = this.O;
        adVar.P = this.P;
        adVar.Q = this.Q;
        adVar.R = this.R;
        adVar.S = this.S;
        adVar.T = this.T;
        adVar.U = this.U;
        adVar.V = this.V;
        adVar.W = this.W;
        adVar.X = this.X;
        adVar.Y = this.Y;
        adVar.Z = this.Z;
        adVar.aa = this.aa;
        adVar.ab = this.ab;
        adVar.ac = this.ac;
        adVar.ad = this.ad;
        adVar.ae = this.ae;
        adVar.af = this.af;
        adVar.ag = this.ag;
        adVar.ah = this.ah;
        adVar.ai = this.ai;
        return adVar;
    }
}
