package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class azn {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = azq.a;
        long j3 = azq.q;
        a = j3;
        b = azq.f;
        c = azq.d;
        d = azq.m;
        e = azq.H;
        long j4 = azq.s;
        f = j4;
        g = j4;
        h = azq.c;
        i = azq.g;
        j = azq.F;
        long j5 = azq.J;
        k = j5;
        l = azq.D;
        long j6 = azq.G;
        m = j6;
        n = azq.M;
        long j7 = azq.Q;
        o = j7;
        p = azq.K;
        long j8 = azq.N;
        q = j8;
        r = j4;
        s = azq.B;
        t = azq.T;
        long j9 = azq.X;
        u = j9;
        v = azq.R;
        long j10 = azq.U;
        w = j10;
        x = azq.A;
        long j11 = azq.y;
        y = j11;
        long j12 = azq.I;
        z = j12;
        A = j6;
        B = j5;
        C = j12;
        D = azq.h;
        long j13 = azq.P;
        E = j13;
        F = j8;
        G = j7;
        H = j13;
        I = j3;
        J = azq.o;
        K = azq.k;
        L = azq.l;
        M = azq.n;
        N = azq.i;
        O = azq.p;
        P = j3;
        Q = j11;
        long j14 = azq.W;
        R = j14;
        S = j10;
        T = j9;
        U = j14;
    }
}
