package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class azo {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = azq.a;
        long j3 = azq.x;
        a = j3;
        b = azq.e;
        c = azq.g;
        d = azq.v;
        long j4 = azq.I;
        e = j4;
        f = azq.m;
        long j5 = azq.i;
        g = j5;
        h = azq.b;
        i = azq.a;
        j = azq.E;
        long j6 = azq.D;
        k = j6;
        l = j6;
        m = azq.G;
        n = azq.L;
        long j7 = azq.K;
        o = j7;
        p = j7;
        q = azq.N;
        r = j5;
        s = azq.y;
        t = azq.S;
        long j8 = azq.R;
        u = j8;
        v = j8;
        w = azq.U;
        x = azq.z;
        y = azq.B;
        z = azq.H;
        long j9 = azq.J;
        A = j9;
        B = j9;
        C = j4;
        D = azq.h;
        E = azq.O;
        long j10 = azq.Q;
        F = j10;
        G = j10;
        H = azq.P;
        I = j3;
        J = j3;
        K = azq.u;
        L = azq.t;
        M = azq.s;
        N = azq.w;
        O = azq.j;
        P = azq.r;
        Q = azq.C;
        R = azq.V;
        long j11 = azq.X;
        S = j11;
        T = j11;
        U = azq.W;
    }
}
