package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class azx {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final cji D;
    public static final cjk E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final cji I;
    public static final cjk J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final cji N;
    public static final cjk O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final cji S;
    public static final cjk T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final cji X;
    public static final cjk Y;
    public static final long Z;
    public static final cjk a;
    public static final long aA;
    public static final cji aB;
    public static final cjk aC;
    public static final long aD;
    public static final long aE;
    public static final long aF;
    public static final cji aG;
    public static final cjk aH;
    public static final long aI;
    public static final long aJ;
    public static final long aK;
    public static final cji aL;
    public static final cjk aM;
    public static final long aN;
    public static final long aO;
    public static final long aP;
    public static final cji aQ;
    public static final cjk aR;
    public static final long aS;
    public static final long aT;
    public static final long aU;
    public static final cji aV;
    public static final cjk aW;
    public static final long aX;
    public static final long aY;
    public static final long aZ;
    public static final long aa;
    public static final long ab;
    public static final cji ac;
    public static final cjk ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final cji ah;
    public static final cjk ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final cji am;
    public static final cjk an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final cji ar;
    public static final cjk as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final cji aw;
    public static final cjk ax;
    public static final long ay;
    public static final long az;
    public static final long b;
    public static final cjk bA;
    public static final long bB;
    public static final long bC;
    public static final long bD;
    public static final cji bE;
    public static final cjk bF;
    public static final long bG;
    public static final long bH;
    public static final long bI;
    public static final cji bJ;
    public static final cjk bK;
    public static final long bL;
    public static final long bM;
    public static final long bN;
    public static final cji bO;
    public static final cjk bP;
    public static final long bQ;
    public static final long bR;
    public static final long bS;
    public static final cji bT;
    public static final cji ba;
    public static final cjk bb;
    public static final long bc;
    public static final long bd;
    public static final long be;
    public static final cji bf;
    public static final cjk bg;
    public static final long bh;
    public static final long bi;
    public static final long bj;
    public static final cji bk;
    public static final cjk bl;
    public static final long bm;
    public static final long bn;
    public static final long bo;
    public static final cji bp;
    public static final cjk bq;
    public static final long br;
    public static final long bs;
    public static final long bt;
    public static final cji bu;
    public static final cjk bv;
    public static final long bw;
    public static final long bx;
    public static final long by;
    public static final cji bz;
    public static final long c;
    public static final long d;
    public static final cji e;
    public static final cjk f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final cji j;
    public static final cjk k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final cji o;
    public static final cjk p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final cji t;
    public static final cjk u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final cji y;
    public static final cjk z;

    static {
        cjk cjkVar = azy.a;
        a = azy.b;
        b = clw.t(24.0d);
        c = clw.v(16);
        d = clw.t(0.5d);
        e = azy.e;
        f = azy.b;
        g = clw.t(20.0d);
        h = clw.v(14);
        i = clw.t(0.2d);
        j = azy.e;
        k = azy.b;
        l = clw.t(16.0d);
        m = clw.v(12);
        n = clw.t(0.4d);
        o = azy.e;
        p = azy.a;
        q = clw.t(64.0d);
        r = clw.v(57);
        long jT = clw.t(0.2d);
        if (cmk.b(jT) == 0) {
            cme.a("Cannot perform operation for Unspecified type.");
        }
        s = clw.w(cmk.b(jT), -cmk.a(jT));
        t = azy.e;
        u = azy.a;
        v = clw.t(52.0d);
        w = clw.v(45);
        x = clw.t(0.0d);
        y = azy.e;
        z = azy.a;
        A = clw.t(44.0d);
        B = clw.v(36);
        C = clw.t(0.0d);
        D = azy.e;
        E = azy.a;
        F = clw.t(40.0d);
        G = clw.v(32);
        H = clw.t(0.0d);
        I = azy.e;
        J = azy.a;
        K = clw.t(36.0d);
        L = clw.v(28);
        M = clw.t(0.0d);
        N = azy.e;
        O = azy.a;
        P = clw.t(32.0d);
        Q = clw.v(24);
        R = clw.t(0.0d);
        S = azy.e;
        T = azy.b;
        U = clw.t(20.0d);
        V = clw.v(14);
        W = clw.t(0.1d);
        X = azy.d;
        Y = azy.b;
        Z = clw.t(16.0d);
        aa = clw.v(12);
        ab = clw.t(0.5d);
        ac = azy.d;
        ad = azy.b;
        ae = clw.t(16.0d);
        af = clw.v(11);
        ag = clw.t(0.5d);
        ah = azy.d;
        ai = azy.a;
        aj = clw.t(28.0d);
        ak = clw.v(22);
        al = clw.t(0.0d);
        am = azy.e;
        an = azy.b;
        ao = clw.t(24.0d);
        ap = clw.v(16);
        aq = clw.t(0.2d);
        ar = azy.d;
        as = azy.b;
        at = clw.t(20.0d);
        au = clw.v(14);
        av = clw.t(0.1d);
        aw = azy.d;
        ax = azy.b;
        ay = clw.t(24.0d);
        az = clw.v(16);
        aA = clw.t(0.15d);
        aB = azy.d;
        aC = azy.b;
        aD = clw.t(20.0d);
        aE = clw.v(14);
        aF = clw.t(0.25d);
        aG = azy.d;
        aH = azy.b;
        aI = clw.t(16.0d);
        aJ = clw.v(12);
        aK = clw.t(0.4d);
        aL = azy.d;
        aM = azy.a;
        aN = clw.t(64.0d);
        aO = clw.v(57);
        aP = clw.v(0);
        aQ = azy.d;
        aR = azy.a;
        aS = clw.t(52.0d);
        aT = clw.v(45);
        aU = clw.v(0);
        aV = azy.d;
        aW = azy.a;
        aX = clw.t(44.0d);
        aY = clw.v(36);
        aZ = clw.v(0);
        ba = azy.d;
        bb = azy.a;
        bc = clw.t(40.0d);
        bd = clw.v(32);
        be = clw.v(0);
        bf = azy.d;
        bg = azy.a;
        bh = clw.t(36.0d);
        bi = clw.v(28);
        bj = clw.v(0);
        bk = azy.d;
        bl = azy.a;
        bm = clw.t(32.0d);
        bn = clw.v(24);
        bo = clw.v(0);
        bp = azy.d;
        bq = azy.b;
        br = clw.t(20.0d);
        bs = clw.v(14);
        bt = clw.t(0.1d);
        bu = azy.c;
        bv = azy.b;
        bw = clw.t(16.0d);
        bx = clw.v(12);
        by = clw.t(0.5d);
        bz = azy.c;
        bA = azy.b;
        bB = clw.t(16.0d);
        bC = clw.v(11);
        bD = clw.t(0.5d);
        bE = azy.c;
        bF = azy.a;
        bG = clw.t(28.0d);
        bH = clw.v(22);
        bI = clw.v(0);
        bJ = azy.d;
        bK = azy.b;
        bL = clw.t(24.0d);
        bM = clw.v(16);
        bN = clw.t(0.15d);
        bO = azy.c;
        bP = azy.b;
        bQ = clw.t(20.0d);
        bR = clw.v(14);
        bS = clw.t(0.1d);
        bT = azy.c;
    }
}
