package defpackage;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class azz {
    public static final chc A;
    public static final chc B;
    public static final chc C;
    public static final chc D;
    public static final chc a;
    public static final chc b;
    public static final chc c;
    public static final chc d;
    public static final chc e;
    public static final chc f;
    public static final chc g;
    public static final chc h;
    public static final chc i;
    public static final chc j;
    public static final chc k;
    public static final chc l;
    public static final chc m;
    public static final chc n;
    public static final chc o;
    public static final chc p;
    public static final chc q;
    public static final chc r;
    public static final chc s;
    public static final chc t;
    public static final chc u;
    public static final chc v;
    public static final chc w;
    public static final chc x;
    public static final chc y;
    public static final chc z;

    static {
        chc chcVar = baa.a;
        cjk cjkVar = azx.a;
        cjk cjkVar2 = azx.a;
        cji cjiVar = azx.e;
        a = chc.v(chcVar, 0L, azx.c, cjiVar, cjkVar2, null, azx.d, azx.b, null, null, 16645977);
        chc chcVar2 = baa.a;
        cjk cjkVar3 = azx.f;
        cji cjiVar2 = azx.j;
        b = chc.v(chcVar2, 0L, azx.h, cjiVar2, cjkVar3, null, azx.i, azx.g, null, null, 16645977);
        chc chcVar3 = baa.a;
        cjk cjkVar4 = azx.k;
        cji cjiVar3 = azx.o;
        c = chc.v(chcVar3, 0L, azx.m, cjiVar3, cjkVar4, null, azx.n, azx.l, null, null, 16645977);
        chc chcVar4 = baa.a;
        cjk cjkVar5 = azx.p;
        cji cjiVar4 = azx.t;
        d = chc.v(chcVar4, 0L, azx.r, cjiVar4, cjkVar5, null, azx.s, azx.q, null, null, 16645977);
        chc chcVar5 = baa.a;
        cjk cjkVar6 = azx.u;
        cji cjiVar5 = azx.y;
        e = chc.v(chcVar5, 0L, azx.w, cjiVar5, cjkVar6, null, azx.x, azx.v, null, null, 16645977);
        chc chcVar6 = baa.a;
        cjk cjkVar7 = azx.z;
        cji cjiVar6 = azx.D;
        f = chc.v(chcVar6, 0L, azx.B, cjiVar6, cjkVar7, null, azx.C, azx.A, null, null, 16645977);
        chc chcVar7 = baa.a;
        cjk cjkVar8 = azx.E;
        cji cjiVar7 = azx.I;
        g = chc.v(chcVar7, 0L, azx.G, cjiVar7, cjkVar8, null, azx.H, azx.F, null, null, 16645977);
        chc chcVar8 = baa.a;
        cjk cjkVar9 = azx.J;
        cji cjiVar8 = azx.N;
        h = chc.v(chcVar8, 0L, azx.L, cjiVar8, cjkVar9, null, azx.M, azx.K, null, null, 16645977);
        chc chcVar9 = baa.a;
        cjk cjkVar10 = azx.O;
        cji cjiVar9 = azx.S;
        i = chc.v(chcVar9, 0L, azx.Q, cjiVar9, cjkVar10, null, azx.R, azx.P, null, null, 16645977);
        chc chcVar10 = baa.a;
        cjk cjkVar11 = azx.T;
        cji cjiVar10 = azx.X;
        j = chc.v(chcVar10, 0L, azx.V, cjiVar10, cjkVar11, null, azx.W, azx.U, null, null, 16645977);
        chc chcVar11 = baa.a;
        cjk cjkVar12 = azx.Y;
        cji cjiVar11 = azx.ac;
        k = chc.v(chcVar11, 0L, azx.aa, cjiVar11, cjkVar12, null, azx.ab, azx.Z, null, null, 16645977);
        chc chcVar12 = baa.a;
        cjk cjkVar13 = azx.ad;
        cji cjiVar12 = azx.ah;
        l = chc.v(chcVar12, 0L, azx.af, cjiVar12, cjkVar13, null, azx.ag, azx.ae, null, null, 16645977);
        chc chcVar13 = baa.a;
        cjk cjkVar14 = azx.ai;
        cji cjiVar13 = azx.am;
        m = chc.v(chcVar13, 0L, azx.ak, cjiVar13, cjkVar14, null, azx.al, azx.aj, null, null, 16645977);
        chc chcVar14 = baa.a;
        cjk cjkVar15 = azx.an;
        cji cjiVar14 = azx.ar;
        n = chc.v(chcVar14, 0L, azx.ap, cjiVar14, cjkVar15, null, azx.aq, azx.ao, null, null, 16645977);
        chc chcVar15 = baa.a;
        cjk cjkVar16 = azx.as;
        cji cjiVar15 = azx.aw;
        o = chc.v(chcVar15, 0L, azx.au, cjiVar15, cjkVar16, null, azx.av, azx.at, null, null, 16645977);
        chc chcVar16 = baa.a;
        cjk cjkVar17 = azx.ax;
        cji cjiVar16 = azx.aB;
        p = chc.v(chcVar16, 0L, azx.az, cjiVar16, cjkVar17, null, azx.aA, azx.ay, null, null, 16645977);
        chc chcVar17 = baa.a;
        cjk cjkVar18 = azx.aC;
        cji cjiVar17 = azx.aG;
        q = chc.v(chcVar17, 0L, azx.aE, cjiVar17, cjkVar18, null, azx.aF, azx.aD, null, null, 16645977);
        chc chcVar18 = baa.a;
        cjk cjkVar19 = azx.aH;
        cji cjiVar18 = azx.aL;
        r = chc.v(chcVar18, 0L, azx.aJ, cjiVar18, cjkVar19, null, azx.aK, azx.aI, null, null, 16645977);
        chc chcVar19 = baa.a;
        cjk cjkVar20 = azx.aM;
        cji cjiVar19 = azx.aQ;
        s = chc.v(chcVar19, 0L, azx.aO, cjiVar19, cjkVar20, null, azx.aP, azx.aN, null, null, 16645977);
        chc chcVar20 = baa.a;
        cjk cjkVar21 = azx.aR;
        cji cjiVar20 = azx.aV;
        t = chc.v(chcVar20, 0L, azx.aT, cjiVar20, cjkVar21, null, azx.aU, azx.aS, null, null, 16645977);
        chc chcVar21 = baa.a;
        cjk cjkVar22 = azx.aW;
        cji cjiVar21 = azx.ba;
        u = chc.v(chcVar21, 0L, azx.aY, cjiVar21, cjkVar22, null, azx.aZ, azx.aX, null, null, 16645977);
        chc chcVar22 = baa.a;
        cjk cjkVar23 = azx.bb;
        cji cjiVar22 = azx.bf;
        v = chc.v(chcVar22, 0L, azx.bd, cjiVar22, cjkVar23, null, azx.be, azx.bc, null, null, 16645977);
        chc chcVar23 = baa.a;
        cjk cjkVar24 = azx.bg;
        cji cjiVar23 = azx.bk;
        w = chc.v(chcVar23, 0L, azx.bi, cjiVar23, cjkVar24, null, azx.bj, azx.bh, null, null, 16645977);
        chc chcVar24 = baa.a;
        cjk cjkVar25 = azx.bl;
        cji cjiVar24 = azx.bp;
        x = chc.v(chcVar24, 0L, azx.bn, cjiVar24, cjkVar25, null, azx.bo, azx.bm, null, null, 16645977);
        chc chcVar25 = baa.a;
        cjk cjkVar26 = azx.bq;
        cji cjiVar25 = azx.bu;
        y = chc.v(chcVar25, 0L, azx.bs, cjiVar25, cjkVar26, null, azx.bt, azx.br, null, null, 16645977);
        chc chcVar26 = baa.a;
        cjk cjkVar27 = azx.bv;
        cji cjiVar26 = azx.bz;
        z = chc.v(chcVar26, 0L, azx.bx, cjiVar26, cjkVar27, null, azx.by, azx.bw, null, null, 16645977);
        chc chcVar27 = baa.a;
        cjk cjkVar28 = azx.bA;
        cji cjiVar27 = azx.bE;
        A = chc.v(chcVar27, 0L, azx.bC, cjiVar27, cjkVar28, null, azx.bD, azx.bB, null, null, 16645977);
        chc chcVar28 = baa.a;
        cjk cjkVar29 = azx.bF;
        cji cjiVar28 = azx.bJ;
        B = chc.v(chcVar28, 0L, azx.bH, cjiVar28, cjkVar29, null, azx.bI, azx.bG, null, null, 16645977);
        chc chcVar29 = baa.a;
        cjk cjkVar30 = azx.bK;
        cji cjiVar29 = azx.bO;
        C = chc.v(chcVar29, 0L, azx.bM, cjiVar29, cjkVar30, null, azx.bN, azx.bL, null, null, 16645977);
        chc chcVar30 = baa.a;
        cjk cjkVar31 = azx.bP;
        cji cjiVar30 = azx.bT;
        D = chc.v(chcVar30, 0L, azx.bR, cjiVar30, cjkVar31, null, azx.bS, azx.bQ, null, null, 16645977);
    }
}
