package defpackage;

import java.util.Arrays;
import java.util.HashMap;

/* compiled from: PG */
/* loaded from: classes.dex */
public final class cqi {
    int a;
    public final cql b = new cql();
    public final cqk c = new cqk();
    public final cqj d = new cqj();
    public final cqm e = new cqm();
    public HashMap f = new HashMap();
    cqh g;

    public final void a(cqe cqeVar) {
        cqj cqjVar = this.d;
        cqeVar.e = cqjVar.j;
        cqeVar.f = cqjVar.k;
        cqeVar.g = cqjVar.l;
        cqeVar.h = cqjVar.m;
        cqeVar.i = cqjVar.n;
        cqeVar.j = cqjVar.o;
        cqeVar.k = cqjVar.p;
        cqeVar.l = cqjVar.q;
        cqeVar.m = cqjVar.r;
        cqeVar.n = cqjVar.s;
        cqeVar.o = cqjVar.t;
        cqeVar.s = cqjVar.u;
        cqeVar.t = cqjVar.v;
        cqeVar.u = cqjVar.w;
        cqeVar.v = cqjVar.x;
        cqeVar.leftMargin = cqjVar.H;
        cqeVar.rightMargin = cqjVar.I;
        cqeVar.topMargin = cqjVar.J;
        cqeVar.bottomMargin = cqjVar.K;
        cqeVar.A = cqjVar.T;
        cqeVar.B = cqjVar.S;
        cqeVar.x = cqjVar.P;
        cqeVar.z = cqjVar.R;
        cqeVar.G = cqjVar.y;
        cqeVar.H = cqjVar.z;
        cqeVar.p = cqjVar.B;
        cqeVar.q = cqjVar.C;
        cqeVar.r = cqjVar.D;
        cqeVar.I = cqjVar.A;
        cqeVar.X = cqjVar.E;
        cqeVar.Y = cqjVar.F;
        cqeVar.M = cqjVar.V;
        cqeVar.L = cqjVar.W;
        cqeVar.O = cqjVar.Y;
        cqeVar.N = cqjVar.X;
        cqeVar.aa = cqjVar.an;
        cqeVar.ab = cqjVar.ao;
        cqeVar.P = cqjVar.Z;
        cqeVar.Q = cqjVar.aa;
        cqeVar.T = cqjVar.ab;
        cqeVar.U = cqjVar.ac;
        cqeVar.R = cqjVar.ad;
        cqeVar.S = cqjVar.ae;
        cqeVar.V = cqjVar.af;
        cqeVar.W = cqjVar.ag;
        cqeVar.Z = cqjVar.G;
        cqeVar.c = cqjVar.h;
        cqeVar.a = cqjVar.f;
        cqeVar.b = cqjVar.g;
        cqeVar.width = cqjVar.d;
        cqeVar.height = cqjVar.e;
        String str = cqjVar.am;
        if (str != null) {
            cqeVar.ac = str;
        }
        cqeVar.ad = cqjVar.aq;
        cqeVar.setMarginStart(cqjVar.M);
        cqeVar.setMarginEnd(cqjVar.L);
        cqeVar.a();
    }

    public final /* bridge */ /* synthetic */ Object clone() {
        cqi cqiVar = new cqi();
        cqj cqjVar = cqiVar.d;
        cqj cqjVar2 = this.d;
        cqjVar.b = cqjVar2.b;
        cqjVar.d = cqjVar2.d;
        cqjVar.c = cqjVar2.c;
        cqjVar.e = cqjVar2.e;
        cqjVar.f = cqjVar2.f;
        cqjVar.g = cqjVar2.g;
        cqjVar.h = cqjVar2.h;
        cqjVar.i = cqjVar2.i;
        cqjVar.j = cqjVar2.j;
        cqjVar.k = cqjVar2.k;
        cqjVar.l = cqjVar2.l;
        cqjVar.m = cqjVar2.m;
        cqjVar.n = cqjVar2.n;
        cqjVar.o = cqjVar2.o;
        cqjVar.p = cqjVar2.p;
        cqjVar.q = cqjVar2.q;
        cqjVar.r = cqjVar2.r;
        cqjVar.s = cqjVar2.s;
        cqjVar.t = cqjVar2.t;
        cqjVar.u = cqjVar2.u;
        cqjVar.v = cqjVar2.v;
        cqjVar.w = cqjVar2.w;
        cqjVar.x = cqjVar2.x;
        cqjVar.y = cqjVar2.y;
        cqjVar.z = cqjVar2.z;
        cqjVar.A = cqjVar2.A;
        cqjVar.B = cqjVar2.B;
        cqjVar.C = cqjVar2.C;
        cqjVar.D = cqjVar2.D;
        cqjVar.E = cqjVar2.E;
        cqjVar.F = cqjVar2.F;
        cqjVar.G = cqjVar2.G;
        cqjVar.H = cqjVar2.H;
        cqjVar.I = cqjVar2.I;
        cqjVar.J = cqjVar2.J;
        cqjVar.K = cqjVar2.K;
        cqjVar.L = cqjVar2.L;
        cqjVar.M = cqjVar2.M;
        cqjVar.N = cqjVar2.N;
        cqjVar.O = cqjVar2.O;
        cqjVar.P = cqjVar2.P;
        cqjVar.Q = cqjVar2.Q;
        cqjVar.R = cqjVar2.R;
        cqjVar.S = cqjVar2.S;
        cqjVar.T = cqjVar2.T;
        cqjVar.U = cqjVar2.U;
        cqjVar.V = cqjVar2.V;
        cqjVar.W = cqjVar2.W;
        cqjVar.X = cqjVar2.X;
        cqjVar.Y = cqjVar2.Y;
        cqjVar.Z = cqjVar2.Z;
        cqjVar.aa = cqjVar2.aa;
        cqjVar.ab = cqjVar2.ab;
        cqjVar.ac = cqjVar2.ac;
        cqjVar.ad = cqjVar2.ad;
        cqjVar.ae = cqjVar2.ae;
        cqjVar.af = cqjVar2.af;
        cqjVar.ag = cqjVar2.ag;
        cqjVar.ah = cqjVar2.ah;
        cqjVar.ai = cqjVar2.ai;
        cqjVar.aj = cqjVar2.aj;
        cqjVar.am = cqjVar2.am;
        int[] iArr = cqjVar2.ak;
        if (iArr == null || cqjVar2.al != null) {
            cqjVar.ak = null;
        } else {
            cqjVar.ak = Arrays.copyOf(iArr, iArr.length);
        }
        cqjVar.al = cqjVar2.al;
        cqjVar.an = cqjVar2.an;
        cqjVar.ao = cqjVar2.ao;
        cqjVar.ap = cqjVar2.ap;
        cqjVar.aq = cqjVar2.aq;
        cqk cqkVar = cqiVar.c;
        cqk cqkVar2 = this.c;
        cqkVar.b = cqkVar2.b;
        cqkVar.c = cqkVar2.c;
        cqkVar.e = cqkVar2.e;
        cqkVar.f = cqkVar2.f;
        cqkVar.g = cqkVar2.g;
        cqkVar.j = cqkVar2.j;
        cqkVar.h = cqkVar2.h;
        cqkVar.i = cqkVar2.i;
        cql cqlVar = cqiVar.b;
        cql cqlVar2 = this.b;
        cqlVar.a = cqlVar2.a;
        cqlVar.b = cqlVar2.b;
        cqlVar.d = cqlVar2.d;
        cqlVar.e = cqlVar2.e;
        cqlVar.c = cqlVar2.c;
        cqm cqmVar = cqiVar.e;
        cqm cqmVar2 = this.e;
        cqmVar.b = cqmVar2.b;
        cqmVar.c = cqmVar2.c;
        cqmVar.d = cqmVar2.d;
        cqmVar.e = cqmVar2.e;
        cqmVar.f = cqmVar2.f;
        cqmVar.g = cqmVar2.g;
        cqmVar.h = cqmVar2.h;
        cqmVar.i = cqmVar2.i;
        cqmVar.j = cqmVar2.j;
        cqmVar.k = cqmVar2.k;
        cqmVar.l = cqmVar2.l;
        cqmVar.m = cqmVar2.m;
        cqmVar.n = cqmVar2.n;
        cqmVar.o = cqmVar2.o;
        cqiVar.a = this.a;
        cqiVar.g = this.g;
        return cqiVar;
    }
}
