package defpackage;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* compiled from: PG */
/* loaded from: classes2.dex */
public final class oqe {
    public static final oqe A;
    public static final oqe B;
    public static final oqe C;
    public static final oqe D;
    public static final oqe E;
    public static final oqe F;
    public static final oqe G;
    public static final oqe H;
    public static final oqe I;
    public static final oqe J;
    public static final oqe K;
    public static final oqe L;
    public static final oqe M;
    public static final oqe N;
    public static final oqe O;
    public static final oqe P;
    public static final oqe Q;
    public static final oqe R;
    public static final oqe S;
    public static final oqe T;
    public static final oqe U;
    public static final oqe V;
    public static final oqe W;
    public static final oqe X;
    public static final oqe Y;
    public static final oqe Z;
    public static final oqe a;
    public static final oqe aa;
    public static final oqe ab;
    public static final oqe ac;
    private static final /* synthetic */ oqe[] ae;
    public static final oqe b;
    public static final oqe c;
    public static final oqe d;
    public static final oqe e;
    public static final oqe f;
    public static final oqe g;
    public static final oqe h;
    public static final oqe i;
    public static final oqe j;
    public static final oqe k;
    public static final oqe l;
    public static final oqe m;
    public static final oqe n;
    public static final oqe o;
    public static final oqe p;
    public static final oqe q;
    public static final oqe r;
    public static final oqe s;
    public static final oqe t;
    public static final oqe u;
    public static final oqe v;
    public static final oqe w;
    public static final oqe x;
    public static final oqe y;
    public static final oqe z;
    public final String ad;

    static {
        oqe oqeVar = new oqe("ARTIST_OF_THE_DAY", 0, "GAC: Artist of the day");
        a = oqeVar;
        oqe oqeVar2 = new oqe("BATTERY", 1, "Battery");
        b = oqeVar2;
        oqe oqeVar3 = new oqe("BARD_ON_PIXEL", 2, "Bard on Pixel");
        c = oqeVar3;
        oqe oqeVar4 = new oqe("BETTERBUG_BUG_REPORT_SHORTCUT", 3, "BetterBug - Bug report shortcut");
        d = oqeVar4;
        oqe oqeVar5 = new oqe("CALENDAR_MONTH", 4, "Calendar - Month");
        e = oqeVar5;
        oqe oqeVar6 = new oqe("CALENDAR_MONTH_GM3", 5, "Calendar - Month GM3");
        f = oqeVar6;
        oqe oqeVar7 = new oqe("CALENDAR_MONTH_V3_2025", 6, "Calendar - Month v3_2025");
        g = oqeVar7;
        oqe oqeVar8 = new oqe("CALENDAR_SCHEDULE", 7, "Calendar - Schedule");
        h = oqeVar8;
        oqe oqeVar9 = new oqe("CALENDAR_SCHEDULE_GM3", 8, "Calendar - Schedule GM3");
        i = oqeVar9;
        oqe oqeVar10 = new oqe("CALENDAR_SCHEDULE_V3_2025", 9, "Calendar - Schedule v3_2025");
        j = oqeVar10;
        oqe oqeVar11 = new oqe("CONTACTS_BESTIES", 10, "Contacts - Besties");
        k = oqeVar11;
        oqe oqeVar12 = new oqe("CONTACTS_FAVORITE_CONTACTS_GRID", 11, "Contacts - Favorite Contacts Grid");
        l = oqeVar12;
        oqe oqeVar13 = new oqe("CONTACTS_SINGLE_CONTACT", 12, "Contacts - Single Contact");
        m = oqeVar13;
        oqe oqeVar14 = new oqe("DEMO_SIMPLE_LIST", 13, "Demo Simple List");
        n = oqeVar14;
        oqe oqeVar15 = new oqe("DEMO_ANALOG_CLOCK", 14, "Demo Analog Clock");
        o = oqeVar15;
        oqe oqeVar16 = new oqe("DEMO_TOOLBAR", 15, "Demo Toolbar");
        p = oqeVar16;
        oqe oqeVar17 = new oqe("DRIVE_QUICK_ACTION_TOOLBAR", 16, "Drive Quick Action Toolbar");
        q = oqeVar17;
        oqe oqeVar18 = new oqe("DRIVE_SUGGESTIONS", 17, "Drive Suggestions");
        r = oqeVar18;
        oqe oqeVar19 = new oqe("FI_USAGE", 18, "Fi - Usage");
        s = oqeVar19;
        oqe oqeVar20 = new oqe("FI_USAGE_LEGACY", 19, "Fi - Usage (Legacy)");
        t = oqeVar20;
        oqe oqeVar21 = new oqe("GEMINI", 20, "Gemini");
        u = oqeVar21;
        oqe oqeVar22 = new oqe("GMAIL_INBOX_MATERIAL_YOU", 21, "Gmail Inbox: Material You");
        v = oqeVar22;
        oqe oqeVar23 = new oqe("GMAIL_INBOX_LEGACY", 22, "Gmail Inbox: Legacy");
        w = oqeVar23;
        oqe oqeVar24 = new oqe("GOOGLE_APP_SEARCH_WIDGET", 23, "AGA Search Widget");
        x = oqeVar24;
        oqe oqeVar25 = new oqe("GOOGLE_TV_TOP_PICKS", 24, "Google TV - Top Picks");
        y = oqeVar25;
        oqe oqeVar26 = new oqe("KEEP_NOTES_GM3", 25, "Keep Notes GM3");
        z = oqeVar26;
        oqe oqeVar27 = new oqe("KEEP_NOTES_LEGACY", 26, "Keep Notes Legacy");
        A = oqeVar27;
        oqe oqeVar28 = new oqe("KEEP_SINGLE_NOTE", 27, "Keep Single Note");
        B = oqeVar28;
        oqe oqeVar29 = new oqe("KEEP_TOOLBAR_GM3", 28, "Keep Toolbar GM3");
        C = oqeVar29;
        oqe oqeVar30 = new oqe("KEEP_TOOLBAR_LEGACY", 29, "Keep Toolbar Legacy");
        D = oqeVar30;
        oqe oqeVar31 = new oqe("MAPS_SEARCH_WIDGET", 30, "Maps Search Widget");
        E = oqeVar31;
        oqe oqeVar32 = new oqe("MAPS_TRAFFIC_WIDGET", 31, "Maps Nearby Traffic");
        F = oqeVar32;
        oqe oqeVar33 = new oqe("NEWS_LEGACY_WIDGET", 32, "News - Legacy");
        G = oqeVar33;
        oqe oqeVar34 = new oqe("NEWS_GLANCE_WIDGET", 33, "News - Glance");
        H = oqeVar34;
        oqe oqeVar35 = new oqe("PHOTOS_MEMORIES", 34, "Photos - Memories");
        I = oqeVar35;
        oqe oqeVar36 = new oqe("PHOTOS_PEOPLE_AND_PETS", 35, "Photos - People & Pets");
        J = oqeVar36;
        oqe oqeVar37 = new oqe("PIXEL_WEATHER_CURRENT_FORECAST", 36, "Pixel Weather - Current Forecast");
        K = oqeVar37;
        oqe oqeVar38 = new oqe("PIXEL_WEATHER_FULL_FORECAST", 37, "Pixel Weather - Full Forecast");
        L = oqeVar38;
        oqe oqeVar39 = new oqe("PLAY_BOOKS_LEGACY", 38, "PlayBooks: Legacy");
        M = oqeVar39;
        oqe oqeVar40 = new oqe("PLAY_BOOKS_MY_BOOKS", 39, "PlayBooks: MyBooks");
        N = oqeVar40;
        oqe oqeVar41 = new oqe("PLAY_BOOKS_READING_PROGRESS", 40, "PlayBooks: Reading Progress");
        O = oqeVar41;
        oqe oqeVar42 = new oqe("SMARTSPACE", 41, "Ambient Assistant: At a Glance");
        P = oqeVar42;
        oqe oqeVar43 = new oqe("STOCKS", 42, "Stocks");
        Q = oqeVar43;
        oqe oqeVar44 = new oqe("TRANSLATE_QUICK_ACTIONS", 43, "Translate Quick Actions");
        R = oqeVar44;
        oqe oqeVar45 = new oqe("TRANSLATE_SAVED_HISTORY", 44, "Translate Saved History");
        S = oqeVar45;
        oqe oqeVar46 = new oqe("TEST", 45, "Test widget");
        T = oqeVar46;
        oqe oqeVar47 = new oqe("WEATHER", 46, "Weather");
        U = oqeVar47;
        oqe oqeVar48 = new oqe("WEATHER_FREEFORM", 47, "Weather - Freeform");
        V = oqeVar48;
        oqe oqeVar49 = new oqe("YTM_FLIP", 48, "YTM Flip");
        W = oqeVar49;
        oqe oqeVar50 = new oqe("YTM_FREEFORM", 49, "YTM  Freeform");
        X = oqeVar50;
        oqe oqeVar51 = new oqe("YTM_NOW_PLAYING", 50, "YTM Now Playing");
        Y = oqeVar51;
        oqe oqeVar52 = new oqe("YTM_NOW_PLAYING_LEGACY", 51, "YTM Now Playing Legacy");
        Z = oqeVar52;
        oqe oqeVar53 = new oqe("FL_LOCK_UNLOCK", 52, "Family Link Lock Unlock");
        aa = oqeVar53;
        oqe oqeVar54 = new oqe("YT_MAIN_QUICK_ACTIONS", 53, "YouTube - Quick Actions");
        ab = oqeVar54;
        oqe oqeVar55 = new oqe("YT_MAIN_SEARCH", 54, "YouTube - Search");
        ac = oqeVar55;
        oqe[] oqeVarArr = {oqeVar, oqeVar2, oqeVar3, oqeVar4, oqeVar5, oqeVar6, oqeVar7, oqeVar8, oqeVar9, oqeVar10, oqeVar11, oqeVar12, oqeVar13, oqeVar14, oqeVar15, oqeVar16, oqeVar17, oqeVar18, oqeVar19, oqeVar20, oqeVar21, oqeVar22, oqeVar23, oqeVar24, oqeVar25, oqeVar26, oqeVar27, oqeVar28, oqeVar29, oqeVar30, oqeVar31, oqeVar32, oqeVar33, oqeVar34, oqeVar35, oqeVar36, oqeVar37, oqeVar38, oqeVar39, oqeVar40, oqeVar41, oqeVar42, oqeVar43, oqeVar44, oqeVar45, oqeVar46, oqeVar47, oqeVar48, oqeVar49, oqeVar50, oqeVar51, oqeVar52, oqeVar53, oqeVar54, oqeVar55};
        ae = oqeVarArr;
        wcq.P(oqeVarArr);
    }

    private oqe(String str, int i2, String str2) {
        this.ad = str2;
    }

    public static oqe[] values() {
        return (oqe[]) ae.clone();
    }
}
