package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class ppl {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final cji D;
    public static final ciy E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final cji I;
    public static final ciy J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final cji N;
    public static final ciy O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final cji S;
    public static final ciy T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final cji X;
    public static final ciy Y;
    public static final long Z;
    public static final ciy a;
    public static final long aa;
    public static final long ab;
    public static final cji ac;
    public static final ciy ad;
    public static final long ae;
    public static final long af;
    public static final long ag;
    public static final cji ah;
    public static final ciy ai;
    public static final long aj;
    public static final long ak;
    public static final long al;
    public static final cji am;
    public static final ciy an;
    public static final long ao;
    public static final long ap;
    public static final long aq;
    public static final cji ar;
    public static final ciy as;
    public static final long at;
    public static final long au;
    public static final long av;
    public static final cji aw;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final cji e;
    public static final ciy f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final cji j;
    public static final ciy k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final cji o;
    public static final ciy p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final cji t;
    public static final ciy u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final cji y;
    public static final ciy z;

    static {
        ciy ciyVar = ppm.a;
        a = ppm.b;
        b = clw.t(24.0d);
        c = clw.v(16);
        d = clw.t(0.0d);
        e = ppm.e;
        f = ppm.b;
        g = clw.t(20.0d);
        h = clw.v(14);
        i = clw.t(0.0d);
        j = ppm.e;
        k = ppm.b;
        l = clw.t(16.0d);
        m = clw.v(12);
        n = clw.t(0.1d);
        o = ppm.e;
        p = ppm.a;
        q = clw.t(64.0d);
        r = clw.v(57);
        s = clw.t(0.0d);
        t = ppm.e;
        u = ppm.a;
        v = clw.t(52.0d);
        w = clw.v(45);
        x = clw.t(0.0d);
        y = ppm.e;
        z = ppm.a;
        A = clw.t(44.0d);
        B = clw.v(36);
        C = clw.t(0.0d);
        D = ppm.e;
        E = ppm.a;
        F = clw.t(40.0d);
        G = clw.v(32);
        H = clw.t(0.0d);
        I = ppm.e;
        J = ppm.a;
        K = clw.t(36.0d);
        L = clw.v(28);
        M = clw.t(0.0d);
        N = ppm.e;
        O = ppm.a;
        P = clw.t(32.0d);
        Q = clw.v(24);
        R = clw.t(0.0d);
        S = ppm.e;
        T = ppm.b;
        U = clw.t(20.0d);
        V = clw.v(14);
        W = clw.t(0.0d);
        X = ppm.d;
        Y = ppm.b;
        Z = clw.t(16.0d);
        aa = clw.v(12);
        ab = clw.t(0.1d);
        ac = ppm.d;
        ad = ppm.b;
        ae = clw.t(16.0d);
        af = clw.v(11);
        ag = clw.t(0.1d);
        ah = ppm.d;
        ai = ppm.a;
        aj = clw.t(28.0d);
        ak = clw.v(22);
        al = clw.t(0.0d);
        am = ppm.e;
        an = ppm.b;
        ao = clw.t(24.0d);
        ap = clw.v(16);
        aq = clw.t(0.0d);
        ar = ppm.d;
        as = ppm.b;
        at = clw.t(20.0d);
        au = clw.v(14);
        av = clw.t(0.0d);
        aw = ppm.d;
    }
}
