package defpackage;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class ppr {
    public static final ciy U;
    public static final cji V;
    public static final cjh W;
    public static final ciy X;
    public static final cji Y;
    public static final cjh Z;
    public static final cjh aA;
    public static final ciy aB;
    public static final cji aC;
    public static final cjh aD;
    public static final ciy aE;
    public static final cji aF;
    public static final cjh aG;
    public static final ciy aH;
    public static final cji aI;
    public static final cjh aJ;
    public static final ciy aK;
    public static final cji aL;
    public static final ciy aa;
    public static final cji ab;
    public static final cjh ac;
    public static final ciy ad;
    public static final cji ae;
    public static final cjh af;
    public static final ciy ag;
    public static final cji ah;
    public static final cjh ai;
    public static final ciy aj;
    public static final cji ak;
    public static final cjh al;
    public static final ciy am;
    public static final cji an;
    public static final cjh ao;
    public static final ciy ap;
    public static final cji aq;
    public static final cjh ar;
    public static final ciy as;
    public static final cji at;
    public static final cjh au;
    public static final ciy av;
    public static final cji aw;
    public static final cjh ax;
    public static final ciy ay;
    public static final cji az;
    public static final long a = clw.t(24.0d);
    private static final float aM = 16.0f;
    private static final float aN = 100.0f;
    public static final long b = clw.v(16);
    public static final long c = clw.t(0.0d);
    private static final float aO = 100.0f;
    private static final float aP = 500.0f;
    public static final long d = clw.t(20.0d);
    private static final float aQ = 14.0f;
    private static final float aR = 100.0f;
    public static final long e = clw.v(14);
    public static final long f = clw.t(0.0d);
    private static final float aS = 100.0f;
    private static final float aT = 500.0f;
    public static final long g = clw.t(16.0d);
    private static final float aU = 12.0f;
    private static final float aV = 100.0f;
    public static final long h = clw.v(12);
    public static final long i = clw.t(0.0d);
    private static final float aW = 100.0f;
    private static final float aX = 500.0f;
    public static final long j = clw.t(64.0d);
    private static final float aY = 57.0f;
    private static final float aZ = 100.0f;
    public static final long k = clw.v(57);
    public static final long l = clw.t(0.0d);
    private static final float ba = 100.0f;
    private static final float bb = 500.0f;
    public static final long m = clw.t(52.0d);
    private static final float bc = 45.0f;
    private static final float bd = 100.0f;
    public static final long n = clw.v(45);
    public static final long o = clw.t(0.0d);
    private static final float be = 100.0f;
    private static final float bf = 500.0f;
    public static final long p = clw.t(44.0d);
    private static final float bg = 36.0f;
    private static final float bh = 100.0f;
    public static final long q = clw.v(36);
    public static final long r = clw.t(0.0d);
    private static final float bi = 100.0f;
    private static final float bj = 500.0f;
    public static final long s = clw.t(40.0d);
    private static final float bk = 32.0f;
    private static final float bl = 100.0f;
    public static final long t = clw.v(32);
    public static final long u = clw.t(0.0d);
    private static final float bm = 100.0f;
    private static final float bn = 500.0f;
    public static final long v = clw.t(36.0d);
    private static final float bo = 28.0f;
    private static final float bp = 100.0f;
    public static final long w = clw.v(28);
    public static final long x = clw.t(0.0d);
    private static final float bq = 100.0f;
    private static final float br = 500.0f;
    public static final long y = clw.t(32.0d);
    private static final float bs = 24.0f;
    private static final float bt = 100.0f;
    public static final long z = clw.v(24);
    public static final long A = clw.t(0.0d);
    private static final float bu = 100.0f;
    private static final float bv = 500.0f;
    public static final long B = clw.t(20.0d);
    private static final float bw = 14.0f;
    private static final float bx = 100.0f;
    public static final long C = clw.v(14);
    public static final long D = clw.t(0.0d);
    private static final float by = 100.0f;
    private static final float bz = 600.0f;
    public static final long E = clw.t(16.0d);
    private static final float bA = 12.0f;
    private static final float bB = 100.0f;
    public static final long F = clw.v(12);
    public static final long G = clw.t(0.0d);
    private static final float bC = 100.0f;
    private static final float bD = 600.0f;
    public static final long H = clw.t(16.0d);
    private static final float bE = 11.0f;
    private static final float bF = 100.0f;
    public static final long I = clw.v(11);
    public static final long J = clw.t(0.0d);
    private static final float bG = 100.0f;
    private static final float bH = 600.0f;
    public static final long K = clw.t(28.0d);
    private static final float bI = 22.0f;
    private static final float bJ = 100.0f;
    public static final long L = clw.v(22);
    public static final long M = clw.t(0.0d);
    private static final float bK = 100.0f;
    private static final float bL = 500.0f;
    public static final long N = clw.t(24.0d);
    private static final float bM = 16.0f;
    private static final float bN = 100.0f;
    public static final long O = clw.v(16);
    public static final long P = clw.t(0.0d);
    private static final float bO = 100.0f;
    private static final float bP = 600.0f;
    public static final long Q = clw.t(20.0d);
    private static final float bQ = 14.0f;
    private static final float bR = 100.0f;
    public static final long R = clw.v(14);
    public static final long S = clw.t(0.0d);
    private static final float bS = 100.0f;
    private static final float bT = 600.0f;
    public static final cjh T = new cjh(cko.g("ROND", 100.0f), cko.g("slnt", 0.0f), cko.g("opsz", 16.0f), cko.g("GRAD", 0.0f), cko.g("wdth", 100.0f), cko.g("wght", 500.0f));

    static {
        ciy ciyVar = ppm.a;
        U = ppm.b;
        V = ppm.d;
        W = new cjh(cko.g("GRAD", 0.0f), cko.g("wght", 500.0f), cko.g("opsz", 14.0f), cko.g("slnt", 0.0f), cko.g("wdth", 100.0f), cko.g("ROND", 100.0f));
        X = ppm.b;
        Y = ppm.d;
        Z = new cjh(cko.g("wdth", 100.0f), cko.g("slnt", 0.0f), cko.g("GRAD", 0.0f), cko.g("wght", 500.0f), cko.g("opsz", 12.0f), cko.g("ROND", 100.0f));
        aa = ppm.b;
        ab = ppm.d;
        ac = new cjh(cko.g("GRAD", 0.0f), cko.g("ROND", 100.0f), cko.g("opsz", 57.0f), cko.g("wght", 500.0f), cko.g("wdth", 100.0f), cko.g("slnt", 0.0f));
        ad = ppm.a;
        ae = ppm.d;
        af = new cjh(cko.g("slnt", 0.0f), cko.g("wdth", 100.0f), cko.g("GRAD", 0.0f), cko.g("wght", 500.0f), cko.g("opsz", 45.0f), cko.g("ROND", 100.0f));
        ag = ppm.a;
        ah = ppm.d;
        ai = new cjh(cko.g("opsz", 36.0f), cko.g("wght", 500.0f), cko.g("ROND", 100.0f), cko.g("wdth", 100.0f), cko.g("slnt", 0.0f), cko.g("GRAD", 0.0f));
        aj = ppm.a;
        ak = ppm.d;
        al = new cjh(cko.g("slnt", 0.0f), cko.g("GRAD", 0.0f), cko.g("ROND", 100.0f), cko.g("wdth", 100.0f), cko.g("wght", 500.0f), cko.g("opsz", 32.0f));
        am = ppm.a;
        an = ppm.d;
        ao = new cjh(cko.g("wght", 500.0f), cko.g("GRAD", 0.0f), cko.g("wdth", 100.0f), cko.g("slnt", 0.0f), cko.g("opsz", 28.0f), cko.g("ROND", 100.0f));
        ap = ppm.a;
        aq = ppm.d;
        ar = new cjh(cko.g("GRAD", 0.0f), cko.g("wdth", 100.0f), cko.g("slnt", 0.0f), cko.g("opsz", 24.0f), cko.g("ROND", 100.0f), cko.g("wght", 500.0f));
        as = ppm.a;
        at = ppm.d;
        au = new cjh(cko.g("wdth", 100.0f), cko.g("opsz", 14.0f), cko.g("wght", 600.0f), cko.g("ROND", 100.0f), cko.g("GRAD", 0.0f), cko.g("slnt", 0.0f));
        av = ppm.b;
        aw = ppm.c;
        ax = new cjh(cko.g("wght", 600.0f), cko.g("GRAD", 0.0f), cko.g("ROND", 100.0f), cko.g("slnt", 0.0f), cko.g("wdth", 100.0f), cko.g("opsz", 12.0f));
        ay = ppm.b;
        az = ppm.c;
        aA = new cjh(cko.g("wdth", 100.0f), cko.g("wght", 600.0f), cko.g("ROND", 100.0f), cko.g("slnt", 0.0f), cko.g("opsz", 11.0f), cko.g("GRAD", 0.0f));
        aB = ppm.b;
        aC = ppm.c;
        aD = new cjh(cko.g("wght", 500.0f), cko.g("ROND", 100.0f), cko.g("slnt", 0.0f), cko.g("GRAD", 0.0f), cko.g("opsz", 22.0f), cko.g("wdth", 100.0f));
        aE = ppm.a;
        aF = ppm.d;
        aG = new cjh(cko.g("ROND", 100.0f), cko.g("opsz", 16.0f), cko.g("GRAD", 0.0f), cko.g("wght", 600.0f), cko.g("wdth", 100.0f), cko.g("slnt", 0.0f));
        aH = ppm.b;
        aI = ppm.c;
        aJ = new cjh(cko.g("wght", 600.0f), cko.g("wdth", 100.0f), cko.g("slnt", 0.0f), cko.g("GRAD", 0.0f), cko.g("opsz", 14.0f), cko.g("ROND", 100.0f));
        aK = ppm.b;
        aL = ppm.c;
    }
}
