package defpackage;

import android.R;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class sok {
    public static final int[] a = {R.attr.background, R.attr.touchscreenBlocksFocus, R.attr.keyboardNavigationCluster, com.google.android.videos.R.attr.elevation, com.google.android.videos.R.attr.expanded, com.google.android.videos.R.attr.liftOnScroll, com.google.android.videos.R.attr.liftOnScrollColor, com.google.android.videos.R.attr.liftOnScrollTargetViewId, com.google.android.videos.R.attr.statusBarForeground};
    public static final int[] b = {com.google.android.videos.R.attr.layout_scrollEffect, com.google.android.videos.R.attr.layout_scrollFlags, com.google.android.videos.R.attr.layout_scrollInterpolator};
    public static final int[] c = {com.google.android.videos.R.attr.collapsedSubtitleTextAppearance, com.google.android.videos.R.attr.collapsedSubtitleTextColor, com.google.android.videos.R.attr.collapsedTitleGravity, com.google.android.videos.R.attr.collapsedTitleGravityMode, com.google.android.videos.R.attr.collapsedTitleTextAppearance, com.google.android.videos.R.attr.collapsedTitleTextColor, com.google.android.videos.R.attr.contentScrim, com.google.android.videos.R.attr.expandedSubtitleTextAppearance, com.google.android.videos.R.attr.expandedSubtitleTextColor, com.google.android.videos.R.attr.expandedTitleGravity, com.google.android.videos.R.attr.expandedTitleMargin, com.google.android.videos.R.attr.expandedTitleMarginBottom, com.google.android.videos.R.attr.expandedTitleMarginEnd, com.google.android.videos.R.attr.expandedTitleMarginStart, com.google.android.videos.R.attr.expandedTitleMarginTop, com.google.android.videos.R.attr.expandedTitleSpacing, com.google.android.videos.R.attr.expandedTitleTextAppearance, com.google.android.videos.R.attr.expandedTitleTextColor, com.google.android.videos.R.attr.extraMultilineHeightEnabled, com.google.android.videos.R.attr.forceApplySystemWindowInsetTop, com.google.android.videos.R.attr.maxLines, com.google.android.videos.R.attr.scrimAnimationDuration, com.google.android.videos.R.attr.scrimVisibleHeightTrigger, com.google.android.videos.R.attr.statusBarScrim, com.google.android.videos.R.attr.subtitle, com.google.android.videos.R.attr.subtitleMaxLines, com.google.android.videos.R.attr.title, com.google.android.videos.R.attr.titleCollapseMode, com.google.android.videos.R.attr.titleEnabled, com.google.android.videos.R.attr.titleMaxLines, com.google.android.videos.R.attr.titlePositionInterpolator, com.google.android.videos.R.attr.titleTextEllipsize, com.google.android.videos.R.attr.toolbarId};
    public static final int[] d = {com.google.android.videos.R.attr.layout_collapseMode, com.google.android.videos.R.attr.layout_collapseParallaxMultiplier};
    public static final int[] e = {com.google.android.videos.R.attr.logoAdjustViewBounds, com.google.android.videos.R.attr.logoScaleType, com.google.android.videos.R.attr.navigationIconTint, com.google.android.videos.R.attr.subtitleCentered, com.google.android.videos.R.attr.titleCentered};
    public static final int[] f = {com.google.android.videos.R.attr.behavior_overlapTop};
}
