package defpackage;

import android.R;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class srj {
    public static final int[] a = {R.attr.textAppearance, R.attr.textSize, R.attr.textColor, R.attr.ellipsize, R.attr.maxWidth, R.attr.text, R.attr.checkable, com.google.android.videos.R.attr.checkedIcon, com.google.android.videos.R.attr.checkedIconEnabled, com.google.android.videos.R.attr.checkedIconTint, com.google.android.videos.R.attr.checkedIconVisible, com.google.android.videos.R.attr.chipBackgroundColor, com.google.android.videos.R.attr.chipCornerRadius, com.google.android.videos.R.attr.chipEndPadding, com.google.android.videos.R.attr.chipIcon, com.google.android.videos.R.attr.chipIconEnabled, com.google.android.videos.R.attr.chipIconSize, com.google.android.videos.R.attr.chipIconTint, com.google.android.videos.R.attr.chipIconVisible, com.google.android.videos.R.attr.chipMinHeight, com.google.android.videos.R.attr.chipMinTouchTargetSize, com.google.android.videos.R.attr.chipStartPadding, com.google.android.videos.R.attr.chipStrokeColor, com.google.android.videos.R.attr.chipStrokeWidth, com.google.android.videos.R.attr.chipSurfaceColor, com.google.android.videos.R.attr.closeIcon, com.google.android.videos.R.attr.closeIconEnabled, com.google.android.videos.R.attr.closeIconEndPadding, com.google.android.videos.R.attr.closeIconSize, com.google.android.videos.R.attr.closeIconStartPadding, com.google.android.videos.R.attr.closeIconTint, com.google.android.videos.R.attr.closeIconVisible, com.google.android.videos.R.attr.ensureMinTouchTargetSize, com.google.android.videos.R.attr.hideMotionSpec, com.google.android.videos.R.attr.iconEndPadding, com.google.android.videos.R.attr.iconStartPadding, com.google.android.videos.R.attr.rippleColor, com.google.android.videos.R.attr.shapeAppearance, com.google.android.videos.R.attr.shapeAppearanceOverlay, com.google.android.videos.R.attr.showMotionSpec, com.google.android.videos.R.attr.textEndPadding, com.google.android.videos.R.attr.textStartPadding};
    public static final int[] b = {com.google.android.videos.R.attr.checkedChip, com.google.android.videos.R.attr.chipSpacing, com.google.android.videos.R.attr.chipSpacingHorizontal, com.google.android.videos.R.attr.chipSpacingVertical, com.google.android.videos.R.attr.selectionRequired, com.google.android.videos.R.attr.singleLine, com.google.android.videos.R.attr.singleSelection};
}
