package defpackage;

import android.R;

/* compiled from: PG */
/* loaded from: classes2.dex */
public final class tao {
    public static final int[] a = {R.attr.enabled, R.attr.value, R.attr.orientation, R.attr.stepSize, R.attr.valueFrom, R.attr.valueTo, com.google.android.videos.R.attr.centered, com.google.android.videos.R.attr.continuousModeTickCount, com.google.android.videos.R.attr.haloColor, com.google.android.videos.R.attr.haloRadius, com.google.android.videos.R.attr.labelBehavior, com.google.android.videos.R.attr.labelStyle, com.google.android.videos.R.attr.minTouchTargetSize, com.google.android.videos.R.attr.thumbColor, com.google.android.videos.R.attr.thumbElevation, com.google.android.videos.R.attr.thumbHeight, com.google.android.videos.R.attr.thumbRadius, com.google.android.videos.R.attr.thumbStrokeColor, com.google.android.videos.R.attr.thumbStrokeWidth, com.google.android.videos.R.attr.thumbTrackGapSize, com.google.android.videos.R.attr.thumbWidth, com.google.android.videos.R.attr.tickColor, com.google.android.videos.R.attr.tickColorActive, com.google.android.videos.R.attr.tickColorInactive, com.google.android.videos.R.attr.tickRadiusActive, com.google.android.videos.R.attr.tickRadiusInactive, com.google.android.videos.R.attr.tickVisibilityMode, com.google.android.videos.R.attr.tickVisible, com.google.android.videos.R.attr.trackColor, com.google.android.videos.R.attr.trackColorActive, com.google.android.videos.R.attr.trackColorInactive, com.google.android.videos.R.attr.trackCornerSize, com.google.android.videos.R.attr.trackHeight, com.google.android.videos.R.attr.trackIconActiveColor, com.google.android.videos.R.attr.trackIconActiveEnd, com.google.android.videos.R.attr.trackIconActiveStart, com.google.android.videos.R.attr.trackIconInactiveColor, com.google.android.videos.R.attr.trackIconInactiveEnd, com.google.android.videos.R.attr.trackIconInactiveStart, com.google.android.videos.R.attr.trackIconSize, com.google.android.videos.R.attr.trackInsideCornerSize, com.google.android.videos.R.attr.trackStopIndicatorSize};
}
