package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public interface zln {
    public static final zjb a;
    public static final zjb b;
    public static final zjb c;
    public static final zjb d;
    public static final zjb e;
    public static final zjb f;
    public static final zjb g;
    public static final zjb h;
    public static final zjb i;
    public static final zjb j;
    public static final zjb k;
    public static final zjb l;
    public static final zjb m;
    public static final zjb n;
    public static final zjb o;
    public static final zjb p;
    public static final zjb q;
    public static final zjb r;
    public static final zjb s;
    public static final zjb t;
    public static final zjb u;

    static {
        zjb zjbVar = new zjb("2.16.840.1.101.3.4");
        a = zjbVar;
        zjb zjbVarF = zjbVar.f("2");
        b = zjbVarF;
        c = zjbVarF.f("1");
        d = zjbVarF.f("2");
        e = zjbVarF.f("3");
        f = zjbVarF.f("4");
        g = zjbVarF.f("5");
        h = zjbVarF.f("6");
        i = zjbVarF.f("7");
        j = zjbVarF.f("8");
        k = zjbVarF.f("9");
        l = zjbVarF.f("10");
        m = zjbVarF.f("11");
        n = zjbVarF.f("12");
        zjbVarF.f("13");
        zjbVarF.f("14");
        zjbVarF.f("15");
        zjbVarF.f("16");
        zjbVarF.f("17");
        o = zjbVarF.f("18");
        zjbVarF.f("19");
        zjbVarF.f("20");
        zjb zjbVarF2 = zjbVar.f("1");
        p = zjbVarF2;
        zjbVarF2.f("1");
        zjbVarF2.f("2");
        zjbVarF2.f("3");
        zjbVarF2.f("4");
        zjbVarF2.f("5");
        zjbVarF2.f("6");
        zjbVarF2.f("7");
        zjbVarF2.f("8");
        zjbVarF2.f("9");
        zjbVarF2.f("21");
        zjbVarF2.f("22");
        zjbVarF2.f("23");
        zjbVarF2.f("24");
        zjbVarF2.f("25");
        zjbVarF2.f("26");
        zjbVarF2.f("27");
        zjbVarF2.f("28");
        zjbVarF2.f("29");
        zjbVarF2.f("41");
        zjbVarF2.f("42");
        zjbVarF2.f("43");
        zjbVarF2.f("44");
        zjbVarF2.f("45");
        zjbVarF2.f("46");
        zjbVarF2.f("47");
        zjbVarF2.f("48");
        zjbVarF2.f("49");
        zjb zjbVarF3 = zjbVar.f("3");
        q = zjbVarF3;
        r = zjbVarF3.f("1");
        s = zjbVarF3.f("2");
        t = zjbVarF3.f("3");
        u = zjbVarF3.f("4");
        zjbVarF3.f("5");
        zjbVarF3.f("6");
        zjbVarF3.f("7");
        zjbVarF3.f("8");
        zjbVarF3.f("9");
        zjbVarF3.f("10");
        zjbVarF3.f("11");
        zjbVarF3.f("12");
        zjbVarF3.f("13");
        zjbVarF3.f("14");
        zjbVarF3.f("15");
        zjbVarF3.f("16");
    }
}
