package defpackage;

/* compiled from: PG */
/* loaded from: classes3.dex */
public interface zni {
    public static final zjb a;
    public static final zjb b;
    public static final zjb c;
    public static final zjb d;
    public static final zjb e;
    public static final zjb f;
    public static final zjb g;
    public static final zjb h;
    public static final zjb i;
    public static final zjb j;
    public static final zjb k;
    public static final zjb l;
    public static final zjb m;
    public static final zjb n;
    public static final zjb o;
    public static final zjb p;
    public static final zjb q;
    public static final zjb r;
    public static final zjb s;
    public static final zjb t;

    static {
        zjb zjbVar = new zjb("1.2.840.10045");
        a = zjbVar;
        zjb zjbVarF = zjbVar.f("1");
        b = zjbVarF;
        zjbVarF.f("1");
        zjb zjbVarF2 = zjbVarF.f("2");
        c = zjbVarF2;
        zjbVarF2.f("3.1");
        zjbVarF2.f("3.2");
        zjbVarF2.f("3.3");
        zjb zjbVarF3 = zjbVar.f("4");
        d = zjbVarF3;
        e = zjbVarF3.f("1");
        zjb zjbVarF4 = zjbVar.f("2");
        f = zjbVarF4;
        zjbVarF4.f("1");
        zjb zjbVarF5 = zjbVarF3.f("3");
        g = zjbVarF5;
        h = zjbVarF5.f("1");
        i = zjbVarF5.f("2");
        j = zjbVarF5.f("3");
        k = zjbVarF5.f("4");
        zjb zjbVarF6 = zjbVar.f("3");
        l = zjbVarF6;
        zjb zjbVarF7 = zjbVarF6.f("0");
        m = zjbVarF7;
        zjbVarF7.f("1");
        zjbVarF7.f("2");
        zjbVarF7.f("3");
        zjbVarF7.f("4");
        zjbVarF7.f("5");
        zjbVarF7.f("6");
        zjbVarF7.f("7");
        zjbVarF7.f("8");
        zjbVarF7.f("9");
        zjbVarF7.f("10");
        zjbVarF7.f("11");
        zjbVarF7.f("12");
        zjbVarF7.f("13");
        zjbVarF7.f("14");
        zjbVarF7.f("15");
        zjbVarF7.f("16");
        zjbVarF7.f("17");
        zjbVarF7.f("18");
        zjbVarF7.f("19");
        zjbVarF7.f("20");
        zjb zjbVarF8 = zjbVarF6.f("1");
        n = zjbVarF8;
        zjbVarF8.f("1");
        zjbVarF8.f("2");
        zjbVarF8.f("3");
        zjbVarF8.f("4");
        zjbVarF8.f("5");
        zjbVarF8.f("6");
        zjbVarF8.f("7");
        new zjb("1.2.840.10040.4.1");
        o = new zjb("1.2.840.10040.4.3");
        zjb zjbVar2 = new zjb("1.3.133.16.840.63.0");
        p = zjbVar2;
        zjbVar2.f("2");
        zjbVar2.f("3");
        zjbVar2.f("16");
        zjb zjbVar3 = new zjb("1.2.840.10046");
        q = zjbVar3;
        zjbVar3.f("2.1");
        zjb zjbVarF9 = zjbVar3.f("3");
        r = zjbVarF9;
        zjbVarF9.f("1");
        zjbVarF9.f("2");
        zjbVarF9.f("3");
        zjbVarF9.f("4");
        zjbVarF9.f("5");
        zjbVarF9.f("6");
        zjbVarF9.f("7");
        zjbVarF9.f("8");
        zjb zjbVar4 = new zjb("1.3.133.16.840.9.44");
        s = zjbVar4;
        zjb zjbVarF10 = zjbVar4.f("1");
        t = zjbVarF10;
        zjbVarF10.f("1");
        zjbVarF10.f("2");
    }
}
